mendersoftware/mender

- ioctl.go
- ioctl_32_bit.go
- ioctl_64_bit.go
- rootfs.go
- rootfs_test.go
We need to go outside the comfort zone and do some low level OS
probing with syscall and unsafe pointers to achieve this.
> Implement proper partition size detection.

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/mendersoftware/log/log.go
- Godeps/_workspace/src/github.com/mendersoftware/mendertesting/mendertesting.go
- main.go
- main_test.go
- rootfs.go
- rootfs_test.go
It is used by specifying a URL to download the update from. Otherwise
it works exactly like the file updater.
> MEN-55: Add network update capability to Mender.

- .travis.yml
> Fail build once cyclomatic complexity is  >= 15

- device.go
- mender.go
- rootfs.go
> More debug output

- .travis.yml
- check_signed_off.sh
Signed-off-by: Gregorio Di Stefano <Gregorio.Di.Stefano@mender.io>
> Run ./check_signed_off.sh in before_script

- .travis.yml
- client.go
- daemon.go
- partitions.go
> removed dead code and unsed variables, updated .travis.yml

- README.md
Signed-off-by: ThomasRyd <thomas@mender.io>
> fix contrib link

- CONTRIBUTING.md
- README.md
Signed-off-by: michaelatmender <michael.clelland@mender.io>
> Removed links to incomplete bugtracker and edited text

- HACKING.md
> Add very basic version of Mender client architecture overview.

- daemon.go
- daemon_test.go
- device.go
- main.go
- main_test.go
- mender-default-test.conf
- mender.go
- mender_test.go
- partitions.go
- partitions_test.go
See individual commit messages for descriptions.
> MEN-440: Dynamic/configurable partition devices

- client_auth.go
- client_auth_test.go
Some fixes for issues found during integration.
> authorization fixes

- client.go
- client_auth.go
- client_auth_test.go
- client_test.go
- client_update.go
Use stable API endpoints. Depends on https://github.com/mendersoftware/mender-api-gateway-docker/pull/7 for API gateway setup.
@pasinskim @kacf
> stable API endpoints

- Godeps/Godeps.json
- vendor/github.com/mendersoftware/mendertesting/check_license.sh
- vendor/github.com/mendersoftware/mendertesting/check_signed_off.sh
- vendor/github.com/mendersoftware/mendertesting/licenses.go
> Update to latest mendertesting.

- mender.go
- state.go
State transitions in a diagram.
> Document state transitions

- mender.go
- state.go
- state_test.go
> Mandatory update status reporting

- client_log.go
- client_log_test.go
- daemon_test.go
- deployment_logger.go
- deployment_logger_test.go
- mender.go
- mender_test.go
- state.go
- state_test.go
> Make sure to enable and disable deployment logging when needed.

- client_log.go
- client_status.go
> Add headers to status and log sending requests.

- client_log.go
- client_status.go
- client_update.go
- state.go
make sure that we close Body of each http.Response
> close http.Response Body

- client_status.go
- daemon_test.go
- deployment_logger.go
- deployment_logger_test.go
- device.go
- device_test.go
- main.go
- mender.go
- state.go
- state_test.go
Add new update verification and rollback states.
Improve logging and fix default log level.
Refactor log and status sending. Fix some infinite loops while storing deployment logs.
Fix sending empty logs to server.
Update tests and documentation.
> Improve Mender state logic

- device.go
> Simplify copying update stream to inactive partition.

- mender.go
> Warn update will not be performed if update image id same as current

- inventory_data.go
- mender.go
- mender_test.go
@pasinskim @kacf @GregorioDiStefano
> do not submit empty inventory updates

- vendor/github.com/mendersoftware/log/log.go
> Update log library.

- inventory.go
- inventory_data.go
- mender.go
- mender_test.go
> Add required `device_type` to inventory data.

- support/mender-inventory-hostinfo
Example inventory script for collecting host related information.
@pasinskim @GregorioDiStefano @kacf
> support/mender-invnetory-hostinfo: example inventory script

- mender.go
- mender_test.go
> include mender client version in inventory attributes

- auth.go
- client_update.go
- client_update_test.go
- mender.go
- mender_test.go
- state.go
> Make sure to remove authentication token if device is unauthorized.

- deployment_logger_test.go
- vendor/github.com/mendersoftware/log/log.go
Make sure that we are testing receiving log in the hook with level
lower that the application log level.
> Update `log` dependency and improve logging test.

- Godeps/Godeps.json
- vendor/github.com/mendersoftware/mendertesting/check_signed_off.sh
> Update mendertesting and log dependencies.

- state.go
> Clear state data before changing to init state after error.

- state.go
> Do not clear state data if can not send report to the server.

- identity_data.go
- identity_data_test.go
- inventory_data.go
- inventory_data_test.go
- utils/kvparser.go
- utils/kvparser_test.go
Use common KeyValParser for handling identity/inventory helpers output.
Fixes: https://tracker.mender.io/browse/MEN-662
> inventory identity same protocol

- inventory_data.go
- mender.go
A couple of fixes for 1.7.x go vet.
@pasinskim @kacf @GregorioDiStefano
> more go 1.7.x vet

- client/client_status.go
- client/client_status_test.go
- client/test/server.go
- mender.go
- mender_test.go
- state.go
- state_test.go
> deployment abort handling

- client/client_status.go
- state.go
- state_test.go
> Already installed update handling

- support/mender-device-identity
- support/mender-inventory-hostinfo
- support/mender-inventory-network
@pasinskim @bboozzoo 
Remove pipefail as they dont work with sh
> remove pipefail from support scripts

- vendor/github.com/mendersoftware/artifacts/parser/generic_parser.go
- vendor/github.com/mendersoftware/artifacts/parser/rootfs_parser.go
- vendor/github.com/mendersoftware/artifacts/reader/reader.go
- vendor/github.com/mendersoftware/artifacts/test_utils/test_utils.go
> Update artifact library dependencies.

- auth_test.go
- daemon_test.go
- dbstore.go
- dirstore.go
- fileseqnum_test.go
- keystore_test.go
- mender.go
- mender_test.go
- state_test.go
- store.go
- store_test.go
- utils/mem_store.go
- utils/mem_store_test.go
@bboozzoo @pasinskim 
As discussed with Maciej, it's useful to move MemStore to utils, but that required me to more Store as well.
> Move Store interface and MemStore to utils package

- client/client_update.go
> warn when call to /update returns invalid status code

- client/client_update.go
- client/test/server.go
> changed update check api call to match actual backend route

- client/client_update.go
- client/client_update_test.go
- client/test/server.go
- mender.go
- mender_test.go
https://tracker.mender.io/browse/MEN-768
> send artifact name & device type in update check requests

- client/client_update.go
- client/client_update_test.go
- client/test/server.go
- mender.go
- mender_test.go
- state.go
- state_test.go
Update client to use new format of API as described here:
https://tracker.mender.io/browse/MEN-737
> Change update response to reflect API changes.

- state.go
> fixed typo is 'state wait' log message

- mender.go
- mender_test.go
- support/mender-inventory-hostinfo
- support/mender-inventory-network
Remove non-static attributes and add more descriptive names for
remaining ones.
> MEN-928 Clean up default device inventory.

- state.go
- state_test.go
> store: Clarify variable name and comment.

- .travis.yml
- Makefile
Best reviewed commit by commit.
> Makefile fixes and switch to codecov.io

- mender.go
> print descriptive state information string instead of integer

- client/client.go
- client/client_auth_test.go
- client/client_test.go
- client/client_update_test.go
- client/test/server.go
- mender_test.go
@mendersoftware/rndity @kacf 
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
> MEN-963: Update client to use new API versioning.

- CONTRIBUTING.md
> CONTRIBUTING.md: Add section about changelog entries.

- README.md
> fix codecov.io badge URL

- installer/installer.go
> Add log message containing detailed info about installed artifact.

- client/client_update.go
> when deploying new update, mention artifact name and devices in logs

- installer/installer.go
Signed-off-by: greg <greg.distefano+github@gmail.com>
> fix debug message printing artifact details

- mender.go
> Improve error message when manifest field/file cannot be read.

- LIC_FILES_CHKSUM.sha256
- block_device.go
- device.go
- device_test.go
- ioctl.go
- ioctl_32_bit.go
- ioctl_64_bit.go
- partitions.go
- vendor/github.com/ungerik/go-sysfs/LICENSE
- vendor/github.com/ungerik/go-sysfs/README.md
- vendor/github.com/ungerik/go-sysfs/attribute.go
- vendor/github.com/ungerik/go-sysfs/object.go
- vendor/github.com/ungerik/go-sysfs/subsystem.go
- vendor/github.com/ungerik/go-sysfs/sysfs.go
- vendor/vendor.json
> Ubi support v2

- config.go
- mender.go
- statescript/executor.go
Force termination of state scripts that are hanging.
> MEN-1188 Force terminating hanging scripts.

- device.go
- device_test.go
> MEN-505: Fix - Now throws an error when committing nothing.

- installer/installer.go
- main.go
- mender.go
- mender_test.go
- state.go
- state_test.go
> MEN-1215: Changed the errormessage to more closely reflect the issue.

- auth.go
- auth_test.go
- client/client_inventory.go
- daemon.go
- daemon_test.go
- main.go
- main_test.go
- mender.go
- mender_test.go
- state.go
- state_test.go
- store/dbstore.go
- store/dbstore_test.go
- store/dirstore.go
- store/dirstore_test.go
- store/keystore.go
- store/keystore_test.go
- store/mem_store.go
- store/mem_store_test.go
- store/mockstore.go
- store/store.go
> Refactored all store implementations into /store

- statescript/executor.go
- statescript/statescript_test.go
Will not log from Idle and sync states
> MEN-1349: Mender now logs whatever a state-script outputs to stderr

- statescript/executor.go
- statescript/statescript_test.go
Rely on the full error description instead of just the error code.
> Improve error messages for state scripts errors.

- ioctl_64_bit.go
> Fix compile for ARM64.

- installer/installer_test.go
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/checksum.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/metadata.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/raw.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/scripter.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/signer.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/tar_writer_file.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/tar_writer_stream.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/writer.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/common.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/generic.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/rootfs_image.go
- vendor/vendor.json
> Update mender-artifact vendored dependency.

- state.go
In some states deployment logger was not switched on and off
correctly. This one makes sure we are logging only the data
while the device update is in progress.
> Make sure to switch the deployment logs on and off.

- device.go
- device_test.go
- main.go
Also demote the print to warning.
Signed-off-by: Mirza Krak <mirza.krak@endian.se>
> set return code = 2, when there is nothing to commit

- state.go
- state_test.go
Now the client, if losing power, will fall back to the original partition,
and run the Artifact-failure scripts, before going back to idle
> MEN-1187: Spontanaeous-reboot hardening of the client

- device.go
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
> Allow multiple digit partition numbers. 

- client/client.go
- config.go
- device.go
- state.go
- state_test.go
- vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh
- vendor/vendor.json
> Update mendertesting dependency and affected copyright years.

- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
- vendor/vendor.json
I feel like this is a useful addition. Any complaints?
> Add testify require as a dependency in the vendor-list and directory 

- main.go
- main_test.go
> MEN-1806: print artifact name from the cli 

- client/client.go
- client/client_auth.go
- client/client_inventory.go
- client/client_log.go
- client/client_status.go
- client/client_status_test.go
- client/client_test.go
- client/client_update.go
- mender.go
- mender_test.go
> MEN-1738: log request-id in case of bad API requests

- support/keygen-client
especially useful for preauthorizing devices.
Is this an appropriate location for this script? Note that it is not that valuable without https://tracker.mender.io/browse/MEN-1902
> Initial script for generating Mender client keys,

- device.go
- main.go
> MEN-1880: log active partition before and after reboot.

- main.go
- main_test.go
> FIX: Remove extra sigusr1 signal from updateCheck test.

- main_test.go
- mender.go
- state.go
- state_test.go
- transition.go
- transition_test.go
> FIX: Remove reboot hardening for install-leave and reboot-enter

- support/mender-inventory-bootloader-integration
- support/mender-inventory-os
- support/mender-inventory-rootfs-type
Based on #303. Only the "os" attribute is new.
>  MEN-2060: New inventory script for "os" attribute, installed by default.

- client/client.go
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
> client: minor spelling updates

- CONTRIBUTING.md
Should consider backport to stable branches if looks ok.
> Note helpwanted label in issue tracker

- README.md
More appropriate to put in docs?
> README: add section on cross-compiling Mender client

- main.go
> MEN-2159: Fix update check not working under BusyBox.

- main.go
> MEN-2158: Return nonzero exit code after help screen.

- CONTRIBUTING.md
- README.md
- code-of-conduct.md
> Add Community Code of Conduct

- .travis.yml
- bootenv.go
- bootenv_test.go
Updated `.travis.yml` go version to 1.9.
> MEN-2083: Improove error message when running mender as non-root user  

- config.go
- daemon.go
- device.go
> Fix various printf formatting mistakes found by Yocto builder.

- device.go
- partitions.go
Signed-off-by: Michael Davis <michael.davis@essvote.com>
> Allow rootfsPartA and rootfsPartB to be symlinks

- device.go
- partitions.go
Signed-off-by: Michael Davis <michael.davis@essvote.com>
(cherry picked from commit 51becbe54b1bb82d8002c36caa6d25b824d89e2f)
> [1.7.x] Allow rootfsPartA and rootfsPartB to be symlinks

- Makefile
- client/client_auth.go
- client/client_status.go
- client/client_update.go
- partitions.go
> Fix more printf mistakes found by Yocto builder.

- main.go
> removed boolean comparison to true in handling of cli options (main.go)

- LIC_FILES_CHKSUM.sha256
- installer/installer_test.go
- mender_test.go
- vendor/github.com/mendersoftware/mender-artifact/LICENSE
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/compressor.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/compressor_gzip.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/compressor_none.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/signer.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/writer.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/common.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/rootfs_image.go
- vendor/vendor.json
> Vendor-update: Updated the vendoring of mender-artifact.

- Makefile
> Fix go test call in Makefile's coverage target

- CONTRIBUTING.md
saw some issues in a recent contribution, didn't have a place to point the person to - so adding it now.
> CONTRIBUTING: add guidelines on PR structuring

- README.md
> Update README link to point to Mender Hub

- README.md
Quick review requested. :)
If ok I will update all repos.
> Update README.md to Mender Hub, and add bugtracker to avoid use of Github issues

- main.go
- state.go
- state_test.go
> MEN-2195: Bugfix for infinite loop on Sync_enter script error

- statescript/executor.go
- statescript/statescript_test.go
> Define defaultStateScriptTimeout const, to be consistent with the rest

- mender.go
- statescript/executor.go
- statescript/statescript_test.go
Launching the code PR already to get the code merged in time for the beta release. I will do the documentation part later on.
Please @oleorhagen have a look, as you are the original author of this code.
> MEN-2409: Fix state scripts configuration names

- device.go
- partitions.go
- partitions_test.go
> MEN-2302: Only resolve symlinks in /dev/disk/by-partuuid.

- .travis.yml
- Makefile
- main_test.go
> Updated the travis go version from 1.9.7 to 1.11.4.

- README.md
Now that the 2.0 documentation is available online
> Restore Update Modules spec link in README

- support/mender-inventory-bootloader-integration
> Make sure ARM64 is included in bootloader integration inventory.

- standalone.go
> standalone: Fix artifact committing not working after upgrading from 1.x.

- README.md
> Added author information to README

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
> module-artifact-gen: Fix inability to specify more than one device_type.

- support/modules-artifact-gen/single-file-artifact-gen
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> Add macos support for single-file-artifact-gen

- standalone.go
The exact error is picked up in main.go.
> Restore error code 2 behavior when there is nothing to commit.

- support/mender-inventory-os
> Fix `/bin/lsb_release` not being picked up by inventory script.

- support/modules-artifact-gen/single-file-artifact-gen
> Clean permissions file after Artifact creation in single-file generator

- tests/rootfs-image-v2
> Add module support for the 'PerformsFullUpdate' API

- Documentation/update-modules-v3-file-api.md
> Doc updates

- client/client_auth.go
- client/client_update.go
- client/client_update_test.go
- datastore/statedata.go
- deployment_logger.go
- installer/bootenv.go
- installer/dual_rootfs_device.go
- installer/installer.go
- mender_test.go
- state.go
This PR fixes misspells in error messages and comments across all code base.
> Fix misspells in comments and error messages

- client/client_inventory.go
- client/client_status.go
- deployment_logger.go
- installer/modules.go
- mender.go
All possible errors must be checked across all code base.
If an error is intentionally ignored it should be done explicitly.
> Make all errors checked or explicitly ignored

- support/modules-artifact-gen/single-file-artifact-gen
> Bad option passed to stat in single-file-artifact-gen fixed

- daemon.go
> Change the debug log message to an error when not able to force SM

- state.go
- state_test.go
> MEN-2676: Set hard limit(10) for client update status report retries

- daemon.go
- standalone.go
- state.go
- state_test.go
- support/modules-artifact-gen/single-file-artifact-gen
- support/modules/single-file
All changes are bug fixes, so we can do a master-to-release merge.
> Merge master into 2.1.x

- cli.go
- config.go
> FIX: failing testpipeline due to omitempty json tags

- system/ioctl.go
The code in `getUbiDeviceSize` looks at the `data_bytes` property of the UBI device/volume instead of looking at the total size of the volume. This causes the size of a UBI device to always get undereported and in some cases, such as a failed update, could cause devices to no longer be able to get updated.
To demonstrate this, note that `Data bytes` is 2MB (after a 2MB file is written to the volume) despite the total usable size being 50MB. 
root@unknown:~# dd if=/dev/urandom of=/tmp/blah bs=1M count=2
2+0 records in
2+0 records out
root@unknown:~# ubiupdatevol /dev/ubi0_0 /tmp/blah
root@unknown:~# ubinfo /dev/ubi0_0
Volume ID:   0 (on ubi0)
Type:        static
Alignment:   1
Size:        802 LEBs (52457216 bytes, 50.0 MiB)
Data bytes:  2097152 bytes (2.0 MiB)
State:       OK
Name: …
> Fixes UBI device size calculation

- .gitlab-ci.yml
- Makefile
- README.md
- cli/cli.go
- cli/setup.go
- cli/setup_test.go
- examples/mender.conf.demo
- examples/mender.conf.production
- installer/dual_rootfs_device_test.go
- installer/installer_test.go
- tests/Dockerfile.daemon
Supersedes #442 
It will be merged together with [mender-dist-packages' feature branch MEN-2315-interactive-mender-config](https://github.com/mendersoftware/mender-dist-packages/tree/MEN-2315-interactive-mender-config).
Please see individual commits.
> MEN-2315: Interactive mender configuration

- cli/cli.go
- cli/cli_test.go
- cli/setup.go
> Handle implicit flag dependencies in `mender setup` command

- .gitlab-ci.yml
- Makefile
- README.md
- cli/cli.go
- cli/cli_test.go
- cli/setup.go
- cli/setup_test.go
- examples/mender.conf.demo
- examples/mender.conf.production
- installer/dual_rootfs_device_test.go
- installer/installer_test.go
- tests/Dockerfile.daemon
Merging in feature branch. All code has already been reviewed and verified.
> MEN-2315: Interactive mender config

- .gitlab-ci.yml
Brings to 2.1.x Pipeline triggers for:
- build/publish Docker mender-client-qemu image for branch
- build/publish Debian deb package for tags
> Add pipeline triggers 2.1.x

- cli/setup.go
> Set default device type to hostname for interactive setup

- app/standalone.go
- app/standalone_test.go
Previously the standalone mode would lose the provide data from the Artifact, as
the data was not stored, for when the device was rebooted.
Changelog: Now the client stores Artifact provides parameters across reboots in
standalone mode. Previously this data was ignored, and hence upgrading with an
Artifact with provides parameters these were lost.
> MEN-2969: Fix: Store provide data across reboots in standalone mode

- LICENSE
- LIC_FILES_CHKSUM.sha256
> Happy New Year 2020!

- .gitlab-ci.yml
- Makefile
- cli/cli.go
- cli/cli_test.go
- cli/setup.go
> Update the Gitlab-runner go version to 1.13

- README.md
> README.md: Corrected a typo (intance -> instance)

- README.md
> Instruct the user to clone the repo inside GOPATH before running make

- cli/setup.go
> [spelling] Fix

- support/modules-artifact-gen/single-file-artifact-gen
> MEN-3049: Make `single-file-artifact-gen` script POSIX compliant.

- cli/setup.go
> Make device type example match an actual real life example.

- cli/cli_test.go
- cli/commands.go
- main_test.go
One cherry-pick from #506 (tested there) and one unit test minor beautification.
> Minor fixes: error for PID 0 and test beatification

- app/auth.go
- app/daemon.go
- app/deployment_logger.go
- app/mender.go
- app/state.go
- cli/cli_test.go
- client/client_auth.go
- client/client_inventory.go
- client/client_log.go
- client/client_status.go
- device/device.go
- installer/block_device.go
- installer/dual_rootfs_device.go
- installer/installer.go
- inventory/inventory_data.go
- statescript/executor.go
- statescript/statescript_test.go
- store/dbstore.go
- store/keystore.go
- system/ioctl.go
- utils/limited_writer.go
Some minor things which annoyed me when using Mender myself.
* Some log messages start with a lowercase, whilst others do not
* Wording in some places, uses words like we
* Minor wording choices
> Fixes various logging nitpicks

- tests/Dockerfile.daemon
- tests/entrypoint.sh
> Add handling of TENANT_TOKEN to docker-client test container.

- .gitlab-ci.yml
> [pipeline] Add pip3 dependency for trigger:mender-qa job - 2.2.x

- support/mender-device-identity
- support/mender-inventory-network
> Misc: correcting misspellings

- Makefile
- support/mender-inventory-geo
> mender-inventory-geo script to return geo localization data.

- support/modules/directory
- support/modules/docker
- support/modules/single-file
Namely: indent for the break in the case statements.
> [support/modules] Unify shell script style in modules

- cli/cli.go
- cli/cli_test.go
> MEN-3676: Fix broken logging to syslogger.

- conf/config.go
> MEN-3762 chmod 600 on config file

- cli/cli.go
- cli/cli_test.go
- conf/config.go
- conf/config_test.go
> MEN-3652: Remove Server config warn on mender setup command

- support/mender-inventory-geo
> mender-inventory-geo: Changing default attribute names.

- support/modules/single-file
> single-file update module: double quotes added in paths vars referals.

- installer/dual_rootfs_device.go
- installer/dual_rootfs_device_test.go
> Improve message when we detect booting from the wrong partition.

- device/device.go
> Close manifest file handler in GetManifestData

- app/auth.go
- app/mender_test.go
- store/keystore.go
1) Remove extraneous function call
2) Remove TODO comment which is now covered (I believe)
> Minor brushups

- go.sum
- store/keystore_test.go
> Linutronix removal from store/keystore_test.go

- app/auth.go
- app/auth_test.go
- app/mender.go
- app/mender_test.go
- cli/cli_test.go
- cli/commands.go
- store/keystore.go
- store/keystore_test.go
> MEN-3114: Client uses certificate private key when mTLS is enabled

- go.mod
- go.sum
- vendor/github.com/mendersoftware/openssl/.gitlab-ci.yml
- vendor/github.com/mendersoftware/openssl/conn.go
- vendor/github.com/mendersoftware/openssl/ctx.go
- vendor/github.com/mendersoftware/openssl/key.go
- vendor/github.com/mendersoftware/openssl/ssl.go
- vendor/modules.txt
> Bump mendersoftware/openssl version to v1.0.6

- app/daemon.go
- cli/commands.go
> Gracefully stop on SIGTERM.

- app/standalone.go
- app/standalone_test.go
- cli/cli.go
- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
This parameter will cause the "mender install" command to return an
exit code of 4 if a manual reboot is required after installation.
Signed-off-by: Pascal Hache <hacpa@touchtunes.com>
Thank you!
> Add --reboot-exit-code parameter to "install" command.

- cli/cli.go
- cli/cli_test.go
- cli/commands.go
> MEN-3074: implement "show-provides" command on client

- .gitlab-ci.yml
- Makefile
- README.md
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- support/mender-client.service
- support/mender-inventory-provides
- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
* MEN-3073: add inventory script to list the artifact provides data
*  MEN-3481: add support for software version flags in artifact generators
> MEN-3073, MEN-3481: software versions

- README.md
- cli/snapshot.go
> MEN-3961 Additional fixes of text around the links to the docs

- client/client.go
> Fixing misspell in log line and hiding the key URI.

- app/state.go
> log: Add a log message explicitly stating authorization success

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
> artifact-gen: Improve error message when mender-artifact is not found.

- client/client_update.go
> fixed typo

- .gitlab-ci.yml
- Makefile
- README.md
- cli/cli_test.go
- installer/dual_rootfs_device.go
- installer/dual_rootfs_device_test.go
> MEN-3980 (2.3.x-cherry)

- .gitlab-ci.yml
- Makefile
- README.md
- cli/cli_test.go
Just to unblock the git push rejected error seen in the pipeline in #635
> 2.3.x fixups 

- Makefile
- app/auth.go
- app/auth_test.go
- app/client_closures.go
- app/daemon.go
- app/daemon_test.go
- app/mender.go
- app/mender_test.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- client/client.go
Not ready for a full review, still missing pieces, but as most of the unit tests pass I believe it would be great to get a first-round of review, at least for the general design.
> MEN-4015: decouple Controller and AuthManager using communication over channels

- README.md
- cli/commands.go
- cli/snapshot.go
- client/client.go
- conf/config.go
(cherry picked from commit d7fd519ebcae22eaf612ee5c3a2d74627dcab1f2)
> MEN-3924 Allow to load private key from the Security configuration section

- support/mender-inventory-geo
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
I have a user I am working with who is reporting significant delays when connecting to ipvigilante.  I cannot replicate that but I did add a timeout here for the wget commands.  I have asked the user to test this version to see if it helps.
> mender-inventory-geo: Set sensible timeout.

- support/mender-inventory-geo
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>
(cherry picked from commit c16ae95dc3a518232c36a72e18486260f8f289e9)
> mender-inventory-geo: Set connection timeout to 10s.

- .gitlab-ci.yml
> CI(gitlab-ci.yml): Install git on the running container

- app/mender_test.go
If a bad certificate is detected, which is what we are testing, the
Golang request processing (http.Client.Do) will close the connection.
Sometimes, but not always, this will lead to a "connection closed"
error instead of a "bad certificate" error, the latter of which we are
looking for in the string. It appears that this is outside of our
control, since our server is not torn down until after the check has
been made.
Work around this by repeating the test multiple times using
assert.Eventually.
> tests: Work around race condition when detecting bad certificate.

- app/auth_test.go
- app/mender_test.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- store/keystore.go
- store/keystore_test.go
Add passphrase-file global option for decrypting encrypted private keys.
> Add passphrase-file global option.

- cli/cli.go
> Fixed typo in mender/cli/cli.go

- LICENSE
- LIC_FILES_CHKSUM.sha256
> Update license copyright year.

- .gitlab-ci.yml
See https://github.com/mendersoftware/mender-qa/pull/474
> [pipeline] Adjust trigger:mender-qa job after changes in the script

- .gitlab-ci.yml
> 2.5.x: [pipeline] Adjust trigger:mender-qa job after changes in the script

- support/modules-artifact-gen/single-file-artifact-gen
> MEN-4179: fix, support white spaces in single-file artifacts' names

- tests/Dockerfile.daemon
* [Dockerfile.daemon] Minor beautifications and optimizations
* [Dockerfile.daemon] Upgrade base image to ubuntu:20.04
> Dockerfile beautification + upgrade

- support/mender-inventory-geo
> Cherry-pick MEN-4085 to 2.5.x

- support/modules/single-file
> single-file: Use atomic file operations.

- README.md
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
> Fix the readme to reflect the client binary name change.

- cli/commands.go
- cli/setup.go
- cli/setup_test.go
Changelog: mender setup: when configuring for demo using self-signed
certificate, install the certificate in the local trust store so that
all components in the system (namely, Mender addons) can trust the
Mender server without extra configuration.
> MEN-4580: Install demo cert in local trust store

- cli/commands.go
- cli/setup.go
- cli/setup_test.go
> 2.6.x:  MEN-4580: Install demo cert in local trust store

- cli/setup.go
> Fix: typo in installDemoCertificateLocalTrust

- conf/config.go
- conf/config_test.go
See: https://tracker.mender.io/browse/MEN-4534 for info
> MEN-4534: Add UpdateControlMapExpirationTimeSeconds to mender.conf

- client/client.go
If skip verify is set , then we shouldnt call `VerifyResult`
> Dont Verify SSL if skip verify is set

- Documentation/io.mender.Authentication1.xml
- Documentation/io.mender.Update1.xml
- Makefile
- README.md
- cli/cli.go
- cli/commands.go
- cli/setup.go
- cli/setup_test.go
- client/client.go
Also merge with master. Only the last commit is new.
> DBus docs: Elaborate a bit more and document on_action_executed. 

- .gitlab-ci.yml
- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
- support/modules-artifact-gen/tests/conftest.py
- support/modules-artifact-gen/tests/requirements.txt
- support/modules-artifact-gen/tests/test_modules_artifact_gen.py
- support/modules/single-file
> 2.6.x: MEN-4671: Add (unit) tests for single-file-artifact-gen + Fix issues in module and generator

- .gitlab-ci.yml
- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
- support/modules-artifact-gen/tests/conftest.py
- support/modules-artifact-gen/tests/requirements.txt
- support/modules-artifact-gen/tests/test_modules_artifact_gen.py
- support/modules/single-file
> 2.5.x: MEN-4671: Add (unit) tests for single-file-artifact-gen + Fix issues in module and generator

- README.md
Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>
Add libssl cross compilation steps to README
> Add libssl cross compilation steps to README

- app/updatemanager.go
- app/updatemanager_test.go
This is based on top of 4547, which may be due to change according to review, but the implementation itself should be pretty freestanding.
> MEN-4548: Implement the Query update logic

- cli/cli_test.go
- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
> [cherry 2.6.x] MEN-4074

- app/mender.go
- app/state.go
- app/state_test.go
- app/transition_test.go
- app/updatemanager.go
- app/updatemanager_test.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- conf/config.go
- conf/config_test.go
- datastore/dbkeys.go
Based on #755. The main commit is the title, the rest are support commits, best reviewed individually.
> MEN-4619: Add saving of Update Control Maps to local database.

- cli/cli_test.go
- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
>  [cherry 2.4.x] MEN-4074

- dbus/dbus_libgio.go.h
> 2.6.x: MEN-4703: Fix D-Bus timeout on errors by finishing handling

- dbus/dbus_libgio.go.h
> 2.5.x: MEN-4703: Fix D-Bus timeout on errors by finishing handling

- cli/cli_test.go
- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
>  [cherry 2.5.x] MEN-4074

- app/mender.go
- app/mender_test.go
Simply upload the substatus pause when the client is paused by an update control map
> MEN-4624: Report to deployments/status when pausing in any state

- app/mender.go
- app/mender_test.go
- app/updatemanager.go
- app/updatemanager_test.go
Various small fixes for issues discovered while making acceptance tests.
> Fixes for Feature dbus update control

- Makefile
- README.md
- app/daemon.go
- app/daemon_test.go
- app/mender.go
- app/mender_test.go
- app/updatemanager.go
- app/updatemanager_test.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- cli/setup.go
- conf/config.go
- conf/paths.go
- dbus/dbus_libgio.go.h
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
- tests/Dockerfile.daemon
Merge `feature-dbus_update_control` into `feature-update_control_maps` and then fix a few problems arising from that. Only the commits after the last merge commit need to be reviewed.
> Update and fix feature-update_control_maps branch.

- .gitlab-ci.yml
> MEN-4107: trigger rebuild of the docs site on changes

- app/updatemanager.go
> Fix channels not being assigned correctly when loading from storage.

- Documentation/io.mender.Update1.xml
> Fix: use ampersand characters in D-Bus documentation

- app/state.go
- app/updatemanager_test.go
And add simple unit test for updatemanager.Delete
> MEN-4562: Remove matching update_control_maps for finished deployments

- app/daemon.go
- app/mender.go
- cli/setup.go
- cli/setup_test.go
- client/client.go
- conf/config.go
- conf/config_test.go
- support/mender-inventory-network
> 3.0.x: porting MEN-4851 and MEN-4857

- .gitlab-ci.yml
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
Thank you!
> corrected trigger rule to allow proper matching on branches

- support/modules/docker
Was doing a demo with the docker module so I ended up extending the
logging to understand what's going on and show meaningful messages on a
failure.
Need to retest it again, it's been a while.
Leaving in Draft until I find some time.
> Extend logs for docker module

- tests/entrypoint.sh
> QA-187: make ServerURL configurable in the Docker client

- tests/entrypoint.sh
> Fix: entrypoint.sh, do not break if server URL contains slashes

- tests/entrypoint.sh
> 3.1.x: QA-187: make ServerURL configurable in the Docker client + fix

- support/mender-inventory-geo
> 3.1.x: [FIX] Fetch geo location data once per power cycle

- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
- system/system.go
This reverts commit 8c672c35290a1dae9021a29264365ddb39a0300f.
> Revert "Make command output less ugly in the log."

- support/mender-inventory-geo
> 3.0.x: [FIX] Fetch geo location data once per power cycle

- support/mender-inventory-geo
> 2.5.x: [FIX] Fetch geo location data once per power cycle

- .gitlab-ci.yml
> CI: Create a Junit test report for Gitlab

- cli/cli.go
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> Fixed typo in CLI help message

- app/daemon_test.go
- app/state.go
- app/state_test.go
> MEN-4882: Query the NeedsArtifactReboot parameter in rollback

- app/state.go
- app/state_test.go
> A couple of fixes for update control map wait logic.

- LICENSE
- LIC_FILES_CHKSUM.sha256
- installer/bootenv.go
> Fix: linting error

- statescript/executor.go
> [Cherry 2.5.x]: Make sure `/etc/mender/scripts/version` is closed after use.

- app/mender_test.go
> style: go fmt on tests

- .gitlab-ci.yml
To align the yml code to the rest of the repositories.
> pipeline: Rewrite mender-qa trigger

- .gitlab-ci.yml
* adding the GOLANG_VERSION variable, read by apckage builders
ChangeLog:none
> MEN-5459 Install go based on the source repository preferences.

- device/device.go
> log: add missing space when joining lines

- .gitlab-ci.yml
> Fixing the go lang version set for package build.

- support/mender-inventory-bootloader-integration
> inventory-bootloader-integration: Detect new environment location.

- support/mender-inventory-bootloader-integration
(cherry picked from commit 3fe18ae0172fca589421791eb7abed9a0678e012)
> 3.0.x: inventory-bootloader-integration: Detect new environment location.

- support/mender-inventory-bootloader-integration
(cherry picked from commit 3fe18ae0172fca589421791eb7abed9a0678e012)
> 3.2.x: inventory-bootloader-integration: Detect new environment location.

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> QA-365: Update the contributor pull request template

- app/proxy/proxy.go
> fix: the HTTP proxy must bind on localhost, not on all the interfaces

- app/process_leaking_test.go
- app/proxy/process_leaking_test.go
- app/updatecontrolmap/process_leaking_test.go
- cli/process_leaking_test.go
- client/process_leaking_test.go
- conf/process_leaking_test.go
- datastore/process_leaking_test.go
- dbus/process_leaking_test.go
- device/identity_data.go
- device/process_leaking_test.go
- installer/bootenv.go
- installer/process_leaking_test.go
- inventory/inventory_data.go
- inventory/inventory_data_test.go
- inventory/process_leaking_test.go
- process_leaking_test.go
- statescript/process_leaking_test.go
- store/process_leaking_test.go
- system/testing/os_calls.go
- system/testing/process_testing.go
- utils/process_leaking_test.go
> Fix: Don't accumulate zombies when identity/inventory parsing fails.

- tests/rootfs-image-v2
> A few changes from playing with rootfs v2.

- installer/modules_test_helper.sh
- system/testing/os_calls_helper.sh
- tests/entrypoint.sh
chore(license): Add OS license to shell scripts
Ticket: None
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(license): Add OS license to shell scripts

- .gitlab-ci.yml
> feat: build using golang version 1.17.13

- client/client.go
> chore: Omit request_id to logs if the header is absent in response

- app/daemon_test.go
> test: fix the race-condition in the DaemonRun unit test 

- Makefile
- app/daemon.go
- app/state.go
> Cherry men 5547 3.0.x

- CONTRIBUTING.md
> fix: Fix broken link to commit specification

- Documentation/automatic-bootstrap-artifact.md
> chore: Document automatic bootstrap Artifact

- dbus/dbus_libgio.go
golangci-lint is not happy
(cherry picked from commit 1548619066edaa6c5511e00511cd7efeea42d403)
> style(lint): break the long line

- support/keygen-client
Ticket: None
Signed-off-by: Alan <alan.martinovic@northern.tech>
(cherry picked from commit 355069236dfca0529a5c008414c5ef3e6ea7dafc)
> fix: Expand the check for new openssl version

- installer/bootenv.go
- support/mender-client.service
Economize CI usage a little bit by testing some easy PRs together.
> Multiple PRs

- CONTRIBUTING.md
- README.md
Ticket: MEN-6033
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
> docs: document contributions during c++ rewrite

- app/mender_test.go
- app/proxy/proxy.go
- app/proxy/proxy_ws.go
- app/proxy/proxy_ws_test.go
- client/client.go
- client/test/http_proxy.go
- go.mod
- go.sum
- vendor/github.com/mendersoftware/openssl/net.go
- vendor/modules.txt
> 3.4.x: Port ME-3, ME-5 and MEN-6009

- .gitlab-ci.yml
- dbus/dbus_libgio.go.h
- dbus/error.go.h
Cherry pick of PR: https://github.com/mendersoftware/mender/pull/1094
For me
> [Cherry 3.3.x]: chore: Fix license check after template update

- CONTRIBUTING.md
> chore: Update contribution guide with C++ programming style.

- autogen.sh
- common/json/json.hpp
- mender-auth/main.cpp
- mender-update/main.cpp
> chore: Add the missing license headers

- .gitlab-ci.yml
- Makefile.am
- configure.ac
- tests/Dockerfile.daemon
Simply setup the unit test target in CI to a working condition again.
> (mender-cpp-client): Fix the CI pipelines

- common/log.hpp
- common/log/platform/boost/boost_log.cpp
- common/log_test.cpp
- mender-update/main.cpp
> fix: Call setup when creating the global logger

- CMakeLists.txt
- common/io.hpp
- common/key_value_database_test.cpp
- common/log.hpp
Also fixed the build errors which popped up as a result.
> Add the -Wall flag during builds

- common/io.cpp
- common/io.hpp
> feat(io): Add a byte-writer

- common/common.cpp
- common/common.hpp
- common/expected.hpp
> fix: Fix return for StringToLongLong function.

- mender-update/CMakeLists.txt
- mender-update/update_module/v3/update_module.cpp
- mender-update/update_module/v3/update_module.hpp
Only as a skeleton for now, just to set up the basic structure and placement of the code.
Ticket: MEN-6312
> feat: Introduce the UpdateModule class

- common/io.cpp
> fix(io): Missing unexpected wrapper around error call

- artifact/sha/sha.hpp
- artifact/tar/platform/libarchive/wrapper.hpp
- artifact/tar/tar.hpp
- common/json.hpp
- common/key_value_database.hpp
Most notably always make sure config.h is included first
> Misc style-guide fixes

- artifact/v3/manifest/manifest.cpp
- artifact/v3/version/version.cpp
- common/CMakeLists.txt
- common/io.cpp
- common/io.hpp
- common/json.hpp
- common/json/platform/nlohmann/nlohmann_json.cpp
- common/json_test.cpp
Instead of reading things in memory before processing them.
> Use streams in I/O

- mender-update/update_module/v3/update_module.cpp
- mender-update/update_module/v3/update_module.hpp
This wasn't in the original acceptance criteria, but I think it makes sense.
> Some renamings

- CMakeLists.txt
- common/CMakeLists.txt
- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/io.cpp
- common/io.hpp
I know that some parts of the body handling aren't working quite right yet, but the main pieces should be there, and I don't want to spend too much time testing it because there is a separate testing task.
> feat: Add HTTP server functionality.

- artifact/sha/platform/openssl/sha.cpp
- artifact/sha/sha_test.cpp
- artifact/tar/platform/libarchive/wrapper.cpp
- artifact/tar/tar_test.cpp
- artifact/v3/payload/payload_test.cpp
- common/common.cpp
- common/conf/conf.cpp
- common/context/context.cpp
- common/error.cpp
- common/error.hpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/identity_parser/identity_parser.cpp
- common/inventory_parser/platform/boost_filesystem/inventory_parser.cpp
- common/io_test.cpp
- common/key_value_database/in_memory/in_memory.cpp
- common/key_value_database/platform/lmdb/lmdb.cpp
- common/key_value_database_test.cpp
- common/key_value_parser/key_value_parser.cpp
- common/key_value_parser_test.cpp
- common/log_test.cpp
- common/processes/platform/tiny_process_library/tiny_process_library.cpp
- mender-auth/main.cpp
- mender-update/main.cpp
> chore: expected<Something, Error> should never allow construction from Error without unexpected()

- support/mender-inventory-geo
> feat: inventory script: parse and support location data.

- .gitlab-ci.yml
> chore: coveralls publish fix.

- common/conf.hpp
- common/conf/conf.cpp
- common/conf_test.cpp
- mender-auth/main.cpp
- mender-update/CMakeLists.txt
- mender-update/cli/actions.cpp
- mender-update/cli/actions.hpp
- mender-update/cli/cli.cpp
- mender-update/cli/cli.hpp
- mender-update/cli/cli_test.cpp
- mender-update/main.cpp
Note, this is based on #1240. No need to re-review those commits here.
> show-artifact and show-provides commands, with support commits

- common/json.hpp
- common/json/platform/nlohmann/nlohmann_json.cpp
Note - the template still needs to be specialized for each invocation of the algorithm used.
Ticket: None
> feat(json): Add a templated Dump function to dump STL structures to JSON

- artifact/sha/platform/openssl/sha.cpp
- artifact/sha/sha.hpp
- artifact/sha/sha_test.cpp
I am also considering moving it to `common` now?
What do you think?
> Minor fixes, and changes to the sha implementation

- .gitlab-ci.yml
Just speed things up a little.
> ci: Add the jobs flag to set the make parallel factor to n-ncpus

- artifact/artifact.cpp
- artifact/artifact.hpp
- common/CMakeLists.txt
- common/error.cpp
- common/error.hpp
- common/error/platform/c++11/error.cpp
- common/events/events_io.cpp
- common/events_io.hpp
- common/json.hpp
- common/json/json.cpp
- common/json_test.cpp
- common/testing.hpp
- mender-update/cli/cli_test.cpp
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/update_module/v3/platform/boost_filesystem/fs_operations.cpp
- mender-update/update_module/v3/platform/boost_filesystem/update_module_call.cpp
- mender-update/update_module/v3/update_module.cpp
- mender-update/update_module/v3/update_module.hpp
- mender-update/update_module/v3/update_module_download.cpp
- mender-update/update_module/v3/update_module_test.cpp
On @oleorhagen's request, singled out all the support commits from #1252 to here.
> Standalone mode support commits

- common/CMakeLists.txt
- common/events/events_io.cpp
- common/events/platform/boost/events.cpp
- common/events_io.hpp
- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/io.cpp
- common/io.hpp
- common/testing.cpp
- common/testing.hpp
- mender-update/CMakeLists.txt
- mender-update/cli/cli_test.cpp
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/standalone/standalone.cpp
> feat(standalone): Add support for installing from HTTP + support commits

- mender-update/deployments.cpp
- mender-update/deployments.hpp
- mender-update/deployments_test.cpp
The first commit is cherry-picked from #1289, whichever gets merged first will pull it in.
> Deployment status API

- common/state_machine.hpp
Not adding any tests now, I still need to decide what should be tested directly, and indirectly as part of usage.
Note that this is not going to the main development branch yet. I still want to validate a bit more by implementing the real work in each state.
> chore: Add state machine framework.

- common/events.hpp
- common/events/events_io.cpp
- common/events/platform/boost/events.cpp
- common/events_io.hpp
- common/state_machine.hpp
- mender-update/standalone/standalone.cpp
- mender-update/update_module/v3/platform/c++17/update_module_call.cpp
- mender-update/update_module/v3/update_module.cpp
- mender-update/update_module/v3/update_module.hpp
- mender-update/update_module/v3/update_module_download.cpp
- mender-update/update_module/v3/update_module_test.cpp
More support commits for daemon mode and state machine.
> Daemon mode and state machine support commits

- mender-update/CMakeLists.txt
- mender-update/cli/actions.cpp
- mender-update/cli/actions.hpp
- mender-update/cli/cli.cpp
- mender-update/daemon.hpp
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
- mender-update/daemon/state_events.hpp
- mender-update/daemon/state_machine.cpp
- mender-update/daemon/state_machine.hpp
- mender-update/daemon/states.cpp
- mender-update/daemon/states.hpp
Ticket: MEN-6575
Ticket: MEN-6500
This builds on the work in https://github.com/mendersoftware/mender/pull/1302.
> Implement state machine and daemon mode support

- go.mod
- go.sum
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/compressor_gzip.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/signer.go
- vendor/modules.txt
> chore: mender-artifact set to 3.10.x in go.mod

- artifact/config.hpp
- artifact/v3/header/header.cpp
- artifact/v3/header/header_test.cpp
- mender-update/daemon/states.cpp
- mender-update/standalone/standalone.cpp
Both in standalone and daemon mode.
> Add full support for storing Artifact scripts

- api/auth.hpp
- api/client.hpp
- common/conf/paths.hpp
- common/conf/platform/posix/paths.cpp
- mender-update/CMakeLists.txt
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
> chore: Switch to use authenticated server requests.

- mender-update/daemon/state_test.cpp
It's a lot easier to view this with whitespace turned off.
> test: Fix race condition due to exit handlers.

- common/state_machine.hpp
- mender-update/daemon/state_events.hpp
> feat(state-machine): Support printing the state event names

- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
> feat: Check artifact's depends before installing it

- .gitignore
- CMakeLists.txt
- artifact/v3/header/header_test.cpp
- common/conf.hpp
- common/conf/conf.cpp
- common/error.cpp
- common/error.hpp
- common/state_machine.hpp
- common/testing.cpp
- common/testing.hpp
- mender-auth/main.cpp
- mender-update/cli/actions.cpp
- mender-update/cli/cli.cpp
- mender-update/cli/cli_test.cpp
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
- mender-update/daemon/state_machine/state_machine.cpp
- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
- mender-update/update_module/v3/platform/c++17/fs_operations.cpp
- mender-update/update_module/v3/update_module_test.cpp
- mender-version.h.in
Plus some supporting commits and fixes.
> MEN-6580: Implement deployment logging in deployments

- Documentation/update-modules-v3-file-api.md
Needed for Flash based updates. This will be implemented in MEN-6273.
Ticket: MEN-6272
> docs: Document "file size" extension to Update Module protocol.

- mender-update/daemon/context.cpp
- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
- mender-update/deployments.hpp
- mender-update/deployments/platform/boost_log/deployments.cpp
> chore: Implement pushing of logs to the server.

- common/common.hpp
- common/conf.hpp
- mender-update/CMakeLists.txt
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
- mender-update/daemon/state_machine/state_machine.cpp
- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
- mender-update/daemon/states.hpp
- mender-update/inventory.cpp
- mender-update/inventory.hpp
- mender-update/inventory_test.cpp
> Actually push inventory from mender-update

- artifact/v3/scripts/executor.cpp
- artifact/v3/scripts/executor.hpp
- artifact/v3/scripts/executor_test.cpp
- common/path.hpp
- common/path/platform/c++17/path.cpp
- mender-update/daemon/state_test.cpp
Also change the interface to the script runner a little.
Along with some minor fixes to the existing code.
> Add a synchronous script runner

- artifact/v3/scripts/executor.cpp
- artifact/v3/scripts/executor.hpp
- common/conf.hpp
- mender-update/CMakeLists.txt
- mender-update/cli/cli_test.cpp
- mender-update/standalone.hpp
- mender-update/standalone/standalone.cpp
This adds the ability to run State Scripts in standalone mode.
Ticket: MEN-6638
> Run State Scripts in Standalone mode

- .gitlab-ci.yml
- client/client.go
> feat: build and test using the latest version of golang (1.21 today)

- artifact/v3/scripts/executor.cpp
- mender-update/daemon/state_events.hpp
Fixes error reaches end of control, error.
> chore: Add return string to function

- CMakeLists.txt
- Documentation/CMakeLists.txt
> build: Install the DBus interface files

- common/conf.hpp
- mender-update/deployments/deployments.cpp
- mender-update/deployments/platform/boost_log/deployments.cpp
- mender-update/update_module/v3/update_module_download.cpp
- support/mender-inventory-provides
- support/modules/rootfs-image
All miscellaneous changes, and nitpicks, and fixes.
> Integration test runs - client fixes

- common/dbus.hpp
- common/dbus/platform/asio_libdbus/dbus_client.cpp
- common/dbus_test.cpp
> DBusClient followup

- common/dbus.hpp
- common/dbus/platform/asio_libdbus/dbus_client.cpp
- common/dbus_test.cpp
> Templated DBusClient methods

- common/crypto/platform/openssl/crypto.cpp
- mender-auth/cli/keystore.hpp
Fixed a few linter issues I came across.
> Misc linter fixes

- README.md
Ticket: None
Signed-off-by: Craig Comstock <craig.comstock@northern.tech>
```
```
Thank you!
> fix: Added libdbus-1-dev dependency for building

- common/events.hpp
- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/http_test_helpers.hpp
- common/log.hpp
- common/log/platform/boost/boost_log.cpp
- mender-auth/CMakeLists.txt
- mender-auth/http_forwarder.hpp
- mender-auth/http_forwarder/CMakeLists.txt
- mender-auth/http_forwarder/http_forwarder.cpp
- mender-auth/http_forwarder/http_forwarder_test.cpp
> Add HTTP forwarder.

- Documentation/automatic-bootstrap-artifact.md
- README.md
- api/auth/auth.cpp
- artifact/config.hpp
- artifact/v3/manifest_sig/manifest_sig.cpp
- artifact/v3/manifest_sig/manifest_sig.hpp
- common/config_parser/config_parser.cpp
- common/path.hpp
- common/path/platform/c++17/path.cpp
- mender-update/cli/actions.cpp
- mender-update/cli/actions.hpp
- mender-update/cli/cli_test.cpp
- mender-update/standalone.hpp
- mender-update/standalone/standalone.cpp
- mender-update/update_module/v3/platform/c++17/update_module_call.cpp
Just  a collection of fixes from running the client with integration tests.
> Misc fixes 4 integration tests

- mender-update/CMakeLists.txt
- mender-update/progress_reader/CMakeLists.txt
- mender-update/progress_reader/progress_reader.cpp
- mender-update/progress_reader/progress_reader.hpp
- mender-update/progress_reader/progress_reader_test.cpp
- mender-update/update_module/v3/update_module_download.cpp
> feat(progressbar): Add the progressbar code to standalone mode

- mender-update/cli/actions.cpp
- mender-update/cli/actions.hpp
- mender-update/cli/cli.cpp
> feat: Add the show-inventory and check-update commands

- common/dbus/platform/asio_libdbus/dbus.cpp
- common/dbus_test.cpp
A big important one and a minor one.
> DBus fixes

- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/io.hpp
- common/io/io.cpp
- mender-auth/http_forwarder.hpp
- mender-auth/http_forwarder/http_forwarder.cpp
- mender-auth/http_forwarder/http_forwarder_test.cpp
Ticket: MEN-6665
Plus many support commits.
> feat: Implement generic TCP forwarding upon 101 Switching Protocols.

- app/auth.go
- app/auth_test.go
- app/client_closures.go
- app/mender_test.go
- app/proxy/proxy_ws_test.go
- app/standalone.go
- app/standalone_test.go
- app/state_test.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- cli/setup.go
- client/client.go
- client/client_auth_test.go
- client/client_inventory_test.go
- client/client_log_test.go
- client/client_status_test.go
- client/client_test.go
- client/client_update_test.go
- conf/config.go
- conf/config_test.go
- statescript/statescript_test.go
> Refactor the configuration into one package

- mender-auth/cli/actions.cpp
With no servers, mender-auth just doesn't know which servers to try to authenticate with.
Ticket: none
> chore: Exit mender-auth with an early error if no servers specified

- common/http_test.cpp
Once in a while, in release mode only, this test will display this symptom:
```
...
record_id=163 severity=trace time="2023-Oct-03 16:22:53.911616" name="http_client" url="http://127.0.0.1:8001" msg="Read 16384 bytes of body data from stream."
record_id=164 severity=trace time="2023-Oct-03 16:22:53.911802" name="http_client" url="http://127.0.0.1:8001" msg="Read 16384 bytes of body data from stream."
record_id=165 severity=warning time="2023-Oct-03 16:22:53.912043" name="http_client" url="http://127.0.0.1:8001" msg="Client destroyed while request is still active!"
[       OK ] HttpTest.TestResponseBody (202 ms)
[----------] 1 test from HttpTest (202 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (202 ms total)
[  PASSED  ] 1 test. …
```
> test: Work around malloc corruption bug during OpenSSL cleanup.

- api/auth_test.cpp
- api/client_test.cpp
- common/http.hpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- mender-auth/ipc/server.hpp
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
> chore: Implement SkipVerify config option.

- common/http_test.cpp
> test: Add test for verifying hostname when doing TLS handshake.

- common/http_test.cpp
> test: Add test for missing certificate.

- api/CMakeLists.txt
- api/auth.hpp
- api/auth/auth.cpp
- api/auth_test.cpp
- mender-auth/cli/actions.cpp
- mender-auth/cli/cli_test.cpp
- mender-auth/ipc/server.cpp
- mender-auth/ipc/server.hpp
- mender-auth/ipc/server_test.cpp
> fix(auth): Attempt to authenticate to all servers from config

- common/CMakeLists.txt
- common/conf/conf.cpp
- common/config_parser.hpp
- common/config_parser/config_parser.cpp
- common/config_parser_test.cpp
- mender-auth/cli/actions.cpp
Use only the list, instead of the list and the single entry.
Ticket: MEN-6662
> chore: Consolidate struct members for server URL.

- src/mender-update/http_resumer.hpp
- src/mender-update/http_resumer/http_resumer.cpp
- src/mender-update/http_resumer/http_resumer_test.cpp
> Several fixes to make sure second updates work

- src/api/auth.hpp
- src/api/auth/auth.cpp
- src/api/auth_test.cpp
- src/common/CMakeLists.txt
- src/common/crypto.hpp
- src/common/crypto/platform/openssl/crypto.cpp
- src/common/crypto_test.cpp
- src/common/http.hpp
- src/common/http/http.cpp
- src/common/http/platform/beast/http.cpp
- src/mender-auth/cli/actions.cpp
- src/mender-auth/cli/keystore.cpp
- src/mender-auth/cli/keystore.hpp
- src/mender-auth/ipc/server.cpp
- src/mender-auth/ipc/server.hpp
- src/mender-auth/ipc/server_test.cpp
Implementation of the HSM support for the cpp client
> Hardware crypto support

- src/common/identity_parser_test.cpp
This adds a test to verify that identity is marshaled in the same way as it is
in the Golang client code.
See the test here:
`https://github.com/mendersoftware/mender/blob/mendersoftware/device/identity_data_test.go#L130`
Note that we still might have a UTF-8 issue here. But this is a separate topic.
Ticket: MEN-6825
-------
> test: Verify that identity is marshaled the same way as in Go

- README.md
PS: Don't forget to add me to the list of C++ client contributors :smile_cat:
> docs: Update systemctl command in README.md to target correct units

- src/common/crypto/platform/openssl/crypto.cpp
- src/mender-auth/cli/actions.cpp
- src/mender-auth/cli/keystore.cpp
Simple fix for keys set in our configuration file
> Fix key regeneration issue when keys are set in the config

- support/mender-inventory-provides
> chore: Temporary add the version to an inventory script

- src/mender-update/http_resumer/http_resumer.cpp
This will cover the case for example when the host cannot temporary be resolved or the handshake fails.
It is explicitly tested on an integration test.
> MEN-6671: Resume downloads when the first header handler errors

- src/mender-update/daemon/states.cpp
This aligns the functionality with the existing Golang client, where provides
are not stored in the case of a failing deployment.
Ticket: MEN-6671
> fix: Only commit provides in the case of a successful deployment

- Documentation/io.mender.Update1.xml
> docs: mention the deprecation of control maps

- src/mender-update/cli/cli_test.cpp
- src/mender-update/standalone/standalone.cpp
> fix(standalone): Add Error state scripts to several missing locations.

- support/modules/rootfs-image
> chore(rootfs-image): Add bootloader canary check.

- src/mender-update/inventory.cpp
- src/mender-update/inventory_test.cpp
- support/mender-inventory-provides
> chore(inventory): Make sure `mender_client_version` is always submitted.

- src/api/auth/auth.cpp
- src/api/client.cpp
- src/api/client_test.cpp
- support/mender-authd.service
> chore: Fix assert when device is unauthorized.

- store/dbstore.go
> feat: recover from a corrupted db and save a working version.

- src/api/client_test.cpp
The test was actually passing already, but this was because both
clients would initiate their requests before the round trip calling
`GetJwtToken` would finish, thereby putting the second client in the
`pending_actions_` queue of the first. This caused the number of
tokens requested to still be one, contrary to what one would expect
after disabling caching. And typically not what would happen in
production.
Fix this by forcing the two clients to be called in sequence by stopping the event loop between them. Now `GetJwtToken` is called twice, as expected.
> test: Take into account that token is not internally cached anymore.

- src/common/CMakeLists.txt
- src/common/key_value_database/platform/lmdb/lmdb.cpp
- src/common/key_value_database_lmdb.hpp
- src/common/key_value_database_test.cpp
Ticket: MEN-6860
The second commit is the heart of the fix.
> chore: Back up and recreate database in case of database corruption.

- src/common/CMakeLists.txt
- src/common/crypto.hpp
- src/common/crypto/platform/openssl/crypto.cpp
- src/common/crypto_test.cpp
> Enable the OpenSSL Engine API for all builds

- CMakeLists.txt
This adds a few commits to optimize the mender binaries to be optimized for size.
> Add build time optimizations to minimize for size

- CMakeLists.txt
- src/artifact/parser.cpp
- src/artifact/v3/manifest_sig/manifest_sig.cpp
- src/artifact/v3/manifest_sig/manifest_sig.hpp
- src/mender-update/CMakeLists.txt
- src/mender-update/cli/cli_test.cpp
> fix: Make sure unsigned bootstrap artifacts can always be installed.

- LICENSE
- LIC_FILES_CHKSUM.sha256
(cherry picked from commit 682ccceb2084e58817c2f882a6e9b3366e01ef8c)
> chore(LICENSE): Update the license year to 2024

- src/client_shared/conf/conf_cli_help.cpp
> fix: Update incorrect default value for `--data` flag in help screen.

- src/common/processes/platform/tiny_process_library/tiny_process_library.cpp
Cherry-pick of the relevant commit from #1602
> 4.0.x: Fix line processing of data when reading a single byte

- src/client_shared/conf.hpp
- src/client_shared/conf/conf_cli_help.cpp
Changelog: Amend default paths printed in CLI help pages. Previously they could be modified by user environment variables.
Ticket: MEN-7133
> MEN-7133: Amend default paths for `--help`

- src/common/processes/platform/tiny_process_library/tiny_process_library.cpp
The message already existed in the non-redirect case, but not when collecting output.
Ticket: None
> fix: Improve error messages when executable can't be found.

- src/common/CMakeLists.txt
- src/common/path.hpp
- src/common/path/path.cpp
- tests/src/common/CMakeLists.txt
- tests/src/common/path_test.cpp
See https://github.com/mendersoftware/mender-update-orchestrator/pull/90
Ticket: MEN-7171
> chore: function for checking if files are identical

- src/common/events/events_io.cpp
- src/common/events_io.hpp
- src/common/io.hpp
Just various improvements I made while investigating a bug. In the end I didn't actually need any of these fixes, but they still seem like worthwhile improvements.
> Improvements

- .gitlab-ci.yml
Ticket: QA-614
(cherry picked from commit 81f5e35172fc08db04120db8dd6669d76c8e9ebd)
> feat: build and test using the latest version of golang (1.22 today)

- src/mender-update/http_resumer/http_resumer.cpp
- tests/src/mender-update/http_resumer/http_resumer_test.cpp
> 4.0.x: fix: Invalid Range request when content_length is 0 (unknown)

- support/CMakeLists.txt
- support/mender-inventory-intervals
It lets the user to check how soon the next poll would be and make decisions if that doesn't happen.
Ticket: None
```
```
Thank you!
> feat: Showcase the configured intervals as inventory items

- README.md
> Update README.md fixed typo from uptdated to updated

- src/artifact/parser.cpp
- src/artifact/v3/header/header.cpp
- src/artifact/v3/manifest/manifest.cpp
- src/artifact/v3/manifest/manifest.hpp
- src/artifact/v3/version/version.cpp
- src/artifact/v3/version/version.hpp
- tests/src/artifact/parser_test.cpp
- tests/src/artifact/v3/manifest/CMakeLists.txt
- tests/src/artifact/v3/manifest/manifest_test.cpp
> 4.0.x: Bugfixes for Artifact manifest

- Documentation/update-modules-v3-file-api.md
- src/mender-update/update_module/v3/update_module.hpp
- src/mender-update/update_module/v3/update_module_download.cpp
Various smaller fixes made while working on other tasks.
> Small fixes

- .gitlab-ci.yml
```
```
Some CI improvements:
* optimize submodule clone and to avoid submodule clone issues
* Moving out from GCP and public runners to Hetzner runners
* Moving to Gitlab Dependency proxy to avoid docker rate limit issue
> Git submodule depth

- .gitlab-ci.yml
To avoid the runc issue
Ticket: None
```
```
pin buildkid v0.17 to avoid the runc issue
> ci: pin docker v27.3

- src/artifact/tar/platform/libarchive/wrapper.cpp
- src/artifact/tar/platform/libarchive/wrapper.hpp
- tests/src/artifact/tar/tar_test.cpp
Cherry-picking #1702 and #1711.
> 4.0.x: MEN-7810 fix and changelog

- src/common/crypto.hpp
- src/common/crypto/platform/openssl/crypto.cpp
- src/common/http/platform/beast/http.cpp
- src/mender-auth/cli/keystore.cpp
- src/mender-auth/cli/keystore.hpp
- tests/src/common/crypto_test.cpp
> fix: Disallow copying and assignment for PrivateKey

- src/common/crypto/platform/openssl/crypto.cpp
Will now get the expected length of the DER encoded signature and use that to allocate an array to hold the encoded data.
Ticket: MEN-7979
> fix: Use the actual length of the DER encoded signature for the buffer

- tests/Dockerfile.daemon
- tests/entrypoint.sh
> chore: Remove ssh configuration from the docker test container

- src/common/events/platform/boost/events.cpp
Ticket: MEN-8051
Signed-off-by: John Olav Lund <john.olav.lund@northern.tech>
(cherry picked from commit 03f52ba5f75f6163d56a96ff90a0a48c21667413)
> 4.0.x: fix: Compile with Boost 1.87

- src/common/events/platform/boost/events.cpp
Ticket: MEN-8051
Signed-off-by: John Olav Lund <john.olav.lund@northern.tech>
(cherry picked from commit 03f52ba5f75f6163d56a96ff90a0a48c21667413)
> 5.0.x: fix: Compile with Boost 1.87

- src/common/http/http.cpp
- tests/src/common/http_test.cpp
> fix: Check for control characters in URLDecode

- src/common/http/platform/beast/http.cpp
> chore: Log an error when the server certificate fails to load

- src/common/http/platform/beast/http.cpp
> fix: Return an error when certificate fails to load

- README.md
Change the README part mentioning hosted offering and improve text explaining differences between open source and commercial.
```
```
Thank you!
> chore: Improve README and add better commercial offering explanation.

- src/common/http/platform/beast/http.cpp
- tests/src/common/http_test.cpp
Otherwise leftover trailing bytes from a previous response may be parsed as a beginning of the new response resulting in HTTP parsing errors.
Ticket: MEN-8554
Changelog: Fix issue where trailing bytes in an HTTP response break parsing of the future HTTP responses, resulting in `bad version` errors and failed HTTP requests
> fix: Clear response buffer before every HTTP request
