mendersoftware/mender

- .travis.yml
- main_test.go
Some functionalities we are using are introduced in go 1.6. Let's update Travis to use it.
> Update travis go to version 1.6

- support/mender-device-identity
The patch adds an example ntegration script for producing device
identity data. The script looks up a network interface with the lowest
ifindex, other than loopback interface, and grabs its MAC address. It is
assumed that /sys/class/net is available in the system.
The identity data is output to stdout and has a form of:
<key>=<value>
The script may produce some information to stderr, make sure that it's
accounted for by whoever is reading the output.
> support/mender-device-identity: example platform integration script

- README.md
First patch wraps lines in README at 70/80 characters per line. The original wrapping was at 120 characters making it difficult to read and edit.
The second patch adds documentation for platform integration and device identity.
> documentation update - device identity

- main.go
- mender.conf.example
The config is based on mender.conf shipped by meta-mender Yocto
layer. The default server address is points to localhost:9080, so that
the the client will try to access the local services set up with docker.
> mender.conf: add example mender config file

- device.go
- partitions.go
- partitions_test.go
The intention is to avoid conflicts with similarly named variables
being used in various U-Boot implementations. It's also the variable
being used by the new generic U-Boot patch for Mender in meta-mender.
> MEN-341: Switch to "mender_boot_part" U-Boot environment variable.

- Godeps/Godeps.json
- LIC_FILES_CHKSUM.sha256
- client.go
- client_test.go
- client_update.go
- client_update_test.go
- config.go
- config_test.go
- daemon.go
- daemon_test.go
- dirstore.go
- dirstore_test.go
- error.go
- error_test.go
- keystore.go
- keystore_test.go
- main.go
- main_test.go
- mender.go
- mender_test.go
- rootfs.go
- state.go
- state_test.go
- store.go
- store_test.go
- vendor/github.com/pkg/errors/.gitignore
- vendor/github.com/pkg/errors/.travis.yml
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/errors.go
While working on authorization implementation it turned out that the client code needs a refactoring, otherwise it would be hard to go through authorization steps in a clean manner.
The patch series introduces some major changes to the agent code, in rough detail these are:
* do away with inheritance (or struct/interface embeddeding) in favor of composition where possible; for instance `menderDaemon` does not need to export any interfaces, while `mender` should only export minimal set of interfaces
* introduce a single `Controler` interface
* split `Client` and `UpdateClient` to separate interfaces
* use a state pattern to implement client states, separates controler from actual state execution; operations on controler have been nicely moved to states
* introduction of `menderError` …
> client state refactoring & basic authorization setup

- auth.go
- auth_test.go
- client.go
- client_auth.go
- client_auth_test.go
- client_test.go
- client_update.go
- config.go
- fileseqnum.go
- fileseqnum_test.go
- identity_data.go
- identity_data_test.go
- keystore.go
- keystore_test.go
- main.go
- mender.go
- mender_test.go
- seqnum.go
- state.go
- state_test.go
The series of patches implemens a workflow for client authorization.
The first 5 patches are mostly cleanups/refactoring of things/helpers that were spotted along the way.
Device identity data is obtained using the helper script `support/mender-device-identity`. Right now the script outputs a per line `key=value` of identity data. This is parsed and collected into a single structure. @pasinskim suggested refactoring the script to just produce JSON output without the need for further parsing.
Seqnum is a sequence generator with storage backing. This is needed for authorization requests.
An authorization client is implemented by `AuthManager` interface, with `AuthDataMessenger` being a helper interface that wraps producing/consuming of authorization requests. Tried to make the interface …
> Authorization workflow

- daemon.go
I have noticed that we are not using stopChannel any more for stopping
daemon. This can be safely removed now.
What is more, looks like  mutexes are also not needed at this point
as Mender is one thread application so synchronization is not needed.
> Remove not needed lacks and stopChannel.

- identity_data.go
- main.go
- main_test.go
- mender.go
- mender_test.go
It may be reasonable to have separate command line switches for triggering bootstrap and authorization. The series renames the old `-bootstrap` switch to `-forcebootstrap` to make it more meaningful and introduces 2 new switches:
* `-bootstrap` - the client perform boostrap only and exit
* `-authorize` - the client performs a single authorization attempt and exits
Also extra cleanups for `runOptionsType`.
@kacf @pasinskim 
Edit: after review separate authorization and bootstrap switches were replaced with single `-bootstrap`.
> bootstrap & authorize CLI switches

- client.go
- client_auth.go
- client_auth_test.go
- client_test.go
- client_update.go
- client_update_test.go
- daemon_test.go
- main.go
- mender.go
- mender_test.go
- rootfs.go
- state_test.go
Cleanup of API client handling. Until now both `UpdateClient` and `AuthClient` created an instance of `http.Client` for requests. This has been replaced by a single instance of `ApiClient` interface kept by mender controller. `ApiClient` is limited to a single call `Do(*http.Request) (*http.Response, error)` that allows for using vanilla `http.Client` instance or one created by `NewApiClient()` helper call.
> API client cleanup

- auth.go
- auth_test.go
- client.go
- client_auth.go
- client_auth_test.go
- client_test.go
- mender.go
- mender_test.go
Add authorization data to outgoing API requests. The series add an `ApiClient` helper with a convenience method `Request()` for creating request wrappers. Request wrapper `ApiRequest` implements `ApiRequester` interface and automatically append authorization data to the outgoing request if none is present.
Mender controller has been updated to cache authorization code so that we don't waste time/cycles for reloading it each time it's needed.
@pasinskim @kacf
> Setup authorization data for API requests

- client_status.go
- client_status_test.go
- mender.go
- mender_test.go
- state.go
- state_test.go
First take on status reporting.
Sending status over HTTP is captured in `StatusClient`, implemented in the first part of this series. Failure to send a status report results in an error that the caller is expected to handle in some way.
`Controller` interface got a new function `ReportStatusUpdate` that returns a `menderError` or nil.
The fun part is captured in state handling. Basically each 'update' state (commit, install, fetch, reboot) can transition to a new error state - `UpdateErrorState`. Also each of these states carries the update information. This is nice, because we don't need to keep it as part of Controller's internal state. Update information should be saved as soon as we decide to apply an update (ideally when update check returns valid update information) and restored …
> Status reporting

- client_log.go
- client_log_test.go
- mender.go
- mender_test.go
- state.go
- state_test.go
A series of patches that adds support for uploading logs in case of update failure. For now there's a single 'update failed' log being reported.
> Log upload

- device.go
- mender.go
- mender_test.go
Interpret empty check update response as no update avaialble.
> mender: handle empty check update response

- daemon.go
- daemon_test.go
- dirstore.go
- dirstore_test.go
- main.go
- mender.go
- state.go
- state_test.go
- store.go
- store_test.go
A proposal of a method for preserving state information across reboots. Update related actions such as reporting of log upload require information on the update that is applied. Since update will normally involve a reboot at some point, we need to capture and preserve update information across reboots, so that it's possible to report update progress after the system was restarted.
The series adds a new entry called `state` to client data store. The `state` file contains JSON serialized `StateData` structure, that captures both the update response and the last state ID. State data is stored when entering a state handler. Loading happens only when entering `UpdateCommitState`. The state entry is removed after an update has been committed.
There are still some open questions about what to do …
> Preserve state data across reboots

- client.go
- client_auth_test.go
- client_log_test.go
- client_status_test.go
- client_test.go
- client_update_test.go
- config.go
- config_test.go
- main.go
- rootfs_test.go
It might be useful to skip SSL certificate validation when troubleshooting integration issues.
> Allow for skipping SSL certificate validation

- client_update.go
- client_update_test.go
- config.go
- config_test.go
- daemon_test.go
- mender-default-test.conf
- mender.conf.example
- mender.go
Small patch series that updates the API endpoints of deployments service. 
Also, Device ID is no longer needed as we no longer need to explicitly pass it in any outgoing request. The series addresses this by removing `DeviceID` from configuration.
@kacf
> Deployments API changes & Device ID

- client_log.go
- client_log_test.go
- client_status.go
- client_status_test.go
Last part of device ID cleanups. Patches 1 and 2 remove device ID from URLs and structures that are passed to the code making an actual API request. The changes are harmless, as device ID was never really passed form mender controller.
The last 2 patches address URL changes in deployments API.
@pasinskim @kacf @GregorioDiStefano
> No device & URLs update

- deployment_logger.go
This was left by accident while merging client logging.
> Remove printing message to stdout.

- main.go
Having log level set to debug we will make sure all log messages will
be available for the journal. Then we can configure journal which
level messages will be filtered out and which ones will be stored in
the system.
> Set debug as default log level for Mender client.

- deployment_log_hook.go
- deployment_logger_test.go
At the moment server endpoint requires JSON log format as follows:
{"level":"info", "message":"log", "timestamp":"2016-08-09T12:03:53Z"}
We are adding new custom log formatter to make sure that logs are
formatted as expected by the server.
> Make sure that deployment logs are formatted correctly.

- state.go
Use `maxReportSendingTries` to make sure that we are trying to send
status and logs finite number of times.
If we are not able to send status or logs we are marking update as
failed and trying to rollback (rollback needs to be implemented).
> Finalize sending deployment logs and status to server.

- state.go
If we are installing broken image device is rebooted reaching
`we have upgrade info but has flag is not set` point.
Here we are sending no information to the server that last update was
broken and we are entering infinite loop of fetching and installing
broken update.
Right now we will try to report broken update so that server will be able
to remove it from the queue.
> Make sure to report failed update after rebooting with broken image.

- deployment_logger.go
- deployment_logger_test.go
- state.go
- state_test.go
If there is not enough space for storing deployment logs we need
to invalidate the update.
> Check if there is enough disk space for logs before starting update.

- Makefile
This will be useful when we start using dependencies that require cgo
> Makefile: do not force CGO_ENABLED when building

- Makefile
Shrinks the mender binary by 30%, but debug symbols are lost.
@kacf @bboozzoo
> Reduce binary size by removing debug symbols

- Makefile
This reverts commit b5d0c8f86a17ce3bd22961cb3b8baf4e3e0db338.
> Revert "Reduce binary size by removing debug symbols"

- mender.go
- mender_test.go
Basically this:
```
DEBU[0000] Reading Mender configuration from file ./mender.conf.example  module=config
DEBU[0000] block type: RSA PRIVATE KEY                   module=keystore
WARN[0000] No client key and certificate provided. Using system default.  module=client
WARN[0000] certificate verification skipped..            module=client
DEBU[0000] handle init state                             module=state
INFO[0000] Mender state: init -> bootstrapped            module=mender
DEBU[0000] handle bootstrapped state                     module=state
INFO[0000] authorization data present and valid, skipping authorization attempt  module=mender
INFO[0000] Mender state: bootstrapped -> authorized      module=mender
ERRO[0000] I/O read error for entry state: open state: no such file or directory …
```
> mender: user friendly state naming

- Makefile
- client_inventory.go
- client_inventory_test.go
- identity_data.go
- inventory.go
- inventory_data.go
- inventory_data_test.go
- main.go
- mender.go
- mender_test.go
- paths.go
- paths_local.go
- state.go
- state_test.go
- support/mender-device-identity
- support/mender-inventory-network
Introduce inventory support. `Controller` interface is extended with `InventoryRefresh()` method. New state `InventoryUpdateState` is added to the state machine, and is executed right after `UpdateCheckState` in case no update is present. Additionally, the state will be run when transitioning from `AuthorizedState`, so that we get a refresh of inventory data if Mender client was restarted.
A couple of extra commits introduce (incomplete) support for 'local' builds. Something I wanted to explore before, but had it only as a couple of stashed patches. The idea is that it would be nice to be able to build and run mender locally as part of one's development cycle. Right now we can build the client, but running it will bail out early in `HasUpgrade()`. Even if one adds `return false, nil` over …
> inventory reporting & improvements

- auth.go
Trim the newline in the authorization tenant token before adding it to the http headers. 
This is a fix for:
```
Sep 13 10:01:20 vexpress-qemu mender[1390]: level=error msg="I/O read error for entry authtoken: open /var/lib/mender/authtoken: no such file or directory" module=dirstore
Sep 13 10:01:20 vexpress-qemu mender[1390]: level=error msg="authorize failed: transient error: authorization request failed: failed to execute authorization request: Post https://mender-api-gateway/api/devices/0.1/authentication/auth_requests: net/http: invalid header field value \"Bearer dummy\\n\" for key Authorization" module=state
Sep 13 10:01:20 vexpress-qemu mender[1390]: time="2016-09-13T10:01:20Z" level=error msg="authorize failed: transient error: authorization request failed: failed to execute …
```
> Trim token of whitespaces before adding header

- main.go
- main_test.go
In #109 the behavior of `http.Client` was changed by runtime. It would be nice to include runtime version information in `-version` output so that we could spot any differences faster.
> main: include runtime information in -version output

- mender.go
- mender_test.go
- state.go
If we are installing image which id is the same as currently running
we are reporting update success to the server.
> MEN-626 Return success in case of installing image with existing id.

- state.go
- state_test.go
Previously when we've been not able to send status to the server after
successful update we've been rolling back to the last working image.
The problem was that `report state` has been saved as the last known state
with the status `success`. Once device was rebooted it continued to send
`success` to the server even though we rolled back.
This is fixing the issue by verifying exact state before sending report
to the server.
It also uses `reboot` state as a part of rollback.
> MEN-630 Check update status before sending report to server.

- state.go
- state_test.go
Retry update status report attempts for 5 minutes, after that return an
error and assume that reporting failed.
@pasinskim @kacf @GregorioDiStefano
> state: use time based limits for update state report attempts

- main.go
> Avoid from crashing when auth manager is not initialized.

- CONTRIBUTING.md
Clarify that Google groups is a mailing list, not a forum.
Also remove contact@mender.io as a contact point for pull requests. It
is not the appropriate channel for such requests.
> Contribution improvements

- rootfs.go
- utils/progress.go
- utils/progress_test.go
Add support for installation progress display when meder is used in `-rootfs` mode. Demo:
https://asciinema.org/a/4cp2bwmdg5whlqywk7wyst3bi
> rootfs image installation/download progress display

- client/client_status.go
- client/test/server.go
- mender.go
- mender_test.go
- state.go
- state_test.go
The first problem is fixed by not adding `Authorization` header to update fetch requests.
The second is addressed by removing `StateError`. It looks that `StateError` was used interchangeably with `StateFailure`, what led to subtle error when reporting update status that resulted in logs not being uploaded.
@pasinskim @kacf
> Fixes for MEN-759, MEN-760

- .travis.yml
oe-meta-go commit fbd51ce introduced Go 1.7.3. Bump travis config to use
the same version.
@pasinskim @kacf
> travis: bump Go version to 1.7.3

- mender-default-test.conf
This follows the change in f33956deab76069251.
> MEN-806: Split poll intervals and increase to 30 min.

- mender.go
- state.go
- state_test.go
So far we've been storing update state as number (`MenderState`).
There is potential risk in this method as after adding some more
states we might end up with some issues after upgrade.
Let's assume we are upgrading client from the version 1.0 to
version 1.1. In the version 1.1 some state was added which is changing
the order of states. In such a scenario, state stored in version 1.0
will be interpreted differently by version 1.1.
This is supposed to fix the ambiguity in storing and loading states.
> MEN-812 Do not store state as number.

- bootenv.go
- bootenv_test.go
- statcommander_test.go
We need to update the environment in one operation, because otherwise
it can be in an in-between state if the device goes down unexpectedly.
The actual atomicity of the operation is ensured by U-Boot and its
redundant environment, we just need to call the right command.
One test case was removed because it's not possible to get such an
error anymore.
> MEN-480: Make sure U-Boot environment update is atomic.

- config.go
- mender.go
- state.go
- state_test.go
Set the default poll interval to 30 minutes in case not configured.
Add retry poll interval configuration option and use it for re-sending auth requests and reports.
> Client interval and resending improvements.

- error.go
- state.go
- state_test.go
```
commit 5823e4fdb9351a9870f5e49e15bc5f715d5d4955
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Thu Dec 22 11:25:28 2016
Improve description of error types.
commit 6061a3198cee05b77a1c4d17288b3a368dafdf1f
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Fri Dec 23 13:46:08 2016
Turn CancellableState into an interface for easier testing.
commit 5024e5bb80a31588ca5e21134e02adb8934641d2
Author: Kristian Amlie <kristian.amlie@mender.io>
Date:   Fri Dec 23 13:48:37 2016
MEN-873: Implement download retrying.
Image download is retried using a simple algorithm: Start with one
minute and try three times, then double interval and repeat. If we
exceed the …
```
> MEN-873: Implement download retrying

- state.go
- state_test.go
This is fixing some logic errors while detecting errors. Most notably, after detecting errors, client is entering `init` state, causing some important actions not being taken.
> Fix transition between states while errors occur

- mender.go
- state.go
This gives both better debug messages, and we can save the state to
the database so that we resume on next reboot.
> Add separate state when retrying downloads.

- client/client.go
- client/client_test.go
This is in order for 3rd party download servers to work, such as S3,
which will not have custom certificates.
> MEN-939: Include standard certificate authorities in client cert pool.

- state.go
- state_test.go
This is changing rollback state to perform reboot itself, instead of
switching to reboot state. The reason is we are storing state
information in reboot state and we are checking if deployment is valid.
In case of aborted deployment, which was correctly detected after
device was rebooted we've been entering rollback and then reboot state.
As deployment was aborted instead of continuing with reboot we
reported error and went back to error and then init state.
No rollback happened in this scenario.
> MEN-961 Make sure rollback happens after deployment is aborted

- state.go
We need to reset the counter otherwise the next fetch or install
fail will be retried only once.
> Zero update install counter.

- Makefile
Some sub packages don't have tests, so this means we also have to
test for their existence before attempting to use their results.
> Makefile: Make sure we don't ignore return codes inside for loop.

- installer/installer.go
- installer/installer_test.go
- rootfs.go
If there is a verification key present, but the artifact signature
is missing do not install artifact.
> MEN-1181 Do not install artifact if signature is missing.

- main.go
- rootfs.go
- rootfs_test.go
Remove command line parameter specifying the location of the
artifact signature verification key and use the value stored
in configuration file instead.
> MEN-1195 Use verification key location from configuration file.

- LIC_FILES_CHKSUM.sha256
One license was incorrectly listed under MIT, it should be ISC.
> Clean up license checksums.

- vendor/github.com/mendersoftware/mendertesting/check_commits.sh
Probably it still passed because the file can be found in the GOPATH
instead.
> Include file that was accidentally omitted in last commit.

- client/client.go
- client/client_auth_test.go
- client/client_inventory_test.go
- client/client_log_test.go
- client/client_status_test.go
- client/client_test.go
- client/client_update_test.go
- config.go
- main.go
- mender.conf.example
- rootfs_test.go
Changelog: remove no longer referenced client certifate code
See: MEN-1292
> remove lingering client certificate code

- config.go
- config_test.go
- main.go
- mender_test.go
DeviceKey file is now a constant set in the source code.
> Removed the DeviceKey option in menderConfig.

- installer/installer.go
- installer/installer_test.go
Include image device types and own device type in an error thrown when image is
incompatible with the device.
@kacf @pasinskim @oleorhagen @GregorioDiStefano
> installer: improve incompatible image error message

- statescript/executor.go
- statescript/statescript_test.go
If there are some rootfs state scripts, but version file is missing
update needs to be failed and client should do rollback.
> MEN-1305 Fail update if rootfs scripts version is missing

- statescript/executor.go
- statescript/statescript_test.go
MEN-1349: Mender now logs whatever a state-script outputs to stderr
Will log to file from all states except Sync and Idle
(cherry picked from commit 5dde085b594cb5c79462fe7eacb51b25905e9b50)
> 1.2.x cherry-picks

- config.go
- mender.go
- state.go
- statescript/executor.go
- statescript/statescript_test.go
For now, a retry later will stop the main execution thread with a
time.Sleep for a default, or user-configured interval.
> Added retry-later functionality on top of the state-script functionality 

- support/mender-device-identity
The script only skipped "lo" interfaces while looking for the
lowest ifindex number. There are a lot more "virtual" interfaces [1]
beside "lo" and we could pick up an MAC address from something
that does not actually have a MAC address since ifindex number is
set based on probe order basicly.
This is of course a example script only and should probably not handle
every configuration possible out there but it should at least handle
the most common one well.
Example of picking up a strange address from a "odd" device:
./mender-device-identity
using interface /sys/class/net/sit0
mac=00:00:00:00
[1]. http://elixir.free-electrons.com/linux/latest/source/include/uapi/linux/if_arp.h
Signed-off-by: Mirza Krak <mirza.krak@endian.se>
> mender-device-identity: only collect MAC from ARPHRD_ETHER types 

- .travis.yml
- Makefile
- client/client.go
- client/client_test.go
- client/client_update.go
- client/client_update_test.go
- client/update_resumer.go
- client/update_resumer_test.go
- mender.go
- rootfs.go
- state.go
- state_test.go
This implements the ability of the client to resume download if the
connection is broken for any reason. It does this by replacing the
socket reader with a custom reader object that keeps track of the read
offset, and if it is broken at any point, the download is
reestablished at the same point and reading continues.
This requires some custom parsing of the 'Content-Range' header, since
Go does not have this support natively on the client side. We
primarily need the offset that the server gives us back, with some
surrounding code to check for sanity of the returned header. All
according to HTTP spec.
One weakness of this method is that it is not possible to abort the
update and have the client notice this in the middle of the download,
even if the connection is broken. But this would …
> MEN-1511: Implement download resume feature.

- config.go
- config_test.go
If the server URL contains trailing slash it is impossible to
make valid requests to the server. This commit is removing slash
form configuration parameter if there is one.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
> MEN-1620 Remove trailing slash from server URL configuration.

- support/mender-device-identity
Mender on oragepi fails to run because identty script exit with error like:
/usr/share/mender/identity/mender-device-identity
cat: can't open '/sys/class/net/bonding_masters/type': Not a directory
Add check before reading type to avoid problems.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
> mender-device-identity: Check if file exists before reading

- config.go
This was originally meant to be a file, but we have moved away from
that, and it is now a string from the config file. Hence empty string
is the correct string if missing.
> Do not set missing token to "authtentoken". 

- client/client.go
- client/client_test.go
- deployment_logger.go
- mender.go
- mender_test.go
The responsecode for each http api-requests is explicitly checked and handles 401 by issuing for a new JWT token.
> FIXED: MEN-1854: HTTP error 401 is not handled by all states

- bootenv.go
- bootenv_test.go
- partitions.go
- partitions_test.go
The way it works is that we store the 'mender_check_saveenv_canary=1'
variable in the default U-Boot environment. We do not store the
corresponding 'mender_saveenv_canary=1' value in the default
environment, but instead we write this during the boot process. When
the Mender client finds the former variable, it will look for the
second value as well, and produce an error if it is not present. If
this happens it is an indication that the U-Boot boot loader and the
user space tools do not agree on the location of the environment. It
will also catch cases where mender_setup is not run.
Also reorganize the logging and error returning to include the error
when returning higher up in the callstack, otherwise the resulting log
entry is quite misleading.
Changelog: Add automatic check for canary …
> Add check for canary value in U-Boot environment.

- daemon.go
- daemon_test.go
- main.go
- main_test.go
- state.go
- state_test.go
The user can now force an update check by either running mender with the
-check-update option, or send a signal [SIGUSR1] to the running mender process.
> MEN-1905: Enable user to force an update-check locally

- partitions.go
There are situations where it nearly impossible to find the active
root-filesystem based on probing mounted devices.
One example is this:
/dev/root on /rom type squashfs (ro,relatime)
There is no information about the actual device device used in above
example.
One additional probe step could be parsing /proc/cmdline to find the
"root=" argument but this is essentially the same as looking at
"mender_boot_part" environment variable.
Hence we add a fall-back to only using the "mender_boot_part"
environment variable and comparing that to what we have in
"mender.conf".
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>
> Fall-back to environment and conf in active part probe

- config.go
- config_test.go
- main.go
Changelog: Mender client now loads configuration settings from
both /etc/mender/mender.conf and (if it exists)
/var/lib/mender/mender.conf. The second file is located
on the data partition, so it allows any subset of configuration
changes to survive upgrades.
Previously, Mender loaded configuration settings from a
single file on the active root partition: /etc/mender/mender.conf
Like everything else on the root partition, this config file
is replaced with each upgrade.
Let us call /etc/mender/mender.conf the "main" configuration file.
Now there is an additional "fallback" configuration file,
/var/lib/mender/mender.conf, stored on the data partition.
If a setting is in the main file, it will be used.
If a setting is not in the main file but is in the fallback
file, the fallback value will …
> MEN-2073: Merge configuration settings from two files.

- installer/installer.go
- main.go
Changelog: Print a message to the mender log when the
mender client has confirmed the authenticity of an
artifact's digital signature.
When the Mender client authenticates a downloaded
artifact's digital signature using a public key configured
by the property "ArtifactVerifyKey" in mender.conf,
it now logs the following message:
"installer: authenticated digital signature of artifact"
This allows the developer to confirm that verification
of mender.sig took place, and that this Mender client
will reject any future downloads bearing a forged signature.
When the Mender client is not configured with a public
key for authenticating downloaded artifacts, log
the following message:
"no public key was provided for authenticating the artifact"
This informs the developer that no signature …
> [1.6.x] MEN-2152: Log whether artifact's digital signature is valid 

- installer/installer.go
- main.go
- partitions.go
Changelog: Print a message to the mender log when the
mender client has confirmed the authenticity of an
artifact's digital signature.
When the Mender client authenticates a downloaded
artifact's digital signature using a public key configured
by the property "ArtifactVerifyKey" in mender.conf,
it now logs the following message:
"installer: authenticated digital signature of artifact"
This allows the developer to confirm that verification
of mender.sig took place, and that this Mender client
will reject any future downloads bearing a forged signature.
When the Mender client is not configured with a public
key for authenticating downloaded artifacts, log
the following message:
"no public key was provided for authenticating the artifact"
This informs the developer that no signature …
> [1.5.x] MEN-2152: Log whether artifact's digital signature is valid

- installer/installer_test.go
The test is duplicated in TestInstallNoSignature.
> Removed duplicate test from TestInstallSigned

- LICENSE
- LIC_FILES_CHKSUM.sha256
> Updated the copyright year to 2019 in LICENSE.

- client/update_resumer_test.go
- daemon_test.go
- state_test.go
Extended the existing unit test to use different poll intervals for
update and inventory. This way we can verify that they are independent
and work as intended.
The interface stateTestController required modifications accordingly
> MEN-2214: Test that both intervals work independently

- CONTRIBUTING.md
> Update mailing list link to Mender Hub

- client/client.go
> Remove misleading warning message when ServerCert is missing.

- Makefile
- block_device.go
This is important for us since some packages are being mainly tested
by being included in higher level package code.
(cherry picked from commit 37afcbb9a143e9884b6619328b66ab1c1256fa10)
> Enable coverage reports for sub packages as well.

- device.go
- partitions.go
- partitions_test.go
Changelog: Mender no longer misidentifies LVM volumes.
> MEN-2302: Only resolve symlinks in /dev/disk/by-partuuid.

- support/mender-inventory-network
Some network interfaces may not have a mac address (e.g. CAN adapters). If these are pushed to the hosted mender backend it returns a 400-error and nothing is written to the inventory.
Signed-off-by: Rick Pannen <pannen@gmail.com>
> Don't push network interfaces without a mac address to inventory

- support/modules-artifact-gen/file-install-artifact-gen
- support/modules/file-install
For the single file install use case, the user will probably want to add
the file in a directory rather than to replace the contents of it with
the file.
Removed also the "install" dependency, using mkdir instead
> Fix File Install UM to not wipe out dest_dir on single file installs

- statescript/executor.go
- statescript/statescript_test.go
- statescript/store.go
Changelog: Version files are now allowed to contain a newline character. Also
some minor changes, as readVersion now accepts an io.Reader, and files are
opened outside of the function. This means that the error message is now
consistent for all the uses of readVersion.
> MEN-2301: Version files are now allowed to contain a newline character. 

- Documentation/update-modules-v3-file-api.md
- Makefile
- daemon.go
- state.go
- state_test.go
- support/modules/file-tree-install
- support/modules/single-file-install
- tests/rootfs-image-v2
The motivation behind is change is to promote the use of `Automatic`
in all update modules. We want this because in order to support
multiple payloads, an update module should not reboot the host in its
`ArtifactReboot` script. Doing so means that `ArtifactReboot` scripts
in later payloads do not get to execute. Instead it should leave this
to Mender using the `Automatic` mechanism. Multiple payloads have not
been implemented yet, but since `Automatic` needs to be supported by
the update module itself, we implement this part now so that we don't
accumulate too many modules without it before we get multiple payload
support.
Note that the most important test of this feature is by changing the
`rootfs-image-v2` script, which is then used by the integration test
which already exists. …
> Update modules: Implement `NeedsArtifactReboot` -> `Automatic`.

- support/mender-inventory-bootloader-integration
(cherry picked from commit 42d2f29e499570fe54ccbfe15e27d2f4a89eb59b)
> [2.0.x] Make sure ARM64 is included in bootloader integration inventory.

- support/mender-inventory-bootloader-integration
(cherry picked from commit 42d2f29e499570fe54ccbfe15e27d2f4a89eb59b)
> [1.7.x] Make sure ARM64 is included in bootloader integration inventory. 

- config.go
- config_test.go
- device.go
- mender.go
This adds a new 'DeviceTypeFile' parameter to /etc/mender.conf to enable the device_type file to be positioned somewhere other that its default location of /var/lib/mender/device_type (aka /data/mender/device_type).
In our setup the data partition will be completely erased upon factory reset, or in case of filesystem corruption. We have a dedicated read-only partition for permanent data such as hardware revisions, so this patch allows us to point Mender there instead.
> Make the device type file location configurable

- client/client.go
- main.go
- main_test.go
Changelog: Title Instead of bailing out on an invalid server certificate,
the client now prints a verbose error message, and then starts up the daemon,
as opposed to dying.
> MEN-2378: Print warning on an invalid server certificate.

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
- support/modules/single-file
```
commit e2ff07c375bde3b7a0d6d4bd89f107b0bd28ab90
Date:   Mon May 13 11:00:34 2019
Artifact gen: Support argument passthrough to `mender-artifact`.
Use `--` to signal that remaining arguments should be passed directly
to `mender-artifact`.
commit 0e62b78c176fdd91e0b94b6796fa2e6dce358369
Date:   Thu May 9 14:45:39 2019
single-file module: Make sure permissions are preserved.
Also make sure that backup preserves permissions.
commit 888299194bc37ac571d2c1c5b57157f689479316 …
```
> Update modules fixes

- daemon.go
- daemon_test.go
- main.go
- main_test.go
- state.go
- state_test.go
Provide command line interface to force inventory update. The client
now is able to be forced into an inventory update check state by sending a
SIGUSR2 signal to the running daemon. One quirk of the implementation is that
the forcedWakeUp channel is now global in the stateContext, therefore, an
unconsumed signal will force an extra wake-up at a later stage, if not consumed
straight away. However, this was chosen as a compromise in order to avoid
relying on synchronization primitives. Furthermore, an updatecheck or inventory-
update can only be forced from idle-state or the update- and inventory-update
states themselves. This done so that the state-machine cannot be forced from
random states into doing an update-check. The original state-machine logic has
to be respected. …
> MEN-2131: Provide command line interface to force inventory update. 

- installer/dual_rootfs_device_test.go
By not requiring explicitly the substring "requires root privileges" in
the error message.
The intention of the test remains unchanged, and now we can run the unit
tests from Docker containers or other privilaged scenarios.
> Accept running the unit tests as root user

- standalone.go
The exact error is picked up in main.go.
Reported-by: Cedric Veilleux <mender@discoursemail.com>
(cherry picked from commit 0918ddc7c0861cbfc1e416be1b15bcf9ecb3cb47)
> [2.0.x] Restore error code 2 behavior when there is nothing to commit.

- examples/state-scripts/retain-systemd-network/Download_Leave_02
script file example for retaining *.network files with systemd
I modified the retain-ssh-keys script to do the same with network configuration files and want to provide it for other users. It works like a charm with my mender image.
Signed-off-by: Dirk Siegmund <siegmund@beckmann-gmbh.de>
> Download_Leave_02

- tests/rootfs-image-v2
We should to read the final empty entry to make sure the client does
not block.
Changelog: commit
> rootfs-image-v2: Make sure to follow the spec regarding `stream-next`.

- main.go
This PR fixes improper usage of signal.Notify(...) func from Go std lib.
Channel must be buffered to properly receive signals:
https://golang.org/pkg/os/signal/#Notify
Also there is no need to reallocate channel each time user signal is received.
Deferring of signal.Stop(...) doesn't make any sense in the context.
> Make channel receiving user signals buffered

- support/mender-inventory-os
Fix `/bin/lsb_release` not being picked up by inventory script.
(cherry picked from commit 4d3e3a6f0f0a254423c33352c46273210a538c52)
> 2.0.x cherry-picks

- installer/dual_rootfs_device.go
Read error may be masked since chunkedCopy(...) func always return nil error if readErr != nil.
Only io.EOF error should be masked.
Other changes are stylistic to make variables conform with Go naming conventions, to eliminate unnecessary zeroing of already zeroed return parameter and to use right format specifiers for integers.
> Fix read error masking in installer.chunkedCopy(...) func

- installer/dual_rootfs_device.go
- standalone.go
- statescript/store.go
This PR is just a code simplification. There are several places in the code base where conditions don't have any impact on logic. Thus it's safe to remove them to simplify code.
Also Go uses short circuit evaluation for logical operators:
https://kuree.gitbooks.io/the-go-programming-language-report/content/22/text.html
That's why conditions like
if err == nil || (err != nil && ...)
may be shortened to
if err == nil || (...)
> Remove useless conditions to simplify code

- standalone.go
Since, the Mender 2.0 can take both file and rootfs as artifact, it is better to update the log with the corresponding CLI option (i.e. install). Otherwise, ' file update ' error also will show as "rootfs called without needed parameters"!
Signed-off-by: Ajith P Venugopal <ajithpv@outlook.com>
> Update rootfs to install

- support/modules/single-file
Without this commit, ArtifactRollback() state is not
executed until the end.
Fixes:
root@nitrogen8m:~# mender -rollback -debug
...
INFO[0000] Update module output: + test -f /var/lib/mender/modules/v3/payloads/0000/tree/tmp/dest_dir/  module=modules
INFO[0000] Update module output: + exit 0                module=modules
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
> module/single-file: make sure filename is well defined

- daemon.go
Previously the `mender -send-inventory` command did not force the state
machine to the correct state, since `checkWaitState` returns the next state
to be handled, and not itself. Therefore the woken state machine would simply
handle the next expected event, and not `send-inventory` as this was
completely random whether would happen or not. Unlucky users therefore
reported this as having to run `-send-inventory` twice in the cases that
`send-inventory` was not the next event scheduled to happen.
> MEN-2721: FIX: `mender -sender-inventory` next state fix.

- Makefile
It was returning unknown. The definition of Version was moved to a conf
package while refactoring in 8a75a8c and the Makefile was not updated
accordingly.
> Fix `mender --version` option

- app/mender.go
- app/mender_test.go
- app/standalone.go
- app/standalone_test.go
- app/state.go
- app/state_test.go
- app/transition_test.go
- datastore/datastore.go
- datastore/dbkeys.go
- datastore/standalone_data.go
- datastore/statedata.go
- installer/installer.go
- installer/installer_test.go
- tests/artifact_utils.go
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/metadata.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/signer.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/writer.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/common.go
- vendor/github.com/mendersoftware/mender-artifact/handlers/rootfs_image.go
- vendor/vendor.json
The ArtifactName attribute is moved to the provides sub-structure of
statedata, keeping the old ArtifactName attribute for comatibility in
the base structure (NOTE: renamed the old attribute to
ArtifactNameAlias to mark it as an unused attribute).
> store: Handle mender-artifact ArtifactProvides attribute in headerinfo

- support/modules-artifact-gen/directory-artifact-gen
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
> support: modules-artifact-gen: Fix typo in default name of output file

- .gitlab-ci.yml
Add verbosity to curl call for triggering deb package Pipeline: GitLab json response contains the URL of the new Pipeline.
> Add verbosity to curl call for triggering deb package Pipeline

- cli/cli.go
- cli/setup.go
- cli/setup_test.go
Rename `--mender-professional` flag to `--hosted-mender`, and adding a `quiet` option to suppress informative prompts.
I also removed the `run-daemon` option from setup flags as it seems redundant.
> Setup fixup

- cli/setup_test.go
Remove device type confirmation from setup unit tests
Fixes the current hung in CI when running the unit tests.
Missing from commit aeb3db2 and overlooked at PR #457. The reason for
the unit tests not to run in the original PR is unknown.
> Remove device type confirmation from setup unit tests

- .gitlab-ci.yml
Trigger mender-dist-packages Pipeline on master builds also
The intention was to rebuild mender-dist-packages on master always to be
able to early catch regressions. So the condition was just missing.
> Trigger mender-dist-packages Pipeline on master builds also

- Makefile
- app/mender_test.go
- client/update_resumer_test.go
- installer/modules_test.go
- inventory/inventory_data_test.go
The newly added go vet check failed on master, due to a merge that was not
rebased. This fixes the vet errors, as well as adds it to all the test-files,
which was previously not done.
> Fix: Pass Go vet check on master

- support/mender-inventory-rootfs-type
Some kernels (confirmed on at least 2.6.37) have a special "rootfs" device
in /proc/mounts:
```
rootfs / rootfs rw 0 0
ubi0_0 / ubifs ro,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=121740k,nr_inodes=30435,mode=755 0 0
proc /proc proc rw,relatime 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620 0 0
tmpfs /dev/shm tmpfs rw,relatime,mode=777 0 0
tmpfs /tmp tmpfs rw,relatime 0 0
tmpfs /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
sysfs /sys sysfs rw,relatime 0 0
ubi0:data /data ubifs rw,relatime 0 0
```
Make sure to skip this "rootfs" device when determining rootfs type.
> Skip special device "rootfs" when determining rootfs type

- Makefile
```
mdb.c: In function ‘mdb_cursor_put’:
mdb.c:6535:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
if (SIZELEFT(fp) < offset) {
^
mdb.c:6540:5: note: here
case MDB_CURRENT:
^~~~
```
> Silence annoying warning from lmdb.

- cli/cli.go
- cli/commands.go
- client/client.go
- client/client_auth_test.go
- client/client_test.go
```
commit 8b74abe167b13ca3dc02cd179d2b37a8bef63959
Date:   Mon Jan 20 14:04:58 2020
MEN-3047: Fix crash when specified certificate can't be opened.
Changelog: Fix crash when specified certificate can't be opened.
Both the `ServerCertificate` setting and the system certificates are
now optional, in the sense that the client will run without them.
However, the client will not be able to connect without the right
certificates, so the main usecase of this change is to have a workable
client that will roll back if connections can't be made, instead of
exiting.
Also redid the `TestEmptySystemCertPool` test. This test actually
never worked as intended, because Go caches the system certificates
behind the scenes, so it only worked if you ran …
```
> MEN-3047: Fix crash when specified certificate can't be opened.

- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
The previous error message does not really make sense to people unfamiliar with
the source code. The message read:
“Fetching Artifact headers failed: installer: failed to read Artifact:
readHeaderV3: handleHeaderReads: Cannot load handler for unknown Payload type
'rootfs-image'"
Which to outsiders does not really make much sense without some serious head
“Fetching Artifact headers failed: installer: failed to read Artifact:
readHeaderV3: handleHeaderReads: Artifact Payload type 'update-type' is not
supported by this Mender Client"
for the generic case. And with a special addition to the most common
rootfs-image type:
“Fetching Artifact headers failed: installer: failed to read Artifact:
readHeaderV3: handleHeaderReads: Artifact Payload type 'rootfs-image' is not
supported by this Mender …
> MEN-3007: Improved error message when an update-module is missing

- app/mender.go
- client/client_update.go
- client/client_update_test.go
- client/test/server.go
- device/device.go
This will add the device provides from the datastore, encode them in the request
body, and send them along with the deployments/next API call, in which the
deployments endpoint will decide upon what to do. If it is to treat it like an
old API call, or handle the provides is up to the backend.
> MEN-2587: Added Client provides to deployments/next API call

- cli/cli.go
- cli/cli_test.go
- cli/commands.go
Fixes https://tracker.mender.io/browse/MEN-3277
- MEN-3277: Fix check-update and send-inventory options on deb install
When installing mender client through deb package, the systemd service
is renamed to mender-client, so these two CLI options were failing in
sending the signal to the daemon.
- Generate an error message when MainPID is 0
For a non-existing process, systemctl returns MainPID=0 instead of an
empty string. Make the error clearer for these cases.
> MEN-3277: Fix check-update and send-inventory options on deb install

- system/ioctl.go
The unix.Major and unix.Minor functions takes an argument of type uint64 and the code currently passes in either stat.Rdev or stat.Dev into these. While stat.Dev and stat.Rdev are often defined as uint64 this is not so for every architecture. See for example mips64el where the fields instead are uint32 [1]. This causes a build failure (atleast with golang 1.14) on architectures where the assumtion doesn't hold true. This change simply casts the value to uint64 before passing it into unix.Major/Minor to fix the build problem.
[1]: https://sources.debian.org/src/golang-1.14/1.14-2/src/syscall/ztypes_linux_mips64le.go/#L107
Signed-off-by: Andreas Henriksson <andreas@fatal.se>
> Fix Stat_t.Dev/Rdev type assumption

- system/ioctl.go
Cherry picking #509 
The unix.Major and unix.Minor functions takes an argument of type uint64 and the code currently passes in either stat.Rdev or stat.Dev into these. While stat.Dev and stat.Rdev are often defined as uint64 this is not so for every architecture. See for example mips64el where the fields instead are uint32 [1]. This causes a build failure (atleast with golang 1.14) on architectures where the assumtion doesn't hold true. This change simply casts the value to uint64 before passing it into unix.Major/Minor to fix the build problem.
[1]: https://sources.debian.org/src/golang-1.14/1.14-2/src/syscall/ztypes_linux_mips64le.go/#L107
Signed-off-by: Andreas Henriksson <andreas@fatal.se>
(cherry picked from commit 9c5c16190158c07838dc94c80c591e3741dde640)
> Fix Stat_t.Dev/Rdev type assumption (2.2.x)

- Makefile
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
This commit adds the ability to build the client with coverage functionality
enabled. That is it downloads the 'gobinarycoverage' tool, which instruments a
regular main package source code for binary coverage analysis. This adds a
function 'coverReport()' to the main file, which reports coverage for the binary
after execution.
However, in order for this to work, the exit paths in the binary need to call
'coverReport()' before exiting. Hence, the binary is patched with the patch file
found in 'patches/', which makes sure that 'coverReport()' is called before
1) The client calls reboot
2) The client exits normally
The target added is 'instrument-binary' and is a phony target, as it does not
build the binary, it is simply a transformational step, before calling 'go
build' like normal.
Note: …
> QA-153: Add Makefile to instrument the client for cover collection

- support/modules/docker
- support/modules/single-file
The only update module to actually have any bashisms was the docker module,
and the bashisms were trivial to remove.
Changes to docker:
- Change any [[ ]] call to [ ]
- Quote any shell calls in [ -n ]
- Change the shebang from #!/bin/bash to #!/bin/sh
Changes to single-file:
- Change the shebang from #!/bin/bash to #!/bin/sh
- No other bashisms are currently present in the file.
Signed-off-by: Adam Duskett <Aduskett@gmail.com>
> Remove bashisms in the update module scripts

- .gitlab-ci.yml
- client/client_test.go
- codecov.yml
The acceptance tests are covered in mender-qa, so they are not visible
in this repo.
> QA-193: Add separate code coverage for unit and acceptance tests.

- statescript/executor.go
Script error prints might as well be diagnostics, and not necessarily errors.
Therefore, in order not to confuse the end user, log it as info.
Signed-off-by: Christian Müller <christian.muller@wifx.net>
(cherry picked from commit 943bd81f96967ed7d1c94c802e12cc1d67600209)
> MEN-3316: Log state-script stderr as info, not error

- .github/PULL_REQUEST_TEMPLATE.md
This will probably save us some of the usual grind of asking people to sign
their commits and add changelogs when they are unfamiliar with the project.
> QA-191: Add a Github PR template to help external contributors

- installer/bootenv.go
Specifically, it means using:
```
bootcount=0
```
instead of:
```
bootcount 0
```
Luckily, this is a backwards compatible change, as both the original
fw-utils based on U-Boot, as well as fw_setenv from
grub-mender-grubenv already support this syntax.
Changelog: Add support for libubootenv as boot loader user space tools
provider.
Thank you!
> MEN-3684: Switch to fw_setenv script syntax which libubootenv supports.

- client/client_test.go
- statescript/executor.go
Script error prints might as well be diagnostics, and not necessarily errors.
Therefore, in order not to confuse the end user, log it as info.
Signed-off-by: Christian Müller <christian.muller@wifx.net>
Cherry of PR: https://github.com/mendersoftware/mender/pull/521.
(cherry picked from commit d3be6dcf2e458fcfb5bc9efe6ef30856222beaba)
> [2.3] MEN-3316: Log state-script stderr as info, not error

- client/client_test.go
- statescript/executor.go
Script error prints might as well be diagnostics, and not necessarily errors.
Therefore, in order not to confuse the end user, log it as info.
Signed-off-by: Christian Müller <christian.muller@wifx.net>
Cherry of PR: https://github.com/mendersoftware/mender/pull/521.
(cherry picked from commit d3be6dcf2e458fcfb5bc9efe6ef30856222beaba)
> [2.2] MEN-3316: Log state-script stderr as info, not error 

- codecov.yml
Currently coverage is collected from the vendor folder. This coverage is quite
low, for some projects, as low as 40%. Since the vendor folder should not have
any effects on the general coverage of the project, ignore it.
This should make general coverage more reflective of what our actual coverage is.
See: https://docs.codecov.io/docs/ignoring-paths for more information.
> Fix: Ignore the coverage files in the vendor folder

- codecov.yml
This fixes one issue with codecoverage, wherein the required project coverage
would be posted after 2 finished CI-jobs. And since, our coverage is dependent
upon both unit and coverage tests, posting the coverage too early actually means
that Codecov marks the required check as failed.
This sets the number of required builds to 7. This is not a random number, but
is taken from our CI-setup for Mender. The Pipeline right now looks similar to:
1 unit-test + 6 acceptance-tests = 7
Thus Codecov will not comment, or update the coverage status until all the
coverage reports are uploaded, which will then provide a consistent coverage
report, as opposed to the premature coverage which is not posted.
> Make Codecov only update coverage after all reports are uploaded

- cli/cli.go
- cli/cli_test.go
- conf/config.go
- conf/config_test.go
Skip the Server configuration verification for mender setup. This
command will override these fields so it is not important to validate
contents of the current config beforehand.
This validation was printing warnings on first time setup for
on-boarding Rasperry Pi install.
> MEN-3652: Remove Server config warn on mender setup command

- support/mender-inventory-geo
This one fixes:
root@raspberrypi:~# /usr/share/mender/inventory/mender-inventory-geo
/usr/share/mender/inventory/mender-inventory-geo: 26: /usr/share/mender/inventory/mender-inventory-geo: Syntax error: "(" unexpected
ChangeLog:none
> mender-inventory-geo: Fixing the syntax error appearing on rpi4.

- cli/cli.go
- cli/cli_test.go
The test being removed is wrong, whether or not you specify -no-syslog
has no effect on hooks, it only affects the specific hook which is the
syslog hook. This part is tested in meta-mender on an actual device.
(cherry picked from commit ec05929c10788016e254c5f057f6eea1d0bbc20d)
> [2.3.x] MEN-3676: Fix broken logging to syslogger.

- cli/cli.go
- cli/cli_test.go
The test being removed is wrong, whether or not you specify -no-syslog
has no effect on hooks, it only affects the specific hook which is the
syslog hook. This part is tested in meta-mender on an actual device.
(cherry picked from commit ec05929c10788016e254c5f057f6eea1d0bbc20d)
> [2.2.x] MEN-3676: Fix broken logging to syslogger.

- cli/cli_test.go
This test started failing in CI after the syslog fixes due to a warning
saying when unable to connect to syslog daemon. It passes locally
because it connects to syslog with no problem.
> Fix TestIgnoreServerConfigVerification

- installer/bootenv.go
Specifically, it means using:
```
bootcount=0
```
instead of:
```
bootcount 0
```
Luckily, this is a backwards compatible change, as both the original
fw-utils based on U-Boot, as well as fw_setenv from
grub-mender-grubenv already support this syntax.
Changelog: Add support for libubootenv as boot loader user space tools
provider.
(cherry picked from commit b2507398889da5de4d859a97cf9fd8d0daf1449c)
> 2.2.x: MEN-3684: Switch to fw_setenv script syntax which libubootenv supports. 

- installer/bootenv.go
Specifically, it means using:
```
bootcount=0
```
instead of:
```
bootcount 0
```
Luckily, this is a backwards compatible change, as both the original
fw-utils based on U-Boot, as well as fw_setenv from
grub-mender-grubenv already support this syntax.
Changelog: Add support for libubootenv as boot loader user space tools
provider.
(cherry picked from commit b2507398889da5de4d859a97cf9fd8d0daf1449c)
> 2.3.x: MEN-3684: Switch to fw_setenv script syntax which libubootenv supports. 

- .gitlab-ci.yml
- cli/setup.go
```
commit 5d611a8ed98ec66ba020128ad897724590ce54ca
Date:   Thu Apr 16 16:56:01 2020
Enable Github status updates from mendertesting repository.
(cherry picked from commit adebef73d8f1e1be5412fb2a72a6d047402fe210)
commit 28e609a7e60ee210a88f770590c241d333918636
Author: Alf-Rune Siqveland <alf.rune@northern.tech>
Date:   Mon Feb 10 11:37:27 2020
Make interactive setup device type default to configured device type
MEN-3777
(cherry picked from commit 66901ffd692987749dbbc8c3c960781f26d74762)
```
> Default device type 2.2.x

- support/mender-device-identity
This fixes an issue where driver initialization happened to order
the interfaces such that dummy0 showed up before a real network
interface, resulting in an invalid identity.
These are virtual interfaces, not suitable for device identity.
It may be unusual for an embedded system (or any system, for that
matter) to include CONFIG_DUMMY in their kernel configuration, but
if it does, its MAC address shouldn't be used as a device identifier.
Signed-off-by: Matt Madison <matt@madison.systems>
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
> mender-device-identity: skip dummyX interfaces

- support/mender-client.service
Mender client startup may happen before the network is ready, so
it can't actually reach the server. It will wait its normal polling
interval to try again, but that's usually on the order of many minutes.
This change adds a weak dependency on the network-online.target and
orders itself after this target. This way, the system's regular checks
for network online will be run before the mender client starts.
Signed-off-by: Matt Madison <matt@madison.systems>
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
> mender.service: update to run after network-online.target

- store/keystore.go
- store/keystore_test.go
This simply adds a unit test for the `ed25519` signature added in #572
> Added unit tests for ED25519 signatures

- Makefile
Previously all packages matching the prefix mendersoftware/mender would be
included in the coverage report. This meant that 'mender-artifact' would be
included in the test coverage reports, which is unnecessary, considering it is a
package of its own.
> test: Only include mendersoftware/mender files in coverage 

- app/auth_test.go
- app/mender_test.go
- cli/cli_test.go
- cli/commands.go
- client/client.go
- store/keystore.go
- store/keystore_test.go
Ability to load a private key from a given engine.
* if `HttpsClient.Key` contains "pkcs11:" prefix treat it as PCKS#11 URI
* new configuration directive: `HttpsClient.SSLEngine`
* tests
* done in: https://github.com/mendersoftware/openssl/pull/17
* integration test coming with [MEN-3905](https://tracker.mender.io/browse/MEN-3905)
ChangeLog:none
(cherry picked from commit b805a45e2d8d64309d370ce75e7cc98c2378aea1)
> MEN-3871 Load private key from engine.

- tests/rootfs-image-v2
This changes the behavior of the ArtifactCommit function. Now, the variable
"upgrade_available" is verified, just like the built-in "rootfs-image",
and the commit fails if no upgrade is in progress. So, if an upgrade fails and
the user tries to commit after returning to the old OS, the commit will fail
and an appropriate message will be printed.
Signed-off-by: Pascal Hache <hacpa@touchtunes.com>
Thank you!
> Fix rootfs-image-v2 commit in standalone mode when upgrade fails

- installer/dual_rootfs_device.go
- installer/dual_rootfs_device_test.go
After a rootfs update is attempted in standalone mode and
reverted by the bootloader, a manual "commit" attempt
would report the wrong error (nothing to commit).
Now it reports the same error as the VerifyReboot state, so
the behavior is now similar in managed and standalone modes.
Signed-off-by: Pascal Hache <hacpa@touchtunes.com>
Thank you!
> Fixed wrong error produced by rootfs-image commit

- support/mender-client.service
At the moment both syntax are supported, but we will remove the -command
one on Mender 3.0, so better to start spreading the word ;)
> Use new command syntax on the service ExecStart

- .gitlab-ci.yml
- README.md
- dbus/dbus.go
- dbus/dbus_libgio.go
- dbus/dbus_libgio_helpers.go
- dbus/dbus_libgio_test.go
- dbus/dbus_test.go
Added a new package `dbus` in the source code defining an interface and
a default implementation for it (using C bindings for libgio).
Implement wrappers for the two easiest calls and add unit tests for
them.
Changelog: Add Glib's GIO dependency for D-Bus interface. It can be
opt-out using `nodbus` at compile time.
> MEN-4032: Add Glib's GIO dependency and demo integration

- installer/bootenv.go
- installer/bootenv_test.go
This change is needed to support older U-Boot versions, where the firmware tools
only support the 'key value', syntax, whereas the newer tools, and libubootenv
especially only support the '=' separator, giving 'key=value' as the only option.
This is solved through first writing to the environment using the legacy whitespace separator syntax, and then reading the variable back, to see if the operation applied a change to the environment. If it did, assume the separator to use is the legacy space separator.
> MEN-3970: Add backwards compatibility to write to old U-Boot envs

- cli/commands.go
- client/client.go
- conf/config.go
Allow to provide the key outside HttpsClient configuration section.
> MEN-3924 Allow to load private key from the Security configuration section

- client/client_update.go
This shows up in the client logs as:
2020-10-22 12:14:24 +0000 UTC error: Update fetch failed: (request_id: ): error receiving scheduled update information server error message: failed to parse server response: http: read on closed response body
Due to the prematurely closed response body.
The fix is to simply extract the error message before closing the response body.
Changelog: Correctly log the error message from the server on failed update
download attempts.
> fix: Do not close the response body before reading error message

- .gitlab-ci.yml
This is done through comparing the latest MENDER_CLIENT_VERSION from the
mender-client source, and then comparing it to the CI_COMMIT_TAG gitlab
variable, which is set to the tag of the current build.
> QA-214: Publish the 'latest' debian client package on new tags

- client/client_auth.go
Currently the log looks like this:
```
level=error msg="Failure occured while executing authorization request.
&url.Error{Op: \"Post\", URL:\"https://hosted.mender.io/...}"
level=error msg="Failure occured while executing authorization request.
&url.Error{Op: \"Post\", URL:\"https://hosted.mender.io/...}"
level=error msg="Authorization request error: dial tcp: ...."
level=error msg="Authorize failed: Transient error: Authorization request error: dial tcp: ...."
```
Where you can see the same error shows up both in logs, and in logged errors
returned from the function.
Therefore, extract information from the failure type we know, and return it.
Prettying up the logs
Changelog: Decrease the verbosity of 'Authorization requests failed' errors in
the log output.
Signed-off-by: Ole Petter …
> log: Update the log messages shown on failed authorization requests

- Makefile
- support/mender-inventory-update-modules
This simple scripts lists all the executable files found in the inventory-script
path:
/usr/share/mender/modules/*/*
Changelog: Add an inventory script for reporting the update-modules currently
installed on a device.
> Add: inventory-script for reporting installed update-modules

- .gitlab-ci.yml
This caused some confusion for an outsider reading it, so cleaning it up to be
semantically correct.
> tidy: Remove the unneeded export on PUBLISH_LATEST_CLIENT_PACKAGE

- app/mender.go
This was causing some integration tests which look for the error to
fail.
> Fix regression: Cause of error not reported when authorization fails.

- Makefile
This way, it can later on be made optional, whether or not to include the
'inventory-geo-script'.
This is followed by a separate target in meta-mender, called:
mender-inventory-geo-script, which can be added ad-hoc by a superuser which
whishes full control over his install.
This follows from the situation where we have had some issues with the
third-party provider we rely on for the geolocation data.
Changelog: The 'inventory-geo-script' now has a separate install target: 'install-inventory-geo-script'
> [inventory-geo-script]: Add a separate install target

- client/client_inventory.go
- client/client_inventory_test.go
Otherwise a new client cannot submit inventory to an old server.
> MEN-4177: Implement fallback to PATCH endpoint for inventory updates.

- app/auth.go
- app/auth_test.go
- cli/commands.go
This means we can get rid of the returned interface in the function
definition, which again allows us return the type in the constructor,
instead of the interface. Thus we can test this without a lot of
casting.
> Use getter/setter-pattern instead of return pattern to avoid casting.

- cli/commands.go
This was missed in 0e1608916bf4c. The auth service is not supposed to
be started in a go routine anymore, since this is managed internally
in the implementation now.
> Fix incorrect use of AuthManager leading to race condition.

- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
A signal handler for SIGTERM is added to the daemon run, but this is only able
to interrupt the client on the state-machine changing state. Thus operations
taking a long time, such as writing an update, are never in fact interrupted on
SIGTERM. Also, the Reboot state is stopped, due to this addition.
This can cause long shutdown times on clients in the process of writing an
update, as the client will not terminate until it has either switched state, or
worse, if it is already in the Reboot state, a SIGKILL signal needs to be sent
from the outside in order to shut it down.
This fix simply exits with Exit code 0 upon a received SIGTERM. The client is
already safe from interruptions, so this call is fine.
Changelog: Exit with code 0 on a received SIGTERM signal.
Signed-off-by: Ole Petter …
> MEN-4170: Shutdown the client on SIGTERM

- app/auth.go
- app/auth_test.go
- dbus/dbus.go
- dbus/dbus_libgio.go
- dbus/dbus_libgio_test.go
- dbus/mocks/DBusAPI.go
Update the D-Bus API replacing ValidJwtTokenAvailable Dbus signal with
a generic JwtTokenStateChange signal which carries the JWT token as a
string parameter.
> MEN-4191: generic D-Bus JwtTokenStateChange signal

- installer/bootenv.go
These messages are just too verbose for a standard run. Take this
example, just committing an artifact:
```
INFO[0000] Loaded configuration file: /var/lib/mender/mender.conf
INFO[0000] Loaded configuration file: /etc/mender/mender.conf
INFO[0000] Mender running on partition: /dev/mmcblk0p3
Committing Artifact...
INFO[0001] Committing update
INFO[0001] Probing the Bootloader environment for which separator to use ...
INFO[0001] Writing map[mender_uboot_separator:1] to the U-Boot environment ...
INFO[0003] Writing map[mender_uboot_separator:] to the U-Boot environment ...
INFO[0004] Writing map[upgrade_available:0] to the U-Boot environment ...
```
> Reduce some logging to Debug level.

- dbus/dbus_libgio.go
> Add missing stdlib.h include in dbus/dbus_libgio.go

- cli/setup.go
The problem is that the endpoint now returns an embedded JSON object
with info about the api limits, which fails to unmarshal into an object of type
map[string]string.
> MEN-4245: Fix error parsing response for getting tenant token on setup

- installer/bootenv.go
Namely, return empty strings on errors. This is not very important, as
the user will discard the return on error != nil, but helps humans to
understand the logic ;)
> probeSeparator: clean-up return values

- cli/setup.go
The problem is that the endpoint now returns an embedded JSON object
with info about the api limits, which fails to unmarshal into a
map[string]string.
(cherry picked from commit 0f69adabe1c0388dfa744e53ab6f96acb4e6a371)
> [cherry-pick] MEN-4245: Fix error parsing response for getting tenant token on setup

- app/auth.go
Since we do not have DBus activation enabled in the
`mender-client.service` file, there is no guarantee that mender-client
will grab the DBus interface first. If mender-shell happens to grab it
first, it will not get a reply to GetJwtToken, but will instead start
waiting for a state change. But unless the token has actually changed,
it will not get one if mender-client doesn't post it on startup.
Adding DBus activation in the systemd service file would also solve
the problem, but this comes with some extra complexities because the
client can also be compiled without DBus support. Rather than deal
with that, this short fix seems to solve the problem well, and also
works if the client simply crashes and comes back online.
Signed-off-by: Kristian Amlie …
> Fix DBus race condition between mender-client and mender-shell.

- LICENSE
- LIC_FILES_CHKSUM.sha256
- dbus/dbus_libgio_test.go
- dbus/dbus_test.go
- dbus/error_test.go
> MEN-4295: don't build dbus-related test files when "nodbus" tag is used

- app/auth.go
The DBus API routine is single threaded, and hence a call to
FetchJwtToken can stall the whole API if this takes a long time. For
slow connections, this is not uncommon.
Fix by moving the FetchJwtToken workload into its own Go routine.
> MEN-4294: Fix FetchJwtToken call stalling the whole DBus API. 

- app/auth.go
- app/auth_test.go
- dbus/dbus.go
- dbus/dbus_libgio.go
- dbus/dbus_libgio.go.h
- dbus/dbus_libgio_test.go
We extend the D-Bus API (GetJwtToken, JwtTokenStateChange) to return a
gvariant containing two strings: the first string contains the JWT
token, the second one the URL of the server.
> MEN-4360: Extend the D-Bus API to return the server URL

- .gitlab-ci.yml
- tests/Dockerfile.daemon
- tests/build-docker
* [Dockerfile.daemon] Update build image to Ubuntu 20.04
So that we have golang 1.13
Note that we keep the final image on Ubuntu 18.04 to avoid a very
strange issue with `COPY --from build` which seems to make /
non accessible. We'll follow up independently.
* [pipeline] Add smoke test to build Docker image
So that we can catch regressions faster.
* [tests/build-docker] Require sh instead of bash
> Improvements to Docker image

- support/mender-inventory-geo
The current script fails due to expired certificate from
'ipvigilante.com'.
There are some differences in the formatting of the
information received from the new API:
- Country now holds the shortened landcode (e.g. US for the
United States)
- There's no continent information, instead I replaced it with
geo-timezone.
ipinfo.io only supports JSON encoding in API so I had to
get creative parsing the payload using tools compatible
with Busybox. (Tested using Alpine docker image)
> Change provider in inventory-geo script to ipinfo.io

- app/standalone_test.go
- cli/setup.go
- client/client.go
- client/client_auth_test.go
- client/client_inventory_test.go
- client/client_log_test.go
- client/client_status_test.go
- client/client_test.go
- client/client_update_test.go
- conf/config.go
- conf/config_test.go
- statescript/statescript_test.go
- tests/mender-default-test.conf
By removing the underlying unused client.Config field IsHttps and
configuration field HttpsClient.
AFIACS, what happened is the following:
* mender setup saves HttpsClient (extracting it from Server URL schema)
* loaded on config.MenderConfigFromFile to set client.Config.IsHttps
* finally generating bogus HTTPS http.Client config at client.New
In any case the field is unused so safe to remove, which makes the
warnings disappear.
Changelog: Remove deprecated field HttpsClient from config file (gets
the rid of bogus SSL warnings on `mender show-artifact` and any other
cli operation).
> MEN-4398: Remove SSL warnings on empty HttpsClient config

- app/standalone_test.go
- cli/setup.go
- client/client.go
- client/client_auth_test.go
- client/client_inventory_test.go
- client/client_log_test.go
- client/client_status_test.go
- client/client_test.go
- client/client_update_test.go
- conf/config.go
- conf/config_test.go
- statescript/statescript_test.go
- tests/mender-default-test.conf
> 2.5.x: MEN-4398: Remove SSL warnings on empty HttpsClient config

- support/mender-inventory-network
This adds functionality for filtering out interfaces matching
* br-.*
* veth.*
* docker.*
by default, so that docker network interfaces do not flood the inventory on
hosts running a lot of docker containers.
If re-adding this functionality is required, set the environment variable:
* INCLUDE_DOCKER_INTERFACES=true
> MEN-4487: Filter out docker network interfaces in inventory

- app/state.go
Previously a reboot was needed in order to force-resend the inventory. This was
never discovered, as the client up until quite recently has almost always
rebooted.
The fix is dead simple, reset the in-memory storage of the last
inventory-update, which is equivalent to a reboot.
Changelog: Send the inventory after a successful deployment, even though the
device has not rebooted.
> MEN-4518: Always send inventory after a successful deployment

- app/state.go
Previously a reboot was needed in order to force-resend the inventory. This was
never discovered, as the client up until quite recently has almost always
rebooted.
The fix is dead simple, reset the in-memory storage of the last
inventory-update, which is equivalent to a reboot.
Changelog: Send the inventory after a successful deployment, even though the
device has not rebooted.
(cherry picked from commit de4aa783dc3bb6cfe82448a195b40514d4c8e32a)
Thank you!
> [Cherry 2.3.x] MEN-4518: Always send inventory after a successful deployment

- support/modules-artifact-gen/single-file-artifact-gen
(cherry picked from commit 80af399cb7c967a8a9c5fb4388ba77f4437fc461)
> MEN-4179: fix, support white spaces in single-file artifacts' names

- cli/setup.go
(cherry picked from commit ecc22acdd6342b3896da90c43a24712aa8fe8d0f)
> Fix: typo in installDemoCertificateLocalTrust

- .github/PULL_REQUEST_TEMPLATE.md
> Fix the relative path to CONTRIBUTING.md

- cli/commands.go
- cli/setup.go
- cli/setup_test.go
This is required for programs that look up certificates by their hash,
such as curl. Concatenated certificates are not supported when
creating hashed symlinks and are simply ignored by
`update-ca-certificates`.
> MEN-4580: Split demo certificate into singular pieces.

- cli/cli.go
Seems that getting the terminal width when running in an ADB shell returns 0, not an error.
This results in an infinite loop of outputting carriage returns when any help output is displayed.
Added test for positive terminal width, else falling back to normal output.
Signed-off-by: Grant Sloman <gs@violet-ultra.co.uk>
Thank you!
> Fix infinite carriage return output when running in ADB shell

- Makefile
This is out of our control, and the warning is annoying.
> Make: Ignore the 'stringop-overflow' compiler warning

- client/client.go
If skip verify is set , then we shouldnt call VerifyResult
Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>
(cherry picked from commit f50216357c64d1b96fc091ffd9793f069b38404e)
Thank you!
> Dont Verify SSL if skip verify is set

- app/state.go
- app/updatemanager.go
- app/updatemanager_test.go
Read the ticket: https://tracker.mender.io/browse/MEN-4547 *thoroughly*
Some points which is explicitly written, but from reading this and the other ticket's I don't fully understand why is needed are the complete separation of the expired maps, and the once still valid. Like why can they not simply be triggered by a boolean?
This would also help with this point:
* The expired pool must have the same primary keys and thread safety as the regular pool. 
* When UpdateControlMapExpirationTimeSeconds elapses without an update, the map is considered expired, and the map must be moved to a separate pool of expired maps.
This essentially requires monitoring of the maps in a separate goroutine, if they are required to _at all time_ be correct.
The way I've done it now is to simply check …
> MEN-4547: Implement the UpdateControlMap expiration logic

- cli/cli.go
- cli/setup.go
- conf/config.go
- conf/paths.go
Changelog: Now the device_type file is always consistent with --data flag options
Signed-off-by: Nils Olav Kvelvane Johansen <nils.olav@northern.tech>
Thank you!
> MEN-4669: Fixed issue where device_type file not consistent with -d flag

- dbus/dbus_libgio.go.h
On errors, Mender client was not finishing the handling of the D-Bus
method call, resulting in a timeout in the bus.
This is extremely unlikely to happen with currently released interface
(Authentication1), but likely to happen in future interfaces.
> MEN-4703: Fix D-Bus timeout on errors by finishing handling

- cli/cli.go
- cli/setup.go
- conf/config.go
- conf/paths.go
Changelog: The location of the device type file is now determined by the mender.conf file. If the device type file is not used in mender.conf, the device type file is determined by the --data flag and if the flag is not used, the device type file is set to default. In addition, the scripts and modules directories location is consistent with the --data flag now.
Signed-off-by: Nils Olav Kvelvane Johansen <nils.olav@northern.tech>
(cherry picked from commit c775e759c3b556a2d09d7dcd0a3d30d4713ad574)
Thank you!
> MEN-4669: Device_type_file is now consistent with -d flag & mender.conf

- app/daemon.go
- app/daemon_test.go
- app/mender.go
- app/updatemanager.go
- cli/commands.go
The heart of the issue is that the control map pool was being created
twice, and then the state logic and the update logic were working on
different pools. To remedy this, move the initialization of pool into
NewDaemon, which is really where it belongs, since it cannot be used
in non-daemon mode [1]. This allows it to be created once and used
everywhere.
One of the unit tests which tests a nil argument is invalid after this
change, so just remove it.
[1] Actually the same thing can be said for the auth manager, but
moving it has a lot more ripple effects which I don't want to deal
with right now.
> Fix Update Control Maps having no effect.

- app/updatemanager.go
This is due to the copy semantics of the Golang for loop.
Fix is real easy, just re-assign the state after modification.
> Fix: Sanitized maps are not updated in the control struct

- app/mender.go
- app/updatemanager.go
- app/updatemanager_test.go
- cli/commands.go
- main.go
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
When runDaemon() returns, the first thing that happens is that it
cleans up the resources used by the MenderDaemon structure. But if we
got a signal, we escaped runDaemon without finishing Run(), which
means this memory is still in use. This is worse than simply exiting,
because operations can be corrupted, as opposed to simply
truncated. There is no way to make this safe with the current design.
Therefore split the signal handling, so that SIGTERM is handled in
doMain, directly where we want to exit from. This means that runDaemon
can keep running without its data being destroyed.
An alternative would have been to simply call os.Exit() from the old
location, but it seemed better to keep the exit codes in one place.
Changelog: Fix occasional crash when exiting using SIGTERM. …
> Fix use-after-free issue when receiving signal.

- .gitlab-ci.yml
while working on QA-315 and to prevent costly trigger loops from appearing because of that, this switches the trigger jobs to use the gitlab native trigger functionality (which also allows easier pipeline navigation).
working triggering pipelines (two due to a limitation in the initial run, but me not being willing to run everything twice):
- https://gitlab.com/Northern.tech/Mender/mender/-/pipelines/314998079
- https://gitlab.com/Northern.tech/Mender/mender/-/pipelines/315090071
triggered pipelines (the mender-dist-packages trigger is untouched, thus not listed here):
- [mender-qa](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/315096310)
- [integration](https://gitlab.com/Northern.tech/Mender/integration/-/pipelines/315003383)
this depends on mendersoftware/mender-qa#506
> make use of gitlab triggers - relates to QA-315

- support/mender-client.service
Changelog: Fix: `mender-client.service` and the old `mender.service`
services can no longer run at the same time. If anyone has both, then
`mender.service` should be removed from the system.
> Prevent conflicting mender services from running simultaneously.

- Documentation/io.mender.Update1.xml
I also reformatted the schema documentation to increase readability
with respect to the rendered markdown output.
> [MEN-4560] Document when update_control_map.id equals deployment ID

- app/mender.go
- client/client.go
- client/client_auth.go
- client/client_inventory.go
- client/client_inventory_test.go
- client/client_log.go
- client/client_log_test.go
- client/client_status.go
- client/client_status_test.go
- client/client_test.go
- client/client_update.go
- client/client_update_test.go
Changelog: The client now supports the HTTP Device API v2.
> MEN-4785: Add support for v2/deployments/next endpoint.

- app/mender.go
- app/state.go
- app/state_test.go
- app/transition_test.go
- datastore/datastore.go
We divide the states into three groups: Update states which are not
allowed to loop, update states which are allowed to loop, and other
states (which are always allowed to loop). For update states
(`updateState`) we use the new `PermitLooping` interface to determine
whether it permits looping, for other states (`baseState`) it's enough
to know that they are not an `updateState`.
The motivation behind all this is to allow going back and forth
between states as long as at least one of them allows looping, which
will allow us to implement limitless state transitions during certain
operations in a deployment. This is important to support Update
Control, and may have other uses in the future as well (the ticket has
some useful links).
However, using the three groups of states, we *also* …
> MEN-3360: Make state trans. counter ignore certain states.

- Documentation/update-modules-v3-file-api.md
- app/standalone.go
- cli/cli.go
- cli/cli_test.go
- cli/commands.go
- tests/entrypoint.sh
On deprecated single hyphen commands, the CLI now prints and error and
exits.
Note: the previous code was also amending single hyphen flags with
double hyphen syntax. However, closer inspection to urfave/cli package
showed that both syntax are accepted for flags (for example --log-level
and -log-level are both valid). Remove that part of the amending just
for clarification (they were some flags not caught there too).
Tests modified accordingly.
And uses of flags modified also for double hyphen (both work, but we
prefer this syntax).
Changelog: CLI commands prefixed with hyphen are now deprecated, use
instead directly the command name. For example `mender daemon`, `mender
commit`, `mender show-artifact`, etc.
Additionally:
MEN-4808: Remove deprecated flag --log-modules
Which had no effect …
> MEN-4808: Deprecate single hyphen commands

- client/client.go
- client/client_test.go
In some cases the server does not return JSON data, as is advertised in the API
upon errors. Instead it simply returns an error string.
Therefore, in the cases in which the error cannot be unmarshalled to JSON, fall
back to returning the response body as a string.
An example of the error can be seen here:
```
level=error msg="Error receiving scheduled update data: (request_id: ): Invalid response received from server server error message: failed to parse server response: json: cannot unmarshal object into Go struct field .error of type string"
```
The error stems from the migration to Traefic, which does some magic rewriting
of our error responses.
> Fix: Correctly log the error response message from server errors

- client/client.go
- client/client_test.go
In some cases the server does not return JSON data, as is advertised in the API
upon errors. Instead it simply returns an error string.
Therefore, in the cases in which the error cannot be unmarshalled to JSON, fall
back to returning the response body as a string.
An example of the error can be seen here:
```
level=error msg="Error receiving scheduled update data: (request_id: ): Invalid response received from server server error message: failed to parse server response: json: cannot unmarshal object into Go struct field .error of type string"
```
The error stems from the migration to Traefic, which does some magic rewriting
of our error responses.
(cherry picked from commit 32846dd4cedad4404624b758b8869fe1d5e074a4) …
> [cherry 2.6.x] Fix: Correctly log the error response message from server errors

- client/client.go
- client/client_test.go
In some cases the server does not return JSON data, as is advertised in the API
upon errors. Instead it simply returns an error string.
Therefore, in the cases in which the error cannot be unmarshalled to JSON, fall
back to returning the response body as a string.
An example of the error can be seen here:
```
level=error msg="Error receiving scheduled update data: (request_id: ): Invalid response received from server server error message: failed to parse server response: json: cannot unmarshal object into Go struct field .error of type string"
```
The error stems from the migration to Traefic, which does some magic rewriting
of our error responses.
(cherry picked from commit 32846dd4cedad4404624b758b8869fe1d5e074a4) …
> [cherry 2.5.x] Fix: Correctly log the error response message from server errors

- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
- system/system.go
This is a followup to 26f2ccbd523932. After that commit, the output is
printed correctly, but completely without context, making it hard to
follow in logs. Since the primary purpose of having this output is
debugging, wrap it in a writer to prettify the output.
No changelog, since this is just augmenting the mentioned commit.
Thank you!
> Make command output less ugly in the log.

- app/mender.go
This removes the error log message:
```
level=error msg="Error receiving scheduled update data: (request_id: ): no deployment available"
```
when the server returns 204, no deployment available, which is not really
necessary to log as an error.
(cherry picked from commit 43e03fec1c1a5152e34c214e856f6b383977d6a1)
> Do not log an error in the case of no deployment available

- app/state.go
- app/state_test.go
- app/updatemanager.go
- app/updatemanager_test.go
In an scenario of only non-server Update Control maps, the client was
busy looping between controlMapState (aware of an active map) and
controlMapPauseState (which checked only for maps matching a given ID).
This fix makes controlMapPauseState.Handle return either a Wait(...)
when non-server maps are present or a MultiplexWait(...) when server
maps are present. In both cases, the times for waiting are HalfWay(s).
> MEN-4829: Fix busy-wait bug for only non-server Update Control Maps wait

- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
- system/system.go
Our own mender-inventory-mender-configure script for some reason logs
one byte at a time, which triggers a new long line for every
character, like this:
```
Jul 05 20:54:51 qemux86-64 mender[236]: time="2021-07-05T20:54:51Z" level=info msg="Output (stderr) from command \"/usr/share/mender/inventory/mender-inventory-mender-configure\": T"
Jul 05 20:54:51 qemux86-64 mender[236]: time="2021-07-05T20:54:51Z" level=info msg="Output (stderr) from command \"/usr/share/mender/inventory/mender-inventory-mender-configure\": o"
Jul 05 20:54:51 qemux86-64 mender[236]: time="2021-07-05T20:54:51Z" level=info msg="Output (stderr) from command \"/usr/share/mender/inventory/mender-inventory-mender-configure\": t"
Jul 05 20:54:51 qemux86-64 mender[236]: time="2021-07-05T20:54:51Z" level=info msg="Output …
```
> Revert "Make command output less ugly in the log."

- app/state.go
- app/state_test.go
- datastore/statedata.go
```
The problem stems from two separate sources:
1. The reportErrorState has long been wrong in handling errors when
the original status submitted into it was StatusSuccess. In this
case it tries to roll back. However, we can't do that, because this
state is always invoked after committing, so it's too late for
that. In fact, there is nothing we can do, and it should do the
same as all the other statuses, namely go back to the Idle
state. So there is no need for this state at all, and it has been
removed.
2. If a spontaneous reboot happens, the updateStatusReportState and
updateStatusReportRetryState states were not being handled
correctly, and the client would go down the ArtifactRollback or
ArtifactFailure path, both of which are wrong. The mentioned
StatusReport states always happen …
```
> Fix bug which caused rollback after commit if status report fails.

- app/state.go
- support/mender-inventory-network
Fixes issue with busybox where grep does not accept long flags
Changelog: mender-inventory-network: Fix incompatibility with busybox,
by using short command line options in grep command.
> MEN-4851: mender-inventory-network: Use short command line options

- app/daemon.go
- app/mender.go
- cli/setup.go
- cli/setup_test.go
- client/client.go
- conf/config.go
- conf/config_test.go
```
commit 78f1fe18be65850075f765e73cb0cf68de9cc36f
Date:   Thu Jul 8 11:36:53 2021
MEN-4857: Correct Update Control settings for `mender setup --demo`.
commit 3679422aefd35f0a64145399d8036c5d978fa6bc
Date:   Thu Jul 8 11:24:16 2021
MEN-4857: Remove more default values from generated config file.
`UpdateControlMapExpirationTimeSeconds` and
`UpdateControlMapBootExpirationTimeSeconds` should not be in the
configuration file if their values are the default values.
commit c99b16a797f9806bb0f6e710182cffa0cd567008
Author: Kristian Amlie …
```
> MEN-4857: Fix configuration issues for Update Control.

- support/mender-inventory-network
Fixes issue with busybox where grep does not accept long flags
Changelog: mender-inventory-network: Fix incompatibility with busybox,
by using short command line options in grep command.
(cherry picked from commit fc8784bff2665f80a910463444454b89a3962e48)
> 2.6.x: MEN-4851: mender-inventory-network: Use short command line options

- app/mender.go
- app/standalone.go
- app/state.go
- app/state_test.go
Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>
This PR fixes a corner case for delta updates. 
Consider a fresh device which has no device provides . 
Now when we ask for an update(`deployment/next` API) , we provide `artifact_name` as device provides by getting it from `GetCurrentArtifactName`
Now once the client gets the artifact from the server and when it comes to installing the artifact , the device calls `maybeVerifyArtifactDependsAndProvides` to ensure that the `depends` of the artifact matches with the `provides` of the device .
In such a case for a fresh device which has `no provides` in the datastore , the …
> Add artifact_name to device provides if not found in store

- support/modules-artifact-gen/docker-artifact-gen
- support/modules/docker
Signed-off-by: Uri Ishon <uri@cs-robotics.com>
Changelog: Support passing docker run CLI arguments when deploying an artifact using the `docker` _update module_.
Add support for passing command line arguments to `docker run` executed when deploying docker containers. E.g., passing ports to expose when deploying an `nginx` container. Support includes an updated `docker` _update module_ as well as an updated `docker-artifact-gen` wrapper script. Note that *all* containers will be run with the passed arguments.
> support passing docker run CLI arguments

- .gitlab-ci.yml
> [CI] Bump outdated clang-format version from 6 to 9

- installer/modules.go
Changelog: Add missing filesystem sync which could produce an empty or
corrupted Update Module file tree in
`/var/lib/mender/modules/v3/payloads/0000/tree/files/` after an
unexpected reboot.
> Add missing filesystem sync after populating Update Module's file tree.

- Makefile
- README.md
- app/daemon.go
- cli/commands.go
- conf/config.go
- dbus/dbus.go
- dbus/dbus_libgio.go
- dbus/dbus_libgio_helpers.go
- dbus/dbus_libgio_test.go
- dbus/dbus_test.go
- dbus/error.go
- dbus/error_test.go
Clients from now on will be relying on a separate authentication
manager on the D-Bus.
> MEN-5012: Remove ability to compile without glib and D-Bus support.

- app/mender.go
- app/standalone.go
- app/standalone_test.go
- app/state.go
The circumstances triggering this bug are a bit specific. There needs
to be an available artifact_name, either through the database or
through `/etc/mender/artifact_info`, the artifact must come with
"Depends" fields, and the `artifact-provides` key in the database must
exist, but contain a null value. I have not figured out the exact
steps which lead to such an `artifact_provides` value, I only know
that it must be at least somewhat rare, since we have not seen in our
tests at all. However, one of our users came across it as described in
the linked ticket. In the tests I have recreated the circumstances
artificially, since it is in any case a valid database entry.
In the described circumstances, the `provide` map is nil, but since
114df81b8bcd5, we always add artifact_name to the map, so …
> Fix crash when device has no Provides and artifact has Depends info.

- app/mender.go
- app/standalone.go
- app/standalone_test.go
- app/state.go
The circumstances triggering this bug are a bit specific. There needs
to be an available artifact_name, either through the database or
through `/etc/mender/artifact_info`, the artifact must come with
"Depends" fields, and the `artifact-provides` key in the database must
exist, but contain a null value. I have not figured out the exact
steps which lead to such an `artifact_provides` value, I only know
that it must be at least somewhat rare, since we have not seen in our
tests at all. However, one of our users came across it as described in
the linked ticket. In the tests I have recreated the circumstances
artificially, since it is in any case a valid database entry.
In the described circumstances, the `provide` map is nil, but since
114df81b8bcd5, we always add artifact_name to the map, so …
> 3.1.x: Fix crash when device has no Provides and artifact has Depends info.

- app/mender.go
- app/standalone.go
- app/standalone_test.go
- app/state.go
The circumstances triggering this bug are a bit specific. There needs
to be an available artifact_name, either through the database or
through `/etc/mender/artifact_info`, the artifact must come with
"Depends" fields, and the `artifact-provides` key in the database must
exist, but contain a null value. I have not figured out the exact
steps which lead to such an `artifact_provides` value, I only know
that it must be at least somewhat rare, since we have not seen in our
tests at all. However, one of our users came across it as described in
the linked ticket. In the tests I have recreated the circumstances
artificially, since it is in any case a valid database entry.
In the described circumstances, the `provide` map is nil, but since
114df81b8bcd5, we always add artifact_name to the map, so …
> 2.5.x: Fix crash when device has no Provides and artifact has Depends info.

- app/mender.go
- app/standalone.go
- app/standalone_test.go
- app/state.go
The circumstances triggering this bug are a bit specific. There needs
to be an available artifact_name, either through the database or
through `/etc/mender/artifact_info`, the artifact must come with
"Depends" fields, and the `artifact-provides` key in the database must
exist, but contain a null value. I have not figured out the exact
steps which lead to such an `artifact_provides` value, I only know
that it must be at least somewhat rare, since we have not seen in our
tests at all. However, one of our users came across it as described in
the linked ticket. In the tests I have recreated the circumstances
artificially, since it is in any case a valid database entry.
In the described circumstances, the `provide` map is nil, but since
114df81b8bcd5, we always add artifact_name to the map, so …
> 3.0.x: Fix crash when device has no Provides and artifact has Depends info.

- support/mender-inventory-geo
This commit fixes what 7864573db39e9b8263911ed9185ba9c018acf865 was
intended to do. The current version fetches geo location data
unconditionally, which will hit the rate limits of ipinfo.io.
FYI I wouldn't consider this PR a release blocker, but it would certainly be nice to fix this so that the geo-location script becomes usable again.
> [FIX] Fetch geo location data once per power cycle

- installer/partitions.go
Changelog: Fix error not finding active partition for systems where /dev/root is a symlink
Signed-off-by: Jesus <wjaxxx@gmail.com>
Fix an error where mender is not able to match the returned mount device with RootfsA or B. This happens in systems where /dev/root is a symlink to the actual partition
> Resolv symlink /dev/root while getting active partition

- .gitlab-ci.yml
- Makefile
- conf/paths.go
- conf/paths_local.go
- dbus/dbus_libgio.go
- dbus/dbus_libgio_helpers.go
- dbus/dbus_libgio_test.go
- dbus/dbus_test.go
- dbus/error.go
- dbus/error_test.go
- system/ioctl_linux.go
- system/ioctl_test.go
* Makefile: extend coverage target to generate junit results
And clean-up the pipeline to not run unit tests twice
* pipeline: Switch to golang 1.17
This only affects unit tests, static checks, etc. The actual building of
the binary happens either in meta-mender or mender-dist-packages, which
might have different golang versions.
> pipeline: misc improvements

- Makefile
* Make sure we post the log from the tests.
* The eval section which is supposed to capture failing tests doesn't
work, because the eval happens at parse time, so the file is empty.
Fix by doing it in shell.
> Fix several bugs in unit test reporting.

- app/proxy/proxy_ws.go
- app/proxy/proxy_ws_test.go
- client/client.go
- go.mod
- go.sum
- vendor/github.com/gorilla/websocket/client.go
- vendor/github.com/gorilla/websocket/client_clone.go
- vendor/github.com/gorilla/websocket/client_clone_legacy.go
- vendor/github.com/gorilla/websocket/conn_write.go
- vendor/github.com/gorilla/websocket/conn_write_legacy.go
- vendor/github.com/gorilla/websocket/mask.go
- vendor/github.com/gorilla/websocket/mask_safe.go
- vendor/github.com/gorilla/websocket/server.go
- vendor/github.com/gorilla/websocket/trace.go
- vendor/github.com/gorilla/websocket/trace_17.go
- vendor/modules.txt
By switching to the "enhanced" API for websocket.Dialer from
mendersoftware's fork.
There is a limitation in current gorilla/websocket.Dialer API in that
the user cannot specify a dial method for TLS/TCP connections. The TLS
handshake is always done by the library based on user's TLSClientConfig,
but that is not enough for Mender as we need it to be done via OpenSSL
(aka our dial wrapper for TLS) so that advance auth features like
getting the keys from HSM.
This commit switches to mendersoftware's fork and modifies the code
accordingly (one line change!).
The patch has been submitted upstream. See:
* https://github.com/gorilla/websocket/issues/745
* https://github.com/gorilla/websocket/pull/746
No changelog, commit 84204a3 claims to support websockets, this commit
just …
> MEN-5273: proxy: Fix websocket connection for advanced auth settings

- app/auth_test.go
Therefore give it a bit more time, but shorter intervals should keep the
responsivity of this at a level equal to or better than already existing.
> test: Unit test fails under heavy load.

- installer/bootenv.go
This provides support for using `systemd-boot` tools to managed the boot environment.  This patch is required as part of mendersoftware/meta-mender#1521
> installer/bootenv: support systemd-boot tools

- LICENSE
- LIC_FILES_CHKSUM.sha256
- patches/0001-Instrument-Mender-client-for-coverage-analysis.patch
- system/system.go
Changelog: Fix a race condition which can happen during a reboot if
systemd kills the `reboot` command before it kills the Mender client.
> MEN-5340: Fix incorrect logic if `reboot` is killed before the client.

- statescript/executor.go
Changelog: Fix a (possible) file descriptor leak.
> Make sure `/etc/mender/scripts/version` is closed after use.

- LIC_FILES_CHKSUM.sha256
- go.mod
- go.sum
- vendor/github.com/mendersoftware/mender-artifact/LICENSE
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/scripter.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/stage/stage.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/writer.go
- vendor/github.com/mendersoftware/mender-artifact/utils/attributes.go
- vendor/github.com/mendersoftware/mender-artifact/utils/progress.go
- vendor/modules.txt
Mainly to bring:
* https://github.com/mendersoftware/mender-artifact/commit/cf280f954fdc42dc5ed998fb58b9d43bc2a073ae
Changelog: Bump github.com/mendersoftware/mender-artifact to 3.6.x
> 3.0.x: Update mender-artifact library to latest 3.6.x

- LIC_FILES_CHKSUM.sha256
- go.mod
- go.sum
- vendor/github.com/mendersoftware/mender-artifact/LICENSE
- vendor/github.com/mendersoftware/mender-artifact/areader/reader.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/scripter.go
- vendor/github.com/mendersoftware/mender-artifact/artifact/stage/stage.go
- vendor/github.com/mendersoftware/mender-artifact/awriter/writer.go
- vendor/github.com/mendersoftware/mender-artifact/utils/attributes.go
- vendor/github.com/mendersoftware/mender-artifact/utils/progress.go
- vendor/modules.txt
Mainly to bring:
* https://github.com/mendersoftware/mender-artifact/commit/cf280f954fdc42dc5ed998fb58b9d43bc2a073ae
Changelog: Bump github.com/mendersoftware/mender-artifact to 3.6.x
> 3.1.x: Update mender-artifact library to latest 3.6.x

- client/client.go
- conf/config.go
ChangeLog:Allow to disable HTTP Keep-Alive from config.
goes with:
* https://github.com/mendersoftware/mender-docs/pull/1668
* https://github.com/mendersoftware/integration/pull/1921
> Disable HTTP Keep-Alive.

- Documentation/io.mender.Authentication1.xml
> Fix typo in FetchJwtToken documentation.

- app/daemon.go
- app/mender.go
- app/state.go
- app/state_test.go
- client/client.go
- client/client_inventory.go
- client/client_test.go
- client/update_resumer.go
- conf/config.go
- datastore/statedata.go
We use RetryPollIntervalSeconds in inventory with the exponential
backoff via GetExponentialBackoffTime together with a new setting:
* RetryPollCount -- the max number of tries
* inventory by default tries 3 times with one minute intervals
(GetExponentialBackoffTime defaults)
ChangeLog:commit
ChangeLog:RetryPollCount applies to all places where backoff is present
> Inventory retry.

- app/state.go
The counters were simply never reset in code. At least the `updateControl` counter can cause  some issues when the daemon is not rebooted in a long time, as you can imagine.
The inventory retry counter actually does not trigger the same kind of bug, due to the logic surrounding it, and hence does not have a `Changelog`.
> Reset `inventory` and `updateControl` retry counters when done with the retry process.

- client/client.go
Calling SSL_CTX_load_verify_locations with CAfile==NULL and CApath==NULL
will make the operation fail. This results in many eror/warning messages
in the mender-client log:
time="2022-03-01T10:11:14Z" level=error msg="Failed to Load the Server certificate. Err SSL errors: "
time="2022-03-01T10:11:14Z" level=error msg="Failed to Load the Server certificate. Err SSL errors: "
time="2022-03-01T10:11:14Z" level=warning msg="Failed to load the server TLS certificate settings: SSL errors: "
time="2022-03-01T10:11:14Z" level=warning msg="Failed to load the server TLS certificate settings: SSL errors: "
Signed-off-by: Sven Schwermer <sven.schwermer@disruptive-technologies.com>
🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONT …
> client: Avoid server certificate errors/warnings

- device/device.go
I feel like this fallback deserves a proper log mention, as the behaviour is pretty magic otherwise.
> fix: log the fallback to the artifact_info file at log level Warn

- support/mender-client.service
The mender-client service file is now explicitly ordered after the
`mender-client-data-dir` service file.
> fix: add an After systemd dependency on mender-client-data-dir

- .gitlab-ci.yml
* adding the GOLANG_VERSION variable, read by package builders
ChangeLog:none
(cherry picked from commit 16082854d3aadb785313ea257183a1c7e680b1f5)
> MEN-5459 Install go based on the source repository preferences.

- Makefile
This reverts commit b6e20f1f274e55fc09c9b0c09b5c8f9429ca2b05.
The problem with not having the optimization is that the `install-bin`
target tries to rebuild the client. This leads to several issues:
* It is incompatible with the fix for CVE-2022-24765 (see links in
changelog tag), which forbids any kind of access to a repository by
any other user than the owning one. This is problematic when
building because we use Git to determine the client version, and the
`install` target is usually invoked with `sudo`. By building
separately and then installing, this is avoided.
* Related to the above, if both the `do_compile` and the `do_install`
Bitbake targets in Yocto touch the same file, the fakeroot
mechanism can get confused. This can lead to some very hard to
detect races and "pseudo abort" …
> fix: Revert "Remove Makefile optimization to reuse old binary if source is unchanged."

- utils/progress.go
In my opinion, this is a confusing hack that [cost me a day](https://hub.mender.io/t/standalone-install-progress-does-not-represent-the-full-installation/4922) :sweat_smile:. For the story, I genuinely thought that something was happening after the copy, where actually it was still working the last percent (which takes longer on my system).
I get that the reason for the hack is to make the log look like this:
```
INFO[0000] Opening device "/dev/mmcblk0p3" for writing  
INFO[0000] Native sector size of block device /dev/mmcblk0p3 is 512 bytes. Mender will write in chunks of 1048576 bytes 
.............................................................  -  100 %
INFO[0109] All bytes were successfully written to the new partition 
INFO[0109] The optimized block-device writer wrote a total of …
```
> fix: remove confusing hack in progress bar logic

- app/process_leaking_test.go
- app/updatecontrolmap/process_leaking_test.go
- cli/process_leaking_test.go
- client/process_leaking_test.go
- conf/process_leaking_test.go
- datastore/process_leaking_test.go
- dbus/process_leaking_test.go
- device/identity_data.go
- device/process_leaking_test.go
- installer/bootenv.go
- installer/process_leaking_test.go
- inventory/inventory_data.go
- inventory/inventory_data_test.go
- inventory/process_leaking_test.go
- process_leaking_test.go
- statescript/process_leaking_test.go
- store/process_leaking_test.go
- system/testing/os_calls.go
- system/testing/process_testing.go
- utils/process_leaking_test.go
Also add a test to every package that makes sure we are not leaking
any zombies.
Ticket: MEN-5587
(cherry picked from commit 74c8c5c63ea9d08798d0a29da1da699b1ce7ba6f)
> 3.0.x: fix: Don't accumulate zombies when command output parsing fails.

- app/process_leaking_test.go
- app/proxy/process_leaking_test.go
- app/updatecontrolmap/process_leaking_test.go
- cli/process_leaking_test.go
- client/process_leaking_test.go
- conf/process_leaking_test.go
- datastore/process_leaking_test.go
- dbus/process_leaking_test.go
- device/identity_data.go
- device/process_leaking_test.go
- installer/bootenv.go
- installer/process_leaking_test.go
- inventory/inventory_data.go
- inventory/inventory_data_test.go
- inventory/process_leaking_test.go
- process_leaking_test.go
- statescript/process_leaking_test.go
- store/process_leaking_test.go
- system/testing/os_calls.go
- system/testing/process_testing.go
- utils/process_leaking_test.go
Also add a test to every package that makes sure we are not leaking
any zombies.
Ticket: MEN-5587
(cherry picked from commit 74c8c5c63ea9d08798d0a29da1da699b1ce7ba6f)
> 3.3.x: fix: Don't accumulate zombies when command output parsing fails.

- app/proxy/proxy.go
- app/proxy/proxy_test.go
- app/proxy/proxy_ws_test.go
fix: Both bind to and return over D-Bus 127.0.0.1 
At the moment we bind to localhost and we also return that as a ProxyHost. We decided it to be safer to use `127.0.0.1` in both cases.
Goes with:
* https://github.com/mendersoftware/meta-mender/pull/1704/head
Changelog: Use 127.0.0.1 both as a default bind host and ProxyHost
Ticket: None
> Bind to 127

- app/daemon_test.go
- app/state.go
- app/state_test.go
- datastore/statedata.go
In order for the spontaneous reboot recovery code to be able to
resume, we have to have recorded that we were in the
`MenderStateReboot` state when the device rebooted. This is tricky for
several reasons:
* The states that deal with Update Control are shared, so they occur
at multiple points throughout the flow, and only the ArtifactReboot
case should have this behavior.
* We have to check that the Update Control Maps do not resolve to a
"fail" before we store `MenderStateReboot`. Otherwise it could be
that the a local process requested failure and rollback, but Mender
continues anyway.
Fortunately, the Update Control states (like `controlMapState` &
friends) do not implement the `UpdateState` interface, and hence no
database state is recorded for them. We take advantage of this by …
> fix: Resume update after manually rebooting during pre-reboot pause.

- log/syslog/syslog.go
Currently, the syslog hook will trigger on all levels above the set log-level. This PR ensures that the syslog hook will also trigger at the log-level itself.
Changelog: Alll
Ticket: None
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
> fix: Append log entries to syslog at the correct level

- app/daemon.go
- app/state.go
Changelog: The client update and inventory checks are now unaffected by the use
of the `check-update` and `send-inventory` commands. While previously, this
would both move the intervals at which checks we're done, and also extend them
beyond the expected polling intervals configured.
Ticket: MEN-5547
In short:
Simplified the `checkWait` logic a lot by moving the last attempt out of the `state.go` file, and into `daemon.go`.
While maybe not completely kosher on the surface, but if you look through the code, you will realize that this does indeed simplify our somewhat fragile logic here a lot, and should now be fairly fool-proof, as opposed to previously, where it has broken for us multiple times.
I also, added an exception for the …
> fix: the periodic update check bug in checkWaitState

- app/proxy/proxy.go
- app/proxy/proxy_ws.go
Previously we would do a log.Fatalf, resulting in an exit from the client upon proxy errors.
This does not play well with our on-abort systemd service policy, meaning that the client will never be restarted upon such exits.
The fix is simple: just log an error instead.
Ticket: ME-3
> Do not exit the client binary on proxy errors, and cancel the dials on stopping the server

- support/keygen-client
[Docs preauth flow](https://docs.mender.io/server-integration/preauthorizing-devices#generate-a-client-keypair) fails if openssl 3 is used.
Signed-off-by: Alan <alan.martinovic@northern.tech>
> fix: Expand the check for new openssl version

- Documentation/io.mender.Authentication1.xml
- Documentation/io.mender.Update1.xml
In order to access the D-Bus API, the already documented interface path is not sufficient. Add the missing pieces of information:
- connection name
- object name
Ticket: None
Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>
> fix: add missing d-bus path documentation

- tests/Dockerfile.daemon
This reverts commit 9e0a11aead94c6cee32a530ec34f7e7bcd9480ca.
Seems to be a problem in CI building this image. Revert the upgrade for now to unblock other work and follow-up independently.
> chore: Revert "chore(tests/Dockerfile.daemon): Update base image to Ubuntu 22" 

- support/mender-client.service
The reason we didn't do this originally was to make the unit show up as "failed" when encountering permanent errors. "Permanent errors" are essentially "all regular exit codes", but not signals. However, because we handle most signals and return an exit code for those too, it does not always work well in certain scenarios, one of them being the OOM killer, which may try to use SIGTERM before SIGKILL. In this case the client would stay dead, even though we should try to relaunch it.
It appears that systemd does consider the unit failed if it restarts often enough, which will happen when there's a permanent error. Therefore we don't need to keep it dead at all, and can just restart it always, which is anyway a good safety net to have.
Ticket: ME-33
Signed-off-by: Kristian …
> fix: systemd: Always try restarting the client if it exits.

- installer/bootenv.go
This was motivated by customer confusion saying that they are using grub and not u-boot after getting the error:
`Failed to probe the U-Boot environment for which separator to use. Got error: exit status 2"`
Ticket: None
Signed-off-by: Alan <alan.martinovic@northern.tech>
----
@kacf 
I did it as a cheap fix not far away from `/s/U-Boot/bootloader/g`
If some actions are really U-boot specific please correct.
> chore: Replace u-boot with booloader in the logs

- app/mender_test.go
- app/proxy/proxy_ws_test.go
- client/client.go
- client/test/http_proxy.go
- go.mod
- go.sum
- vendor/github.com/mendersoftware/openssl/net.go
- vendor/modules.txt
Two commits:
fix: websocket connectivity through http-proxy if configured
Enables websocket connections to be established through an http-proxy configurable by setting the `HTTPS_PROXY` environment variable. This renders services that relies on websocket connections, such as `mender-connect`, compatible with http-proxying.
Changelog: All
Ticket: ME-5
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
`---`
fix: client not to skip custom TLS if an http-proxy is configured
Previously, Mender client supported http-proxying but ignored custom TLS client configuration if present. This change renders any custom TLS configurations, such as Mutual TLS, compatible with http-proxying.
Changelog: All
Ticket: MEN-6009
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
> ME-5 and MEN-6009: http-proxy fixes

- support/mender-client.service
The reason we didn't do this originally was to make the unit show up as "failed" when encountering permanent errors. "Permanent errors" are essentially "all regular exit codes", but not signals. However, because we handle most signals and return an exit code for those too, it does not always work well in certain scenarios, one of them being the OOM killer, which may try to use SIGTERM before SIGKILL. In this case the client would stay dead, even though we should try to relaunch it.
It appears that systemd does consider the unit failed if it restarts often enough, which will happen when there's a permanent error. Therefore we don't need to keep it dead at all, and can just restart it always, which is anyway a good safety net to have.
Ticket: ME-33
Signed-off-by: Kristian …
> 3.4.x: fix: systemd: Always try restarting the client if it exits.

- support/mender-client.service
The reason we didn't do this originally was to make the unit show up as "failed" when encountering permanent errors. "Permanent errors" are essentially "all regular exit codes", but not signals. However, because we handle most signals and return an exit code for those too, it does not always work well in certain scenarios, one of them being the OOM killer, which may try to use SIGTERM before SIGKILL. In this case the client would stay dead, even though we should try to relaunch it.
It appears that systemd does consider the unit failed if it restarts often enough, which will happen when there's a permanent error. Therefore we don't need to keep it dead at all, and can just restart it always, which is anyway a good safety net to have.
Ticket: ME-33
Signed-off-by: Kristian …
> 3.3.x: fix: systemd: Always try restarting the client if it exits.

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
Propagate the software versioning opts to the mender-artifact command. Before this commit, the options were swallowed and ignored.
Ticket: MEN-6026
I discovered this issue when working on https://github.com/mendersoftware/mender-demo-artifact/pull/220
> fix: do not ignore software versioning opts in the module artifact gens

- app/daemon_test.go
This fixes the race-condition in the DaemonRun test through allowing the
UpdateCheckCount to be one higher than currently allowed.
The reason for adding this is that the update check is actually really close to
being triggered 6 times. If you look at the timeline below:
0  1  2  3  4  5
|--|--|--|--|--|-
u1 u2 u3 u4 u5 u6
i1 i2 i3 i4 i5 i6
Here you can see that the update should really be sent 6-times, if the client is
fast, and the tests are a little bit slow.
In fact, it is really easy to trigger locally, by making the test-thread a
little bit slower with the added sleep:
```
time.Sleep(time.Duration(timespolled)*pollInterval + time.Duration(10)*time.Millisecond)
```
Then, you will get 6 update check attempts every time locally. …
> test: fix the race-condition in the DaemonRun unit test

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
Propagate the software versioning opts to the mender-artifact command. Before this commit, the options were swallowed and ignored.
Ticket: MEN-6026
(cherry picked from commit cbefdcc1b6c9322149f4741179568bcc469359db)
> 3.3.x: fix: do not ignore software versioning opts in the module artifact gens

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
Propagate the software versioning opts to the mender-artifact command. Before this commit, the options were swallowed and ignored.
Ticket: MEN-6026
(cherry picked from commit cbefdcc1b6c9322149f4741179568bcc469359db)
> 3.4.x: fix: do not ignore software versioning opts in the module artifact gens

- support/mender-client.service
Since systemd v213, `journald` symlinks `/dev/log` to point to itself. The syslogger in mender-client is configured by default to forward log messages to `/dev/log`. `journald` will receive duplicate log messages; one from `/dev/log` and one from `stdout`.
Changelog: Add `--no-syslog` to the service file to ensure no duplicate log messages in the journal.
Ticket: MEN-6070
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
> fix: duplicate journald log entries in some systemd configurations

- support/mender-inventory-hostinfo
Signed-off-by: Luis Ramirez Vargas <luis.ramirez@northern.tech>
By using `cat` you will print the comments in the file, while the actual command ignore them, if a user has in `/etc/hostname`:
```bash
#Any comment
actualHostName
```
The script will fail. Even busybox has the `hostname` command available
Thank you!
> change mender-inventory-hostinfo to use the output of hostname

- Makefile
- lib.cpp
* Introduce "fake" missed coverage. The resulting number (75%) is closer to what we actually have in the client.
* Omit "_test.*" files from coverage report.
* Test something which is in a "production" source file.
> feat: Extend the coverage support a little bit.

- tests/entrypoint.sh
The docker-client has no syslog to write to as there is no daemon listening.
Simply disable writing it.
> test(docker-client): Do not write to the syslog

- CONTRIBUTING.md
Otherwise it creates an empty file because the URL returns 302 and a different location. Feels like it is more future-proof to use -L here than the target URL directly.
Ticket: None
Signed-off-by: Vratislav Podzimek <vratislav.podzimek@northern.tech>
> fix: Tell curl to follow redirects when downloading .clang-format

- LICENSE
- LIC_FILES_CHKSUM.sha256
- app/standalone.go
- app/standalone_test.go
- cli/cli_test.go
- cli/commands.go
- conf/config.go
- device/device.go
- installer/dual_rootfs_device.go
- installer/dual_rootfs_device_test.go
- installer/installer.go
- installer/installer_test.go
https://hub.mender.io/t/multiple-artifactverifykeys/4309/6
Creates a new client config parameter called ArtifactVerifyKeys that is a list of paths to keys. Any matching key can be used to verify an artifact - e.g. if 5 verification keys are provided, only 1 needs to match to verify the artifact.
This is version 2, see https://github.com/mendersoftware/mender/pull/1045 for previous discussions.
Signed-off-by: Michael Ho <callmemikeh@gmail.com>
> feat: Support multiple verifications keys

- app/proxy/proxy.go
- app/proxy/proxy_ws.go
Now the proxy logger stands out in the logs more, and can thus be filtered easier with tools parsing structured logs. This means that a log line from the `proxy` thread goes from looking like:
```
Oct 05 08:50:06 qemux86-64 mender[259]: time="2022-10-05T08:50:06Z" level=error msg="error forwarding from client to backend: websocket: close 1006 (abnormal closure): unexpected EOF"
```
To:
```
Oct 05 08:50:06 qemux86-64 mender[259]: time="2022-10-05T08:50:06Z" level=error thread="proxy" msg="error forwarding from client to backend: websocket: close 1006 (abnormal closure): unexpected EOF"
```
Ticket: None
> feat(logger): Add a thread: <proxy> field to the proxy logger

- .gitignore
- .gitlab-ci.yml
- CMakeLists.txt
- common/CMakeLists.txt
- common/log.hpp
- common/log/platform/boost/boost_log.cpp
- common/log_test.cpp
- config.h.in
- mender-auth/CMakeLists.txt
- mender-update/CMakeLists.txt
- mender-update/main.cpp
- tests/Dockerfile.daemon
This is my initial attempt at the structured logger interface.
I know it is probably rough, but at least it's in a working state now. Example output:
```console
record_id=1 severity=info time="2023-Jan-10 15:02:23.770474" name="Test" msg="Test log"
record_id=2 severity=error time="2023-Jan-10 15:02:23.771073" name="Foo" foo="bar" bar="baz" msg="Some error"
record_id=3 severity=info time="2023-Jan-10 15:02:23.771282" name="Test" msg="Some info message"
record_id=4 severity=debug time="2023-Jan-10 15:02:23.771475" name="Test" msg="I should show test"
```
Obviously rough, and can/should be changed, but I think you get the jist of it.
Currently in order to add fields to your log record you need to call the `withFields` method. The reason for this is that in boost attributes have to be added …
> Initial logging library implementation

- support/mender-inventory-os
- tests/rootfs-image-v2
Changelog: Replace obsolescent `egrep` with `grep -E` in inventory script
(cherry picked from commit 75b0acb07c972f5ba4f40b4b221f4a0f1b342b09)
> chore: egrep is obsolescent; use grep -E

- common/io.hpp
This adds an io::Reader utility to wrap regular cpp streams, as seen in the PR: https://github.com/mendersoftware/mender/pull/1141
> feat: Add io stream reader

- common/CMakeLists.txt
Instead of requiring everything linking with common_config_parser to explicitly link with common_json too.
Ticket: None
> fix: Link common_config_parser with common_json

- common/log.hpp
- common/log/platform/boost/boost_log.cpp
- common/log_test.cpp
Leftover fix from the logger, and one cleanup
* Now loggers no longer interfere with eachothers log-levels, as the filtering is done in each logger.
* Chore: Removed the standard log-level setting in Setup, as this is already done when constructing the class.
> Fix logger levels

- common/expected.hpp
This adds a few methods to align our `mender::expected` library to align closer with the standard librarys `expected` implementation.
The commits should contain most the information needed.
> expected lib alignments with the standard library

- artifact/sha/platform/openssl/sha.cpp
Amazing that it still compiled! It does not compile with -Wall though.
Ticket: None
> fix: Add missing `case` keywords.

- common/CMakeLists.txt
- common/conf.hpp
- common/conf/conf.cpp
- common/conf/paths.hpp
- common/conf/platform/boost_filesystem/paths.cpp
- common/conf_test.cpp
- mender-update/CMakeLists.txt
- mender-update/main.cpp
Default paths in mender::common::conf::paths and
mender::common::conf:GetEnv() for getting values of environment variables with a fallback (default) value.
Ticket: MEN-6313
> feat: Add default paths and environment handling

- CMakeLists.txt
- artifact/sha/CMakeLists.txt
- common/CMakeLists.txt
- common/config_parser.hpp
- common/config_parser/config_parser.cpp
- common/json/json.cpp
- common/key_value_database/in_memory/in_memory.cpp
- mender-auth/CMakeLists.txt
- mender-update/CMakeLists.txt
Because flags are inherited from other libraries when you link to them, this does not work well for conflicting flags. Instead, introduce a default for all components, and then override using `target_compile_options`, which always puts the flags last.
Ticket: None
> fix(cmake): Avoid inheriting conflicting flags from static libs.

- .gitmodules
- CMakeLists.txt
- LIC_FILES_CHKSUM.sha256
- artifact/sha/platform/openssl/sha.cpp
- common/config_parser.hpp
- common/config_parser/config_parser.cpp
- common/expected.hpp
- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/inventory_parser/platform/boost_filesystem/inventory_parser.cpp
- common/io.hpp
- common/io_test.cpp
- common/json.hpp
- common/json/platform/nlohmann/nlohmann_json.cpp
- common/key_value_database/in_memory/in_memory.cpp
- common/key_value_database/platform/lmdb/lmdb.cpp
- common/key_value_parser.hpp
- common/key_value_parser/key_value_parser.cpp
- common/processes.hpp
- mender-update/main.cpp
This PR replaces our internal std::expected implementation with an existing project. More closely:
```
https://github.com/TartanLlama/expected
```
This fully replaces our implementation, while giving us access to the modern monadic extensions, which can help reduce the overhead surrounding our expactation handling.
See the link for more information.
> Replace the internal expected implementation with an existing lib

- artifact/CMakeLists.txt
- artifact/v3/version/CMakeLists.txt
- artifact/v3/version/version.cpp
- artifact/v3/version/version.hpp
- artifact/v3/version/version_test.cpp
This adds a simple parser for the Mender-Artifact v3 version header.
As well as a small utility ByteWriter class to io.
I do have to admit that I feel this turned out needlessly complicated, so all open for advice on how to improve this!
> (artifact-parser): Add the Version header parser

- artifact/v3/version/version.cpp
- artifact/v3/version/version.hpp
- artifact/v3/version/version_test.cpp
This was missed during the initial implementation and review.
> chore(artifact): Add the version parser to the mender namespace

- artifact/CMakeLists.txt
- artifact/error.cpp
- artifact/error.hpp
- artifact/v3/manifest/CMakeLists.txt
- artifact/v3/manifest/manifest.cpp
- artifact/v3/manifest/manifest.hpp
- artifact/v3/manifest/manifest_test.cpp
- common/io.cpp
- common/io.hpp
This adds the initial manifest parser implementation for the Mender-artifact format parser.
> Add the manifest parser implementation

- artifact/CMakeLists.txt
- artifact/v3/payload/CMakeLists.txt
- artifact/v3/payload/payload.cpp
- artifact/v3/payload/payload.hpp
- artifact/v3/payload/payload_test.cpp
This adds the payload parser implementation.
Interface:
```
payload::Verify(io::Reader) -> Reader
```
The payload is itself offering a Reader, and will automatically verify the
payload checksum upon write, and if the checksum does not match, will throw an
error at the end of the write.
Interface:
```
p = Payload.Next()
.Read() -> expectedSize
```
Ticket: MEN-6205
> Artifact Payload parser implementation

- .gitlab-ci.yml
- artifact/CMakeLists.txt
- artifact/lexer.hpp
- artifact/parser.cpp
- artifact/parser.hpp
- artifact/parser_test.cpp
- artifact/token.hpp
Adds the top-level Artifact parser structure.
Usage:
```
a = artifact::Parse(io::Reader &reader)
a.version
a.x
.
.
.
payload = a.Next()
```
Ticket: MEN-6200
> feat(artifact): Add the top-level parser structure

- common/json.hpp
- common/json/platform/nlohmann/nlohmann_json.cpp
- common/json_test.cpp
An elementary function allowing iteration over JSON object's children, other functions can be easily built on top of this one.
Ticket: none
> feat: Introduce Json::GetChildren()

- .gitmodules
- CMakeLists.txt
- LIC_FILES_CHKSUM.sha256
This adds an optional library to vendor. The library is fully compatible with C++17's optional implementation, when built under C++11, which should suit us well.
Added a simple example to the auth binary, to examplify it's use.
Ticket: None
> feat(vendor): Add an optional library

- common/context.hpp
- common/context/context.cpp
Adding basic set of DB keys as constants into the MenderContext class and cleanup of unused keys from the DB as part of MenderContext::Initialize().
Ticket: MEN-6308
> feat: Basic DB keys and vacuuming

- common/json_test.cpp
Rebase caused a mismatch between LoadFromString() replaced by overloaded Load() and GetChildren() being introduced.
Ticket: none
> fix: Fix json GetChildren() test

- CMakeLists.txt
- common/CMakeLists.txt
- common/http_test.cpp
It helps readability by knowing where overrides are, and can also prevent mistakes in cases where an override is unintentional.
> chore: Enforce use of `override` everywhere where it is appropriate.

- artifact/CMakeLists.txt
- artifact/config.hpp
- artifact/lexer.hpp
- artifact/parser.cpp
- artifact/parser.hpp
- artifact/parser_test.cpp
- artifact/token.hpp
- artifact/v3/header/CMakeLists.txt
- artifact/v3/header/header.cpp
- artifact/v3/header/header.hpp
- artifact/v3/header/header_info.cpp
- artifact/v3/header/header_test.cpp
- artifact/v3/header/token.hpp
- artifact/v3/header/type_info.cpp
- artifact/v3/manifest/manifest.cpp
- artifact/v3/manifest/manifest.hpp
- artifact/v3/manifest/manifest_test.cpp
- common/io.cpp
- common/io.hpp
- common/json.hpp
- common/json/json.cpp
- common/optional.hpp
Implementation of the header-parser, minus the meta-data parsing, which will be handled as a follow-up in https://northerntech.atlassian.net/browse/MEN-6424.
For now it's directly importing the `vendor/expected` lib, but I will move this out into our own wrapper in a separate PR in parallel, and then rebase on top of it.
> Header parser impl

- CMakeLists.txt
- artifact/CMakeLists.txt
- artifact/sha/CMakeLists.txt
- artifact/tar/CMakeLists.txt
- artifact/v3/header/CMakeLists.txt
- artifact/v3/manifest/CMakeLists.txt
- artifact/v3/payload/CMakeLists.txt
- artifact/v3/version/CMakeLists.txt
- common/CMakeLists.txt
- common/events_io_test.cpp
- common/log/platform/boost/boost_log.cpp
- common/log_test.cpp
- common/main_test.cpp
- mender-update/CMakeLists.txt
This means we can call setup and teardown functions for the entire test framework.
For now we only set the log-level to `Trace` for all the tests.
I also did some minor fixes to the logger, feel free to reject any of these at will. I can also move it to a separate PR if you want.
> Add a mender::common::main_test loop

- artifact/CMakeLists.txt
- artifact/artifact.cpp
- artifact/artifact.hpp
- artifact/v3/header/CMakeLists.txt
- artifact/v3/header/header.cpp
- artifact/v3/header/header.hpp
- artifact/v3/header/header_test.cpp
- artifact/v3/header/meta_data.cpp
- common/config_parser/config_parser.cpp
- common/expected.hpp
- common/json.hpp
- common/json/platform/nlohmann/nlohmann_json.cpp
- common/json_test.cpp
- mender-update/update_module/v3/update_module.hpp
- mender-update/update_module/v3/update_module_test.cpp
This adds the meta-data parser from MEN-6424, as well as a few touches to our Json implementation, notably:
* Fix: Align the `GetInt` function with the underlying Nlohmann integer representation
* feat: Json::GetDouble
Note, this is based on top of https://github.com/mendersoftware/mender/pull/1203 so feel free to ignore those commits obviously :)
> Header metadata parser

- artifact/error.hpp
- artifact/parser.cpp
- artifact/parser.hpp
- artifact/parser_test.cpp
- artifact/v3/payload/CMakeLists.txt
- artifact/v3/payload/payload.cpp
- artifact/v3/payload/payload.hpp
- artifact/v3/payload/payload_test.cpp
This adds support for reading multiple files from each payload.
The solution is just an extension of the existing `Next()` interface, so that
now:
```
artifact::Parse() -> artifact
artifact.Next() -> Payload
Payload.Next() -> payload::Reader
...
Payload.Next() -> NoMorePayloadFilesError
```
Hence, each payload, and each file in the given payload can be processed in
turn.
The reader verifies the checksum of the given file as it is consumed, and
returns an error if there is a checksum mismatch.
The `payload::Reader` also has accessors for getting the `filename` and the
`size` of the given file.
Ticket: MEN-6452
> feat(artifact/payload): Support multiple files read in each payload

- artifact/artifact.cpp
- artifact/artifact.hpp
- artifact/config.hpp
- artifact/v3/header/header.hpp
- artifact/v3/header/header_test.cpp
- mender-update/update_module/v3/update_module.hpp
- mender-update/update_module/v3/update_module_test.cpp
`parser::` should not be exposed outside of the artifact:: namespace. Hence we alias the `parser::Artifact`, and wrap the `Next` method, to provide the top-level interface in `artifact`.
> refac(artifact): Add the Parse interface to the toplevel artifact::

- artifact/parser_test.cpp
- artifact/v3/payload/payload.cpp
- artifact/v3/payload/payload_test.cpp
Quick fix for the bug with the payload name.
I simply hard-coded the name. We do not support multiple payloads at the moment anyways.
> Fix artifact payload name bug

- artifact/tar/platform/libarchive/tar.cpp
> fix(tar): Narrowing conversion from la_int_64_t to ssize_t

- CMakeLists.txt
This can be overridden by the option:
MENDER_BOOST_DYN_LINK=OFF
> build(boost): Dynamically link Boost by default

- artifact/tar/CMakeLists.txt
According to the documentation:
https://cmake.org/cmake/help/latest/module/FindLibArchive.html
The LibArchive::LibArchive call is added in CMake v3.17.
Since Ubuntu Focal, have 3.16 available, this will not link properly.
Ticket: MEN-6395
```
```
Thank you!
> build(ubuntu-focal): Remove CMake v3.17 import libarchive target

- common/http/platform/beast/http.cpp
- common/http_test.cpp
The AWS Loadbalancer will not route requests to our k8s cluster unless the `HOST` header is set in the request.
Therefore, this fix sets the header for all outgoing HTTP requests.
Ticket: None
> fix(http): Set the HOST header for all HTTP requests

- common/io.hpp
- common/io_test.cpp
A follow-up to bc4061daf8b725db94433227a11d00e46d89bc05 and 1bb88cdf8007a162b8a8ec3ae668f4b1a0c1b34c that added constructors from shared pointers passed by reference. If we capture shared pointers by copy, they cannot be passed further as references and thus we need constructors from shared pointers passed by value. However, having both variants (value and reference) makes the constructors ambiguous so we have to only provide the by-value constructors.
Ticket: MEN-6494
> chore: Construct IO objects from shared_ptr passed by value

- common/http.hpp
- common/http/platform/beast/http.cpp
> fix: Don't crash if the handler owns `Client` by capture.

- common/processes.hpp
- common/processes/platform/tiny_process_library/tiny_process_library.cpp
If the process finishes so quickly that `SetupAsyncWait` completes before the caller has a chance to call `AsyncWait`, then the handler is never called. With this commit, this scenario is detected and the handler is scheduled right away if we find that the process has already ended.
This showed up on my system occasionally as a very rare hang in the Update Module state calls tests.
Ticket: None
> fix: Fix race condition in AsyncWait for quick processes.

- .gitlab-ci.yml
- support/modules-artifact-gen/tests/deb-requirements.txt
This is based on libssl3, and is therefore incompatible with the downloadable mender-artifact. The package for Ubuntu 22.04 is however compatible, so use that as an image instead.
> test: Work around Python:3.10 base image upgrade to Debian:12 (bookworm)

- mender-update/standalone.hpp
- mender-update/standalone/standalone.cpp
This was not caught because two branches conflicted only when merged with each other.
> chore: Follow rename and other refactorings.

- common/CMakeLists.txt
The real name is `Boost_INCLUDE_DIRS` with the trailing `S`.
The singular is a cache variable.
See the documentation for more.
```
```
Thank you!
> build(boost): Fix the Boost find_package variable

- mender-update/deployments.cpp
- mender-update/deployments.hpp
- mender-update/deployments_test.cpp
- mender-update/inventory.cpp
- mender-update/inventory.hpp
- mender-update/inventory_test.cpp
Doing this is unnecessary because the `AsyncCall()` that it performs is already an asynchronous call which will be posted on the event loop, so there is no need to post twice. This has the convenient side effect of getting rid of the `EventLoop` argument.
Also add error handling for the `AsyncCall()`, which was missing, and remove the loop argument from many API functions that don't actually use it.
> chore: Remove unneeded `EventLoop::Post` in `CheckNewDeployments`.

- .gitlab-ci.yml
- app/state.go
- support/modules-artifact-gen/tests/deb-requirements.txt
3.3.x is failing: https://gitlab.com/Northern.tech/Mender/mender/-/pipelines/943410534
```
app/auth.go:266:15: undefined: timers
app/auth.go:279:5: undefined: timers
app/auth.go:295:15: undefined: timers
app/auth.go:304:5: undefined: timers
app/auth.go:413:16: undefined: timers
app/auth.go:418:6: undefined: timers
app/auth.go:476:13: undefined: timers
app/auth.go:481:3: undefined: timers
make: *** [Makefile:85: mender] Error 1
```
Ticket: None
> chore: 3.3.x compilation fixes

- common/json.hpp
- common/json/json.cpp
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
- mender-update/daemon/states.hpp
```
commit 315039fa825552ee06f56c73b8330050e5c09eae
Date:   Wed Jul 19 14:31:49 2023
chore: Add database keys for saved update states.
commit 96b4df4ca19c153faebc4d52233dfbe8690523c4
Date:   Wed Jul 19 13:13:54 2023
chore: Make deployment state data load/save functions.
Ticket: MEN-6565
commit b2b54ee66d2203125bf7c459c11c90557de5b308
Date:   Wed Jul 19 12:41:39 2023
chore: Add more `json::To*` functions, for use in monadic expressions.
```
> State saving functions

- common/log/platform/boost/boost_log.cpp
- common/state_machine.hpp
This was discussed with the team members. Since an unhandled event is
almost guaranteed to hang the state machine, then it's better to
terminate and let systemd try to restart us, in the hopes that
recovery will still work.
> chore: Treat events with no state transitions as fatal.

- common/inventory_parser/platform/c++17/inventory_parser.cpp
Nicer syntax and one line shorter!
Ticket: none
> chore: Use a range-based for loop on a directory iterator in inventory parser

- common/crypto/platform/openssl/crypto.cpp
- common/crypto_test.cpp
Since the OpenSSL errors are stored in a queue, and harvested in a FIFO like fashion, it is important that we do harvest the messages upon every call which fails, otherwise the extraction will generate the wrong error messages.
> chore(crypto): harvest the OpenSSL error message for all failed calls

- artifact/tar/platform/libarchive/wrapper.hpp
- common/conf.hpp
- common/error.hpp
- common/events/events_io.cpp
- common/events/platform/boost/events_io.cpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/io.hpp
- common/key_value_database/in_memory/in_memory.cpp
- common/key_value_database/platform/lmdb/lmdb.cpp
- common/log.hpp
- common/log/platform/boost/boost_log.cpp
- common/processes/platform/tiny_process_library/tiny_process_library.cpp
- common/testing.cpp
- common/testing.hpp
- mender-update/cli/actions.hpp
- mender-update/context.hpp
- mender-update/update_module/v3/platform/c++17/fs_operations.cpp
- mender-update/update_module/v3/update_module.cpp
Where possible, leaving the more explicit calls to other constructors with parenthesis.
> chore: Consistently use curly braces initialization in constructors

- api/auth.hpp
- mender-update/context/context.cpp
- mender-update/context_test.cpp
* chore: Remove unused declaration `GetPrivateKey`
* fix: Support parsing device_type with no endl at the end
As currently formatted by `mender setup` from the golang client
> fix: Support parsing device_type with no endl at the end

- .gitignore
```
```
Added `build/` to `.gitignore` in order to provide the means for my favourite command `git add .`.
> Added `build/` to `.gitignore`

- common/http/platform/beast/http.cpp
Instead of auto-cancelling the first one, which is quite confusing to debug.
> chore: Produce error message when trying to call two endpoints at once.

- common/common.hpp
- mender-update/CMakeLists.txt
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/context_test.cpp
Using a helper function ArtifactMatchesContext() to make testing
easier.
Ticket: MEN-6511
> feat: Add MenderContext::MatchesArtifactDepends()

- common/common.hpp
- mender-update/context.hpp
- mender-update/context/context.cpp
- mender-update/context_test.cpp
Actually done in the ArtifactMatchesContext() helper function which needs to check values from artifact::HeaderView::type_info (if any).
Also handle cases when `artifact_group` is missing in the local provides data gracefully (the value is not required to be present).
Ticket: MEN-6511
> chore: Respect type info depends in MenderContext::MatchesArtifactDepends()

- api/client.hpp
- mender-update/daemon/state_machine.cpp
- mender-update/daemon/state_machine.hpp
- mender-update/daemon/states.cpp
- mender-update/daemon/states.hpp
While we don't test a scenario with broken credentials exactly, it is indirectly tested because what would happen is that the status update would fail. This is already tested in other ways, so let's leave it at that.
Ticket: MEN-6582
> chore: Expire token before committing, so that credentials are verified.

- tests/Dockerfile.daemon
Previously used Ubuntu 20.04 uses golang 1.13 which is very old at this point. Ubuntu 22.04 runs golang 1.18.
This image is for internal use only and should not be the blocker for dependencies updates.
> chore: Update base image for `mender-client-docker`

- mender-auth/CMakeLists.txt
- mender-auth/cli/CMakeLists.txt
- mender-auth/cli/actions.cpp
- mender-auth/cli/actions.hpp
- mender-auth/cli/cli.cpp
- mender-auth/cli/cli.hpp
Require `daemon` argument to actually run the daemon, and produce
failure when no argument is given.
Ticket: MEN-6639
> chore: Fix mender-auth CLI interface.

- mender-update/daemon/state_test.cpp
It was failing submitting inventory, which is not that odd.
> test(state): Fix the failing DeploymentLogging test

- api/CMakeLists.txt
- api/auth_test.cpp
- api/client_test.cpp
- artifact/sha/CMakeLists.txt
- artifact/sha/sha_test.cpp
- artifact/v3/manifest/CMakeLists.txt
- artifact/v3/manifest/manifest_test.cpp
- artifact/v3/manifest_sig/CMakeLists.txt
- artifact/v3/manifest_sig/manifest_sig_test.cpp
- artifact/v3/payload/CMakeLists.txt
- artifact/v3/payload/payload_test.cpp
- common/CMakeLists.txt
- common/config_parser_test.cpp
- common/identity_parser_test.cpp
- common/inventory_parser_test.cpp
- mender-auth/ipc/CMakeLists.txt
- mender-auth/ipc/server_test.cpp
- mender-update/CMakeLists.txt
- mender-update/context_test.cpp
- mender-update/daemon/state_test.cpp
Many tests had the header and include path while only using GTest.
Completely unnecessary clean-up...
> chore: Clean-up `gmock` use in tests

- common/events.hpp
- common/events/platform/boost/events.cpp
- common/events/platform/boost/events_io.cpp
- common/events_io.hpp
- common/events_io_test.cpp
- common/events_test.cpp
- common/http.hpp
- common/http/http.cpp
- common/http/platform/beast/http.cpp
- common/http_test.cpp
- common/processes.hpp
- common/processes/platform/tiny_process_library/tiny_process_library.cpp
- common/processes_test.cpp
- mender-update/update_module/v3/platform/c++17/fs_operations.cpp
- mender-update/update_module/v3/update_module.cpp
- mender-update/update_module/v3/update_module.hpp
- mender-update/update_module/v3/update_module_test.cpp
This should "fix" most `Cancel()` calls to return `operation_canceled` in their handlers, unless it is during destruction.
One notable omission is the signal handlers. Boost does produce an error even in this case, but because a signal handler is installed permanently, and does not wait for any specific event, it seems more acceptable to not call them with `operation_canceled`. And the handlers are not taking errors in their arguments currently, so it would need to change the call sites.
> Cancel() triggers "operation canceled"

- artifact/v3/scripts/executor.cpp
- artifact/v3/scripts/executor.hpp
- mender-update/CMakeLists.txt
- mender-update/daemon/context.cpp
- mender-update/daemon/state_events.hpp
- mender-update/daemon/state_machine.hpp
- mender-update/daemon/state_machine/state_machine.cpp
- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
- mender-update/daemon/states.hpp
This adds the expected functionality for the daemon state scripts.
Still some things I'm wondering, have a close look at:
* LoadStateFromDB
* How to handle DB errors when running state scripts, and saving state
* The updated tests
> test: Fix and add the daemon state script tests

- common/dbus/platform/asio_libdbus/dbus_client.cpp
It complains locally with clang 14.
> chore: Fix error `lambda capture 'status' is not used`

- mender-update/daemon/state_machine/state_machine.cpp
- mender-update/daemon/state_test.cpp
Since we don't support it, fail instead.
Ticket: MEN-6647
Changelog: Update Control support has been removed from the client.
> chore: Take Update Control into account when upgrading.

- api/CMakeLists.txt
- api/auth.hpp
- api/auth/auth.cpp
- api/auth_test.cpp
- api/client.cpp
- api/client.hpp
- api/client_test.cpp
- common/dbus_test.cpp
- common/http.hpp
- common/http/http.cpp
- common/testing_dbus.hpp
- mender-auth/ipc/server_test.cpp
- mender-update/CMakeLists.txt
- mender-update/daemon/context.cpp
- mender-update/daemon/context.hpp
- mender-update/daemon/state_test.cpp
- mender-update/daemon/states.cpp
- mender-update/deployments.hpp
- mender-update/deployments/deployments.cpp
- mender-update/deployments_test.cpp
- mender-update/inventory.cpp
- mender-update/inventory.hpp
- mender-update/inventory_test.cpp
**Hint for review**: check the commit overview first so that you know what is made nicer in future commits :wink: 
TODO:
Ticket: MEN-6656
> feat: Change Authenticator to fetch authentication data over DBus

- mender-auth/ipc/server.cpp
- mender-auth/ipc/server.hpp
If the `FetchJwtToken()` DBus method is called multiple times in a row while authentication is in progress, only one authentication request to the server should be made.
Ticket: none
> fix(mender-auth): Make FetchJwtToken() a noop if authentication in progress

- mender-auth/cli/actions.cpp
- mender-auth/ipc/server.hpp
Just add the missing identity script, and private key params.
Ticket: MEN-6671
> fix(mender-auth): Remember to pass in the needed params

- .gitlab-ci.yml
`--load-average` causes it to oscillate between full capacity (which rapidly raises load average) and far below capacity (which lowers load average again). This causes the overall execution time to be much slower than just using all the CPUs constantly.
Probably this was a typo, and using all CPUs is what was intended all along.
> test: Fix suboptimal job count when building.

- CONTRIBUTING.md
We got an external request that the link to Jira Help Wanted does not work. Fixing this one.
> docs(CONTRIBUTING): Fix link to Help Wanted Jira filter.

- .gitignore
Introduced in 84c13e9fe047d1c47a2b7cc93ea9f49eef53aacf
> chore: Exclude `main.cmake` from Git ignore list

- mender-update/cli/actions.cpp
`SIGUSR1` is for deployment check and `SIGUSR2` is for inventory update.
> fix: Swap user signals sent

- mender-auth/http_forwarder.hpp
- mender-auth/ipc/CMakeLists.txt
- mender-auth/ipc/server.cpp
- mender-auth/ipc/server.hpp
- mender-auth/ipc/server_test.cpp
Also, in the tests, `TEST_PORT_2` seems to not be necessary (never used together with `TEST_PORT`), so just use the latter.
Ticket: MEN-6664
> chore: Proxy HTTP requests from clients through mender-auth.

- artifact/v3/scripts/executor.hpp
- common/common.hpp
- common/crypto_test.cpp
- common/http.hpp
- common/http_test.cpp
- common/key_value_database/platform/lmdb/lmdb.cpp
- common/key_value_database_lmdb.hpp
Turns out `bool` values are not guaranteed to be initialized to
`false` by default. However, if we explicitly initialize fields
in `http::ClientConfig`, we cannot use designated (named)
initializers. So we need a custom boolean type that acts like a
boolean, but is guaranteed to be initialized to `false` by
default.
Ticket: MEN-6787
Signed-off-by: Vratislav Podzimek <v.podzimek@mykolab.com>
*Plus two small related changes.*
> fix: Use our custom false-initialized boolean in http::ClientConfig

- common/http/platform/beast/http.cpp
- common/http_proxy_test.cpp
- common/http_test.cpp
It's not done automatically and we need to use a callback for
this. However, it's a common thing so Boost has the callback
(functor object) ready for us.
Ticket: MEN-6788
Signed-off-by: Vratislav Podzimek <v.podzimek@mykolab.com>
> fix(https): Enable server host name verification in TLS handshake

- installer/block_device.go
```
commit ff0db6042830bebc7e15b93da7c71eead153f3f9
Date:   Mon Oct 23 10:42:22 2023
fix: Fix possible missing `Sync` call at the very end of the update.
We need to override the `Close` method so that we call `Sync` as the
final thing before closing. Most boards are not affected by this,
because the flushing interval is set to the native sector size of the
board, which, AFAIK, is 512 for all normal block devices except raw
Flash storage. I consider it very unlikely that a filesystem would not
be a multiple of 512 (maybe squashfs?), which means that by the time
we get to `Close()`, `Sync()` will usually have been called already
because the last write was 512 bytes or bigger.
But on raw Flash filesystems it can potentially happen, if the …
```
> fix: Fix possible missing `Sync` call at the very end of the update.

- common/http.hpp
- mender-update/update_module/v3/platform/c++17/fs_operations.cpp
We make sure that the update module file has some executable permissions bits set. It doesn't mean executing it will be allowed, but it's a good enough filter. If the actual execution fails, it will be handled properly.
Ticket: none
Plus one more.
> chore: Drop a TODO about access(X_OK) in DiscoverUpdateModules()

- api/auth_test.cpp
- api/client_test.cpp
- common/dbus.hpp
- common/dbus/platform/asio_libdbus/dbus.cpp
- common/dbus_test.cpp
- mender-auth/ipc/server.cpp
If the method call arrives to the particular `DBusServer` instance, it must have the matching destination set.
Ticket: MEN-6808
> fix: Omit service/destination from method handling spec

- support/mender-inventory-provides
> fix: Make sure `device_type` is submitted with inventory data.

- mender-auth/ipc/server.cpp
On regular operation, `mender-auth` will log errors until accepted by the server and then it will just keep silent. This log should not be very noisy and will give the user a confirmation that the device is has been accepted.
> chore: Add info log line on successful authentication

- src/api/auth/auth.cpp
- src/artifact/v3/header/type_info.cpp
- src/common/CMakeLists.txt
- src/common/identity_parser.hpp
- src/common/identity_parser/identity_parser.cpp
- src/common/identity_parser_test.cpp
- src/common/json.hpp
- src/common/json/json.cpp
- src/mender-update/daemon/context.cpp
Use the same logic than for inventory keys: if the vector has one
element serialize as string, else submit as a list of strings.
> MEN-6813: Serialize identity keys as single strings when possible

- support/mender-authd.service
This aliases the systemd.service for `mender-authd` to `mender-client`, so that
other existing third-party services relying on it will still work transparently.
Ticket: MEN-6812
-------
> chore: Alias mender-authd.service -> mender-client.service

- src/mender-auth/cli/keystore.cpp
Some tests depend on it and it doesn't seem too intrusive for users neither.
> chore: Promote successful key load message to info level

- src/common/conf/conf.cpp
- src/common/conf_test.cpp
- src/common/config_parser.hpp
- src/common/config_parser/config_parser.cpp
- src/common/config_parser_test.cpp
First of all, reverse the order of loading. If the fallback is to have least precedence, then it must be loaded first for the other one to override it.
Then, to match the behavior of the Golang client, we need to change two things:
* We need to allow `ArtifactVerifyKey` and `ServerURL` to appear in both files. This was not previously possible because they were automatically put into the list variant and would trigger an error that you can't use both at the same time.
* The list variants, `ArtifactVerifyKeys` and `Servers` need to override the specified lists in the fallback config file, not add to them.
Ticket: None
> fix: Fix several fallback config parsing bugs.

- src/mender-update/daemon/context.cpp
This simply aligns the keys with the encoding used in the already existing format.
Ticket: None
> fix(state-data): Align the keys with the existing version 2 keys

- src/mender-auth/cli/actions.cpp
- src/mender-update/cli/actions.cpp
While it can be useful for users, this is primarily to make it easier to test for readiness in tests.
> chore: Add readiness log messages to each daemon.

- src/mender-auth/ipc/server.cpp
The old client behaved this way and it seems like `mender-monitor` relies on this behavior to detect being online or offline. Other 3rd party software could also be relying on it.
This fixes the related integration tests.
> MEN-6671: Emit D-Bus signal both on authentication and unauthentication

- src/common/error.hpp
Previously this would just expand to `__LINE__` ad verbatim, as we did
lazy-evaluate it in the macro with `#`.
-------
> chore: expand __LINE__ to a string in the ErrOrReturn macros

- src/artifact/parser_test.cpp
- src/artifact/v3/header/header_info.cpp
- src/artifact/v3/header/type_info.cpp
- src/artifact/v3/payload/payload.cpp
Such comparisons are dangerous, because if you don't also compare the category, you can get false positives.
> chore: Get rid of direct comparisons with `Error::code`.

- src/artifact/lexer.hpp
- src/artifact/parser.cpp
- src/artifact/parser_test.cpp
- src/artifact/tar/CMakeLists.txt
- src/artifact/tar/platform/libarchive/tar.cpp
- src/artifact/tar/platform/libarchive/wrapper.cpp
- src/artifact/tar/platform/libarchive/wrapper.hpp
- src/artifact/tar/tar.hpp
- src/artifact/tar/tar_errors.cpp
- src/artifact/tar/tar_errors.hpp
- src/artifact/tar/tar_test.cpp
- src/artifact/v3/version/version_test.cpp
- src/common/events/events_io.cpp
- src/common/http/platform/beast/http.cpp
- src/common/log/platform/boost/boost_log.cpp
- src/mender-update/cli/cli_test.cpp
- src/mender-update/daemon/states.cpp
- src/mender-update/http_resumer.hpp
- src/mender-update/http_resumer/http_resumer.cpp
- src/mender-update/standalone/standalone.cpp
The `clog` stream has some peculiar properties, and can't be captured properly, neither using stdout nor stderr. We don't really need it, so just switch to `cout` instead.
> chore: Fix inability to capture log output.

- src/mender-update/cli/actions.cpp
- src/mender-update/cli/cli_test.cpp
- src/mender-update/standalone.hpp
- src/mender-update/standalone/standalone.cpp
In a fresh provisioning situation, we need to do so or the info will be empty.
We introduce a new options struct to be able to reuse the existing installation code without printing information, since the bootstrap artifact is a implementation detail and the user might be confused otherwise. Error logs are still printed, so no real info should be lost.
> chore: Make sure bootstrap artifact is installed before returning info.

- Documentation/io.mender.Update1.xml
Ticket: MEN-6648
Title: None
[First version](https://github.com/mendersoftware/mender/pull/1493) rendered incorrectly (didn't respect the link syntax).
This one uses a more basic format for the message.
> docs: correct rendering on the synchronized updates deprecation

- src/common/http/platform/beast/http.cpp
- src/mender-update/daemon/states.cpp
By  calling `DoCancel()` before calling the user handler in all cases
except with a successful 101 Switching Protocols response.
As the user handler will use the `response_`, remove the reset of if
(and of the `request_`) from the `DoCancel()`. This has no side effects
as these classes have noop as destructors and the objects will anyway
later be set to the new request/response in subsequent calls.
> MEN-6671: Close TCP socket when HTTP request/response is completed

- src/mender-update/daemon/states.cpp
- support/modules/rootfs-image
```
commit fde5b0469a7f2bd2c81638c1ded553d0bd233512
Date:   Tue Nov 28 12:45:02 2023
chore: Add a message when deployment has finished.
commit ab31b5626362b91ee3bbc0eaf8f81caad5d56f61
Date:   Tue Nov 28 09:40:04 2023
fix: Make partition checking more robust in every state.
In particular, this prevents the client from erronously committing a
rootfs-image update if it's paused in the ArtifactReboot state, and
then restarted through `systemctl restart` instead of through a
reboot. Now it checks that the root partition is what we expect.
This has been a bug in the Golang client too, so we want a changelog
entry for this. …
```
> fix: Make partition checking more robust in every state.

- src/mender-update/deployments/platform/boost_log/deployments.cpp
I haven't been able to reproduce this in our CI, only locally, so it's possible that the behavior has changed between libc versions. Checking for existence should be safe in either case though.
Our integration tests check for the submission of deployment logs for failed deployments already.
Ticket: MEN-6867
> chore: Fix missing deployment logs in certain cases.

- support/mender-authd.service
After further discussion, we decided not have this alias and instead adjust every other dependency to the new systemd service name.
Ticket: MEN-6858
Changelog: systemd service `mender-client` does not exist anymore. Dependencies shall depend either `mender-authd` or `mender-updated`.
This reverts commit a807f996468da5911b1cf3e81ddbd8f31f4a1980.
> MEN-6858: Remove mender-client systemd service (alias) completely

- src/mender-auth/cli/actions.cpp
This adds a signal handler for SIG{TERM,INT,QUIT} to mender-auth, so that the
daemon exits gracefully in these circumstances by stopping the event loop.
Ticket: MEN-6733
> feat: Add a termination signal handler the mender-auth

- src/CMakeLists.txt
- src/api/auth/auth.cpp
- src/api/auth_test.cpp
- tests/Dockerfile.daemon
The design is that the entry level function `WithToken` should either
return error synchronously or eventually call the handler
asynchronously.
This fixes the issue where `mender-update` will abort with an unhandled
event. What was happening before is that an error while connecting to
the bus would post two events and later the state machine will handle
the second one from the `Idle` state.
> MEN-6836: Do not call the user's callback when returning an error

- Documentation/CMakeLists.txt
It should be `interfaces` according to:
* https://dbus.freedesktop.org/doc/dbus-api-design.html
> fix: Amend D-Bus interface files path

- main.cmake
Remove all of the extra if (${PLATFORM} STREQUAL linux_x86) lines in main.cmake and unify them into a single if statement. Logic for other platforms can be added to the else() statement at a later date.
> chore: clean up platform logic in main.cmake

- src/mender-update/context/context.cpp
- tests/src/mender-update/cli/cli_test.cpp
Just make sure that they show up in the logs, as the mismatch can be pretty confusing otherwise.
> chore(context): Log provides/depends mismatches at error level

- Documentation/CMakeLists.txt
- cmake_uninstall.cmake.in
- src/mender-auth/CMakeLists.txt
- src/mender-update/CMakeLists.txt
- support/CMakeLists.txt
Older CMake versions do not support `--component=...` syntax, so use an space instead.
> build: Modify syntax for compatibility with CMake 3.18

- README.md
With the mender-setup tool being factored out, somebody who just follows the instructions in the README has no way to obtain a working configuration.
Hence, add a reference to the repository and mention that other configuration flows exist.
Ticket: None
```
```
Thank you!
> fix: add mender-setup to README

- CMakeLists.txt
It's redundant, since it already exists in 84c13e9fe.
This reverts commit 0b923f656ea8621678b43f849ac71daba32737f3.
> Revert "build: Set MinSizeRel as the default build type"

- src/mender-update/daemon/state_machine/state_machine.cpp
- tests/src/mender-update/daemon/state_test.cpp
This came about because the main state machine inspects the `ctx.deployment.rollback_failed` variable, which is set in the `deployment_tracking` state machine. We always want the setting to happen first, and in one corner case this did not happen if there were no intervening states between the inspection and the previous state.
Illustrating with an example. In most cases it would work because:
```
main_state.OLD_STATE
deployment_tracking.OLD_STATE
|
v
main_state.INTERMEDIARY_STATE
deployment_tracking.NEW_STATE.<set rollback_failed flag>
|
v
main_state.NEW_STATE.<inspect rollback_failed flag>
```
But in the simplest of transitions, it would break, like this:
```
main_state.OLD_STATE
deployment_tracking.OLD_STATE
|
v
main_state.NEW_STATE.<inspect rollback_failed flag> …
```
> fix: Swap order of daemon state machines.

- src/client_shared/conf/conf.cpp
- src/client_shared/conf/conf_cli_help.cpp
- tests/src/mender-auth/cli/cli_test.cpp
- tests/src/mender-update/cli/cli_test.cpp
Note in particular that we leave one instance of the old flag behind in our tests. The flag was never tested explicitly, just implicitly through a lot of other tests. So I just picked one at random where I kept the old flag.
Changelog: Replace `--data` flag with `--datastore` flag. This aligns better with the environment variables with the same names. The old `--data` flag is still accepted for backwards compatibility, but note that it does not have the same meaning as the `MENDER_DATA_DIR` environment variable (hence the rename).
Ticket: None
> feat: Replace `--data` flag with `--datastore` flag.

- src/common/state_machine.hpp
Otherwise the first state will not be entered unless there is an event to trigger it.
> chore: Make sure the event loop is kicked even without a starting event.

- src/mender-update/daemon/context.hpp
- src/mender-update/daemon/states.cpp
Note that this fix only works "once". IOW if you reject a device and then re-admit it later, then it won't submit inventory again, but will follow the regular schedule.
Ticket: None
> fix: Submit inventory as soon as the device is accepted.

- app/state.go
- app/state_test.go
> fix: doing so return 1 in Download_Enter state scripts aborts instead of retrying in an endless loop

- src/mender-update/deployments/deployments.cpp
Discovered in review of a copy-pasted version of this code into mendersoftware/mender-update-orchestrator#30.
Ticket: none
> fix: Ensure enough body writer capacity if no Content-Length sent by deployments API

- src/mender-update/update_module/v3/platform/c++17/update_module_call.cpp
Changelog: Fix a bug where a failure in checking the working directory will not exit cleanly from `Cleanup` state.
> fix: Fix error checking for Update Module's working directory

- src/common/key_value_parser.hpp
- src/common/key_value_parser/key_value_parser.cpp
- tests/src/common/key_value_parser_test.cpp
The MultiValued maps are distinguished by the plural "Values" name.
> chore: Add Key Value Parser for single-value maps.

- app/state.go
- app/state_test.go
ticket: MEN-6402
Changed the code so when encountering failures due to signature it goes into the update-error state, which will allow it to run Download_Error.
> fix: so the Download_error state script gets executed for failures due to signature

- src/client_shared/conf.hpp
- src/client_shared/conf/conf_cli_help.cpp
- src/mender-update/cli/cli.cpp
- tests/src/client_shared/conf_test.cpp
Updating CLI help screen to show arguments for commands, and updating the help screen to show more options and commands
Ticket: MEN-6986
> chore: updating CLI help screen

- main.cmake
C++ `expected` and `optional` replacement libraries are header only and we don't need to include their CMake projects.
The motivation of removing it is to not add a requirement on more recent versions of CMake that are used in vendored projects (namely: `expected` requires CMake 3.14).
This was fixed implicitly in master when all the vendored projects were moved to a separate directory. See in the following commit that we removed the `add_subdirectory` and moved only the `include` parts:
* https://github.com/mendersoftware/mender/commit/d9946929a63dc45e5acb6a73731ab8dd4b3b8391
> build: Remove vendored CMake projects

- support/modules-artifact-gen/directory-artifact-gen
- support/modules-artifact-gen/docker-artifact-gen
- support/modules-artifact-gen/single-file-artifact-gen
Changelog: Returns an error when passing type, or when passing metadata to docker-artifact gen, and overrides output path
and name when passed as passthrough argument.
Ticket: MEN-7110
> chore: changed parsing of some passthrough args in generators

- .gitlab-ci.yml
It seems like `buster-backports` distribution (backports for today's oldoldstable) has been removed from `deb.debian.org`.
> ci: Use Debian archives for `buster-backports`

- support/CMakeLists.txt
Use it to customize the location of the systemd unit files. Usually it is set to `/lib/systemd/system`.
Ticket: None
> feat: Add `SYSTEMD_UNIT_DIR` CMake variable.

- .gitlab-ci.yml
The code that accepts `CI_BRANCH` as a generic environment variable is actually not released upstream, and the latest pypi avilable version relies on `TRAVIS_*` type of variable.
See: https://github.com/eddyxu/cpp-coveralls/compare/v0.4.2...47f638727512126bc16b1365560854a86db70e7e#diff-b1eda260daddc41aa91c216b3b054933cc85304b6d5e3235c652f0b48c59fcf9R46
As we were missing the branch name, in the eyes of coveralls the "master" branch is frozen on golang code.
> ci: Fix coverage reporting for branches

- .gitlab-ci.yml
- support/CMakeLists.txt
Use it to customize the location of the systemd unit files. Usually it is set to `/lib/systemd/system`.
Ticket: None
(cherry picked from commit 943b8198bff3328229f0f3055989807836c9f7d6)
> 4.0.x: feat: Add `SYSTEMD_UNIT_DIR` CMake variable.

- support/modules/rootfs-image
PARTUUID device paths (e.g. /dev/disk/by-partuuid/b3c4f349-1180-45e1-9a3d-0a6697f4960e) are symlinks to the regular device paths (e.g. /dev/sda2). They need to be resolved first for the rest of the code to succeed.
Changelog: Fix committing mender-update artifacts when using mender-partuuid
Ticket: None
I have been using a mender-partuuid setup under Yocto Dunfell for the past 4 years. This needed fixes from me in the past such as https://github.com/mendersoftware/meta-mender/pull/1685.
I'm now in the process of upgrading to Yocto Scarthgap (using https://github.com/enlyze/meta-mender/tree/feature/scarthgap-support-for-master) and noticed this regression.
> fix: Resolve PARTUUID device paths in rootfs-image

- src/common/http/http_resumer.cpp
- tests/src/common/http_resumer/http_resumer_test.cpp
If an HTTP download is resumed without the client ever having learned the `content_length`, it will request the update with the following invalid header:
```
Range: bytes=0--1
```
Ticket: #8880
> fix: Invalid Range request when content_length is 0 (unknown)

- src/mender-update/daemon/context.cpp
If a deployment fails before the artifact info is parsed, e.g. when a deployment is started but S3 is blocked by a firewall, the JSON state data describes an artifact with an empty `payload-types` list. If mender-update is subsequently restarted, the JSON state data unmarshaler would exit early and return invalid state data (empty deployment ID) triggering an assert in `DeploymentClient::PushStatus`. The client would never recover from this.
Ticket: None
---
I reported this issue to support@northern.tech a couple of weeks ago, so there might be an internal Mender ticket for this (edit: MEN-7327). The ticket contains steps to reproduce this problem. [Here](https://github.com/user-attachments/files/15586541/mender-update-trace.log) is a trace-level log.
I don't know where …
> fix: parse artifact ID before validating payload size

- src/mender-update/context.hpp
- src/mender-update/context/context.cpp
- tests/src/mender-update/context_test.cpp
Replaced the regex in FilterProvides by matching a substring with the whole provides-string. This is done to remove ExceptionToErrorOrAbort. Added unit tests and a testing-function to context.
Ticket MEN-7323
> chore: Rewrote FilterProvides to not use regex

- src/common/crypto/platform/openssl/crypto.cpp
Libcrypto does not load the openssl.cnf file automatically. This removes the need for manually having to export e.g. `PKCS11_MODULE_PATH` as an env var when loading a pkcs11 interface (if it's already specified in openssl.cnf).
> fix: Make crypto load and use the openssl.cnf file

- src/mender-update/daemon/state_machine.hpp
- src/mender-update/daemon/state_machine/state_machine.cpp
- src/mender-update/daemon/states.cpp
- src/mender-update/daemon/states.hpp
- support/mender-updated.service
- tests/src/mender-update/daemon/state_test.cpp
The problem is that once we have entered the `sync_leave_download`
internal state, a deployment has started, and a deployment always has
to be ended, to properly clean up. This is fine when
`sync_leave_download` is successful and proceeds into subsequent
download states, which always end with the
`end_of_deployment_state`. But if `sync_leave_download` fails, then it
goes directly to `sync_error`, which does not know about the
deployment, and does not go to `end_of_deployment_state`.
Fix this by creating a dedicated `sync_error_download` state.
This bug happened only occasionally in the test
`test_state_scripts[Corrupted_script_version_in_etc-test_set11]` in
the integration repository, typically under load. The reason it
happened only occasionally is that the test is programmed to fail in …
> fix: Fix crash when Sync_Leave returns error during a deployment.

- src/mender-update/progress_reader/progress_reader.cpp
- src/mender-update/progress_reader/progress_reader.hpp
- tests/src/mender-update/progress_reader/progress_reader_test.cpp
Due to a bug in the logic, the progress was being updated after every block, even if the percentage number was not changing. This made the reading/writing of Artifacts slow and noisy.
> MEN-7159: Progress reader updates the output only when progressing

- support/modules/rootfs-image
This pull request cleans up several shellcheck warnings, incuding:
- SC2005 useless echo
- SC2166 Preffer || or && instead of -o
- SC2086 Douple quote
Ticket: None
> fix: cleanup shellcheck warnings for rootfs-image module

- src/artifact/sha/sha.hpp
- src/common/CMakeLists.txt
- src/common/crypto/platform/openssl/crypto.cpp
- src/common/events/events_io.cpp
- src/common/http/http.cpp
- src/common/http/platform/beast/http.cpp
- src/common/platform/dbus/asio_libdbus/dbus.cpp
- tests/src/common/http_resumer/http_resumer_test.cpp
This builds on #1676.
Originally we wanted to include this list:
* `-Wbad-function-cast`
* `-Wcast-qual`
* `-Wconversion`
* `-Wpacked`
* `-Wpadded`
* `-Wpointer-arith`
* `-Wredundant-decls`
* `-Wswitch-default`
but since it is from C, several changes were made:
* `-Wbad-function-cast` - This does not work with C++.
* `-Wcast-qual` - We should use the C++ specific `-Wold-style-cast` instead, which catches more cases than this one.
* `-Wpadded` - This only affects space usage, and would take some effort to fix. Since the C++ client is no longer being pursued for the embedded side, I chose to omit this one now, although it could be revisited later.
* `-Wswitch-default` - This one is a bit tricky, IMHO it does more harm than good to add this. A typical example of where this is a problem is …
> build: Enable some more warnings by default.

- main.cmake
Otherwise `CMAKE_BUILD_TYPE=UndefSan`, as in CI tests, has no effect.
> build: Include missing sanitizer options

- src/common/common.hpp
- src/common/json.hpp
- src/common/yaml.hpp
- src/mender-update/deployments/deployments.cpp
- src/mender-update/inventory.cpp
The `StringTo` function was supposed to be used in 15162ba17b77a3867a, but looks I forgot it. Take them into use and fix the issue that popped up when there is a signed/unsigned mismatch.
> chore: int conv: Use utility functions and fix their issues.

- .gitlab-ci.yml
This trigger is meant to render the Device API page on changes for the D-Bus API documented at `Documentation/*.xml`.
This happens very seldom, and the Mender Docs site is anyway rendered often enough to publish these withing a day.
> QA-794: Remove trigger to `mender-docs-site`

- src/common/CMakeLists.txt
- src/common/crypto/platform/openssl/crypto.cpp
- src/common/path.hpp
- src/common/path/platform/c++17/path.cpp
- src/common/path/platform/posix/path.cpp
- src/mender-auth/cli/keystore.cpp
- tests/src/common/CMakeLists.txt
- tests/src/common/crypto_test.cpp
- tests/src/mender-auth/cli/keystore_test.cpp
I intentionally kept the changes from the last commit separate so that they can be easily dropped (or reverted in the future may that be necessary).
> Fix: Private key file permissions

- support/CMakeLists.txt
- support/mender-authd.service
- support/mender-data-dir.service
- support/mender-updated.service
Both the mender-authd.service and mender-udpated.service files have
mender-client-data-dir.service in the "After=" line. However, this
service file isn't provided by the mender package. Instead, the
mender-client-data-dir.service file currently resides in the
meta-mender repository. This means that the mender-authd.service and
mender-updated.service files are incorrect, but currently "just work"
because of the WantedBy in the mender-data-dir.service file.
Even though "After" does not mean "required" it can still be confusing
to users as to where this file comes from. Furthermore, a user may not
want the service file to exist at all, as their build setup may create
the /data directory (or /var/lib/mender) during the image creation.
- Move the mender-data-dir.service file into the mender …
> chore: add mender-data-dir.service file

- src/artifact/tar/platform/libarchive/wrapper.cpp
- src/artifact/tar/platform/libarchive/wrapper.hpp
- tests/src/artifact/tar/tar_test.cpp
The tar format says [1]:
> The end of an archive is marked by at least two consecutive zero-filled records.
Which means that if a file is a valid tar archive, a copy of the file with blocks of zeroes appended to its end is still a valid archive, with the same content.
Thus we cannot consider extra zeroes in a file for which libarchive tells us `ARCHIVE_EOF` as superflous data.
[1] https://en.wikipedia.org/wiki/Tar_(computing)#File_format
Ticket: MEN-7810
> fix: Allow blocks of zeroes after ArchiveEOF

- src/mender-update/standalone/standalone.cpp
It is not related to the major bump of the Client, but it was reported in Mender Hub with this suspicion so let's keep the Git commit aligned.
While working on internal improvements to support more advance use cases in standalone mode, we introduced a new version of the standalone store. See commit 2c1d92212.
In that commit it can be seen the code dealing with the migration (iow an update triggered from standalone store v1 being committed with standalone store v2): when missing the state, set the state that will trigger the state machine into continuing into commit state.
However a later commit aiming to increase robustness of the process added new states into the standalone state machine, and the migration from store v1 was not taking into account, provoking a regression where the client …
> MEN-7818: Fix regression updating from Client v4 to Client v5 or newer

- src/api/auth.hpp
- src/api/auth/auth.cpp
- src/api/client.cpp
- src/api/client.hpp
- src/mender-update/daemon/context.hpp
- src/mender-update/daemon/state_machine/state_machine.cpp
- src/mender-update/daemon/states.cpp
- src/mender-update/inventory.hpp
This fixes the case where e.g. a third party tool re-authenticates by using the D-Bus API while mender-update is waiting for the next poll interval to expire. The inventory will now be resubmitted when the poll triggers.
Ticket: MEN-7873
> fix: Clear the inventory data hash on re-authentication

- src/mender-update/daemon/states.cpp
When implementing the backoff for errors when polling for deployment or submitting inventory, we added an exception for unauthorized errors. After looking at how it was done in Mender Client 3, we discovered that such an exception was not present there, and that the backoff should be triggered for all types of errors.
Changelog: All errors when polling for deployment or submitting inventory are retried with an exponential backoff.
Ticket: MEN-7938
> fix: retry polling on all errors

- src/mender-update/daemon/context.cpp
- src/mender-update/daemon/context.hpp
- src/mender-update/daemon/state_machine.hpp
- src/mender-update/daemon/state_machine/state_machine.cpp
- src/mender-update/daemon/states.cpp
- src/mender-update/daemon/states.hpp
From the code point, the issue was that the re-scheduling of new polls for updates or inventory were done from the states _after_ the sync state, so unless the state machine reached that point the new polls would not be scheduled.
Fix by creating two new states, that just do the re-scheduling, between idle and sync. Note that the timer(s) have now been moved to the context object so that it can be accessed from multiple states (namely, update polling and submit inventory states which would need to manipulate the timer for exponential back-off retries.
Changelog: Fix issue where any error in Sync state (triggered for example with an error in Sync_Enter or Sync_Leave state scripts) leaves the client stuck in idle state forever and no new polls for update nor submit of inventory would be …
> MEN-7900: Fix Mender client getting stuck after failure in sync state

- .gitlab-ci.yml
The oldest LTS in mender-dist-packages is debian 11 (bullseye)
> ci: align backward-compat with oldest oldest LTS at mender-dist-packages

- src/mender-auth/api/auth/embedded_auth.cpp
Made a new pull request for this to easier integrate it with my diverging fork.
> fix: Fix wrong parameter order for AuthData

- src/artifact/v3/payload/payload.cpp
This fixes the case where we access an object after it has been moved.
Ticket: MEN-7980
> fix: Fix undefined behaviour after a move operation

- src/artifact/tar/platform/libarchive/tar.cpp
When reading the archive entry size from the tar archive, the size was cast to size_t before storing it as an int64_t.
Ticket: MEN-8062
> fix: Fix deployment on 32 bit systems when rootfs is larger than 4Gb

- src/artifact/tar/platform/libarchive/tar.cpp
When reading the archive entry size from the tar archive, the size was cast to size_t before storing it as an int64_t.
Ticket: MEN-8062
Signed-off-by: John Olav Lund <john.olav.lund@northern.tech>
(cherry picked from commit 8ba599b6ec48b7be9f4e5181593ec8c34d78b271)
> 4.0.x: fix: Fix deployment on 32 bit systems when rootfs is larger than 4Gb

- src/artifact/tar/platform/libarchive/tar.cpp
When reading the archive entry size from the tar archive, the size was cast to size_t before storing it as an int64_t.
Ticket: MEN-8062
> 5.0.x: fix: Fix deployment on 32 bit systems when rootfs is larger than 4Gb

- src/mender-update/context/context.cpp
- src/mender-update/standalone/standalone.cpp
> fix: Use EscapeString when generating JSON for supplied artifact data

- support/mender-inventory-geo
- [√] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.
```
fix: wget effectively hangs when using ipinfo.io in restricted environments
Changelog: Add retry limit to inventory geo script to prevent hanging
Ticket: None
```
- [√] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.
In …
> fix: inventory-geo appears to hang while wget retries many times

- src/mender-update/context/context.cpp
- src/mender-update/standalone/standalone.cpp
Ticket: MEN-7974
Signed-off-by: John Olav Lund <john.olav.lund@northern.tech>
(cherry picked from commit d74fba313f3131121c9cc1a8a8e6462691658b3b)
> 5.0.x: fix: Use EscapeString when generating JSON for supplied artifact data

- src/CMakeLists.txt
- src/common/http/platform/beast/http.cpp
- tests/src/common/http_test.cpp
The Mender client version will now be sent to the server through the User-Agent header.
Tiicket: MEN-1979
> feat: Add User-Agent header to HTTP requests

- tests/src/common/platform/testing_dbus.hpp
> test: suppress leaks from libdbus in ASan tests

- README.md
- cmake/aarch64.cmake
Add a toolchain file for aarch64 and update the readme with requirements and steps for building
> chore: add toolchain file for aarch64

- support/modules/rootfs-image
The "fallback" configuration file at /var/lib/mender/mender.conf is optional. We should therefore not log an error if it is not present.
Ticket: None
```
```
The fallback configuration file /var/lib/mender/mender.conf is optional. When it's missing we end up with those error logs from the rootfs-image update module:
```
Update Module output (stderr): can't open /var/lib/mender/mender.conf: …
```
> fix: rootfs-image: Avoid logging errors if config file is missing.

- tests/Dockerfile.daemon
The following errors are present in mendersoftware/mender-client-docker:mender-master
```
mender-auth: error while loading shared libraries: libboost_log.so.1.83.0: cannot open shared object file: No such file or directory
mender-update: error while loading shared libraries: libboost_log.so.1.83.0: cannot open shared object file: No such file or directory
```
> chore: bump libboost_log to 1.83.0

- support/mender-inventory-geo
Ticket: MEN-8548
Changelog: Make mender-inventory-geo work with both wget provided by busybox and full version of wget
Please see https://northerntech.atlassian.net/browse/MEN-8548?focusedCommentId=122504 for dicsussion about what was broken.
Note: script is written in POSIX-complaint way, and no longer depends on bash (runs on sh/dash).
> fix: Make mender-inventory-geo work with busybox.wget

- .gitlab-ci.yml
- tests/Dockerfile.daemon
Mender supports tool installation using repositories now. This is the correct way of installing the packages instead of downloading fixed version as a *.deb files.
Ticket: QA-1090
> chore: Use repo instead of standalone deb packages

- src/common/http.hpp
- src/common/http/platform/beast/http.cpp
If network connection is lost while downloading an artifact, the client
can hang when calling `beast::http::async_read_some` in `AsyncReadNextBodyPart`.
Implement an AsyncWait timer that triggers an error handler after 5 minutes.
Ticket: MEN-8717
Changelog: Fix an issue where mender-update hangs when network connection is
lost during artifact download. Implement a 5-minute timeout in `AsyncReadNextBodyPart`
to allow the HTTP resumer to resume the download.
> fix: add timeout to prevent hanging downloads on connection loss

- .gitlab-ci.yml
Use the workstation-tools repo and switch to stable packages.
Ticket: QA-1090
See failures: https://gitlab.com/Northern.tech/Mender/mender/-/pipelines/2069741346
> ci: Update mender-artifact repository

- src/client_shared/CMakeLists.txt
- src/client_shared/config_parser.hpp
- src/client_shared/config_parser/config_parser.cpp
- src/common/CMakeLists.txt
- src/common/device_tier.cpp
- src/common/device_tier.hpp
- src/mender-auth/api/CMakeLists.txt
- src/mender-auth/api/auth.hpp
- src/mender-auth/api/auth/auth.cpp
- src/mender-auth/cli/actions.cpp
- src/mender-auth/ipc/server.cpp
- src/mender-auth/ipc/server.hpp
- src/mender-update/CMakeLists.txt
- src/mender-update/context/context.cpp
- tests/src/client_shared/config_parser_test.cpp
- tests/src/common/CMakeLists.txt
- tests/src/common/device_tier_test.cpp
- tests/src/mender-auth/api/auth_test.cpp
- tests/src/mender-update/context_test.cpp
Ticket: MEN-8636
Changelog: Add device tier support to authentication requests. The client now sends a 'tier' parameter in authentication requests, supporting "standard" (default), "micro", and "system" tiers. The tier is configurable via the DeviceTier configuration option, with "standard" as the default.
> feat: send tier in authentication request
